### ISSUE TITLE
Статический IP адрес

### ISSUE THREAD

**Issue by Vovaka1** [vvip-68/GyverPanelWiFi#100]
Приветствую. В крайней версии перестал сохраняться статический IP адрес. При нажатии на "Сохранить" на матрице показывается новый IP, но после перезагрузки приходиться исправлять в приложении на IP выданный роутером. Пробовал заливать (в ESP32) версию 1.07, там сохраняется.

**Comment by vvip-68** [comment]
Наблюдаю, да. Самое смешное - что код абсолютно одинаковый для ESP32 и для ESP8266
Причин понять не могу - в этом куске кода, связанном с адресами давно ничего не менялось, вроде.
По наблюдениями - он сохраняется и далее используется ДО обновления / загрузки прошивки в контроллер.
То есть - залил, настроил - можно пользоваться. Но после обновления - слетает. В чем траблы - понять не могу. Когда / если пойму - починю. Пока - никак. Если сможете понять в чем дело - напишите.

**Comment by vvip-68** [comment]
Во, вроде понял в чем дело. Обновил файл eeprom.ino
Должно поправиться...

**Comment by vvip-68** [comment]
И еще там файлы затронуты были - снова обновил.

**Comment by Vovaka1** [comment]
Дважды качал архив. Не проходит компиляция.
Ошибка  'runTextSound' was not declared in this scope 
Подсвечена строка 335  runTextSound = -1;   // Нет звука, сопровождающего строку

**Comment by vvip-68** [comment]
Исправил
