### ISSUE TITLE
Не компилится 1.08 версия

### ISSUE THREAD

**Issue by mcvall** [vvip-68/GyverPanelWiFi#103]
C:\GyverPanelWiFi-master\GyverPanelWiFi-master\firmware\GyverPanelWiFi_v1.08\custom.ino: In function 'void checkIdleState()':
custom:639:36: error: 'wait_play_file_finished' was not declared in this scope
          _**(thisMode == MC_SDCARD && wait_play_file_finished && !play_file_finished))**_
                                    ^
custom:639:64: error: 'play_file_finished' was not declared in this scope
          (thisMode == MC_SDCARD && wait_play_file_finished && !play_file_finished))
                                                                ^
exit status 1
'wait_play_file_finished' was not declared in this scope

**Comment by vvip-68** [comment]
Исправил.
