### ISSUE TITLE
Не работает бегущая строка

### ISSUE THREAD

**Issue by dronov1981** [vvip-68/GyverPanelWiFi#106]
Привет! плата wemos d1 mini прошивка и приложение последние (1,08) 

Не могу запустить бегущую строку, при переходе на настройки текста и нажатию кнопки просмотр ничего не происходит, все остальное работает корректно и стабильно

**Comment by vvip-68** [comment]
У кого-нибудь еще такое происходит?
Судя по описанным симптомам - как раз похоже, что приложение не 1.08, а старая версия, которая не совместима с прошивкой 1.08. Попробуйте обновить приложение на телефоне.

**Comment by dronov1981** [comment]
поставил сейчас 1,09 из репозитория результат тот же может матрица 10х10 маловата?

**Comment by vvip-68** [comment]
1. Бегущая строка работает на матрицах с высотой от 8 строк.
2. Не существует приложения версии 1.09. Последняя версия приложения - 1.08, она совместима с прошивкой 1.09

**Comment by dronov1981** [comment]
не смогу прислать, приложение 1 стоит на симуляторе, второе на TV приставке, телефона с адройдом нет (

**Comment by vvip-68** [comment]
Что, настолько приложение не работает, что даже фотографию (с четко-различимым) содержимым с ЕМ-приставки или скриншот окна симулятора Андроид сделать не получается? Ну нифига ж себе....
Про часы - вообще ничего не понял. Консультации по телефону не оказываю.

**Comment by vvip-68** [comment]
Матрица 10x10 для часов, кстати, маловата. Минимальный размер для горизонтальных часов 15x5, для вертикальных - 7x11. Часы на такой матрице работать не должны. Только в виде бегущей строки...
