### ISSUE TITLE
Погода через сервис openweathermap

### ISSUE THREAD

**Issue by user44** [vvip-68/GyverPanelWiFi#108]
Не правильно работает парсинг погоды через сервис openweathermap. При выводе через бегущую строку {WT} постоянно показывает 0 градусов. Как решить?

**Comment by vvip-68** [comment]
Какой у вас код города для OpenWeatherMap?

**Comment by user44** [comment]
код 699311

**Comment by vvip-68** [comment]
Для вашего кода прямо сейчас возвращается сервисом и отображается на матрице -13

**Comment by user44** [comment]
Возвращается то да и даже через монитор порта возвращается -13, но на матрице выводится 0 (ноль) всегда. Не пойму почему так(

**Comment by vvip-68** [comment]
Ну, поскольку сия ситуация проявляется ТОЛЬКО у вас - видимо и отлаживать / искать причину придется вам самостоятельно...

**Comment by user44** [comment]
попробую обновить прошивку
