### ISSUE TITLE
Мало паттернов

### ISSUE THREAD

**Issue by 80Stepko08** [vvip-68/GyverPanelWiFi#11]
Помните ту тему, которую я скинул, так вот там я нарисовал много паттернов, но одна совместима с новыми цветами  
>      CHSV colorMR[12] = {
>      CHSV(0, 0, 0),              // 0 - Black
>        CHSV(HUE_RED, 255, 255),    // 1 - Red
>        CHSV(HUE_GREEN , 255, 255),  // 2 - Green
>        CHSV(HUE_BLUE, 255, 255),   // 3 - Blue
>        CHSV(HUE_YELLOW, 255, 255), // 4 - Yellow
>        CHSV(0, 0, 220),            // 5 - White
>        CHSV(0, 255, 255),              // 6 - плавно меняеться в цикле (фон)
>        CHSV(0, 255, 255),              // 7 - цвет равен 6 но +64
>        CHSV(HUE_ORANGE, 255, 255),
>        CHSV(HUE_PINK, 255, 255),
>        CHSV(HUE_PURPLE, 255, 255),
>        CHSV(HUE_AQUA, 255, 255),
>    };

https://community.alexgyver.ru/threads/wifi-lampa-budilnik-proshivka-firelamp_jeeui-gpl.2739/post-55231

**Comment by vvip-68** [comment]
Спасибо, утянул к себе...
