### ISSUE TITLE
Ничего не понятно

### ISSUE THREAD

**Issue by igoroff** [vvip-68/GyverPanelWiFi#110]
LittleFS Error: mklittlefs not found!

**Comment by vvip-68** [comment]
А гугль что говорит по данному вопросу?
В настройках распределения памяти вообще место под файловую систему выделено?

**Comment by igoroff** [comment]
Гугль не помог, или я настолько неумён.
Выделенно.

**Comment by igoroff** [comment]
Я просто не туда забежал. 
LittleFS.h: No such file or directory
Вот такая ошибка. Просто та ошибка следствие этой

**Comment by vvip-68** [comment]
Контроллер ESP32? Установите библиотеку в менеджере библиотек.

**Comment by igoroff** [comment]
Спасибо, помогло
