### ISSUE TITLE
Ошибка при компиляции

### ISSUE THREAD

**Issue by Dmitro4ekalov** [vvip-68/GyverPanelWiFi#111]
Здравствуйте! такая ошибка при компиляции:
C:\Users\Максим\Documents\Arduino\GyverPanelWiFi_v1.09\clock.ino: In function 'void checkAutoMode5Time()':
clock:1187:80: error: 'useweather' was not declared in this scope
C:\Users\Максим\Documents\Arduino\GyverPanelWiFi_v1.09\clock.ino: In function 'void checkAutoMode6Time()':
clock:1207:80: error: 'useweather' was not declared in this scope
exit status 1
'useweather' was not declared in this scope
Помогите, в чем причина?

**Comment by vvip-68** [comment]
Затрудняюсь сказать. Вы что-то исправляли?
В моем экземпляре скетча в 'mn[ строках - переменная useWeather.
А переменная useweather - действительно неизвестна...

**Comment by Dmitro4ekalov** [comment]
да, useWeather на useweather я сам исправлял, думал может ошибка в большой букве W.
а вот с оригиналом так же
C:\Users\Максим\Documents\Arduino\GyverPanelWiFi_v1.09\clock.ino: In function 'void checkAutoMode5Time()':
clock:1187:80: error: 'useWeather' was not declared in this scope
C:\Users\Максим\Documents\Arduino\GyverPanelWiFi_v1.09\clock.ino: In function 'void checkAutoMode6Time()':
clock:1207:80: error: 'useWeather' was not declared in this scope
exit status 1
'useWeather' was not declared in this scope

**Comment by vvip-68** [comment]
А... У вас наверное в настройках стоит `#define USE_WEATHER 0`
Мой косяк. Сейчас исправлю...

**Comment by vvip-68** [comment]
Исправил, забирайте 
clock.ino
