### ISSUE TITLE
ошибки при компиляции ESP32

### ISSUE THREAD

**Issue by Dmitro4ekalov** [vvip-68/GyverPanelWiFi#112]
In file included from sketch\a_def_hard.h:432:0,
                 from C:\Users\Максим\Documents\Arduino\GyverPanelWiFi_v1.09\GyverPanelWiFi_v1.09.ino:19:
C:\Users\������\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\ArduinoOTA\src/ArduinoOTA.h:84:5: error: 'WiFiUDP' does not name a type
     WiFiUDP _udp_ota;
     ^
                       ^
C:\Users\Максим\Documents\Arduino\GyverPanelWiFi_v1.09\GyverPanelWiFi_v1.09.ino: In function 'void startWiFi(long unsigned int)':
GyverPanelWiFi_v1.09:325:23: error: no matching function for call to 'WiFiClass::disconnect(bool)'
In file included from C:\Users\������\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\ArduinoOTA\src/ArduinoOTA.h:4:0,
                 from sketch\a_def_hard.h:432,
                 from C:\Users\Максим\Documents\Arduino\GyverPanelWiFi_v1.09\GyverPanelWiFi_v1.09.ino:19:
C:\Program Files (x86)\Arduino\libraries\WiFi\src/WiFi.h:130:9: note: candidate: int WiFiClass::disconnect()
     int disconnect(void);
         ^
C:\Program Files (x86)\Arduino\libraries\WiFi\src/WiFi.h:130:9: note:   candidate expects 0 arguments, 1 provided
GyverPanelWiFi_v1.09:329:8: error: 'class WiFiClass' has no member named 'mode'
GyverPanelWiFi_v1.09:329:13: error: 'WIFI_STA' was not declared in this scope
GyverPanelWiFi_v1.09:341:40: error: no matching function for call to 'WiFiClass::config(IPAddress, IPAddress, IPAddress, IPAddress, IPAddress)'
In file included from C:\Users\������\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\ArduinoOTA\src/ArduinoOTA.h:4:0,
                 from sketch\a_def_hard.h:432,
                 from C:\Users\Максим\Documents\Arduino\GyverPanelWiFi_v1.09\GyverPanelWiFi_v1.09.ino:19:
C:\Program Files (x86)\Arduino\libraries\WiFi\src/WiFi.h:85:10: note: candidate: void WiFiClass::config(IPAddress)
     void config(IPAddress local_ip);
          ^
C:\Program Files (x86)\Arduino\libraries\WiFi\src/WiFi.h:85:10: note:   candidate expects 1 argument, 5 provided
C:\Program Files (x86)\Arduino\libraries\WiFi\src/WiFi.h:92:10: note: candidate: void WiFiClass::config(IPAddress, IPAddress)
     void config(IPAddress local_ip, IPAddress dns_server);
          ^
C:\Program Files (x86)\Arduino\libraries\WiFi\src/WiFi.h:92:10: note:   candidate expects 2 arguments, 5 provided
C:\Program Files (x86)\Arduino\libraries\WiFi\src/WiFi.h:100:10: note: candidate: void WiFiClass::config(IPAddress, IPAddress, IPAddress)
     void config(IPAddress local_ip, IPAddress dns_server, IPAddress gateway);
          ^
C:\Program Files (x86)\Arduino\libraries\WiFi\src/WiFi.h:100:10: note:   candidate expects 3 arguments, 5 provided
C:\Program Files (x86)\Arduino\libraries\WiFi\src/WiFi.h:109:10: note: candidate: void WiFiClass::config(IPAddress, IPAddress, IPAddress, IPAddress)
     void config(IPAddress local_ip, IPAddress dns_server, IPAddress gateway, IPAddress subnet);
          ^
C:\Program Files (x86)\Arduino\libraries\WiFi\src/WiFi.h:109:10: note:   candidate expects 4 arguments, 5 provided
C:\Users\Максим\Documents\Arduino\GyverPanelWiFi_v1.09\GyverPanelWiFi_v1.09.ino: In function 'void startSoftAP()':
GyverPanelWiFi_v1.09:403:8: error: 'class WiFiClass' has no member named 'softAPdisconnect'
GyverPanelWiFi_v1.09:409:23: error: 'class WiFiClass' has no member named 'softAP'
GyverPanelWiFi_v1.09:425:27: error: 'class WiFiClass' has no member named 'softAPIP'
GyverPanelWiFi_v1.09:429:10: error: 'class WiFiClass' has no member named 'enableAP'
GyverPanelWiFi_v1.09:430:10: error: 'class WiFiClass' has no member named 'softAPdisconnect'
GyverPanelWiFi_v1.09:434:25: error: 'class WiFiClass' has no member named 'softAP'
C:\Users\Максим\Documents\Arduino\GyverPanelWiFi_v1.09\GyverPanelWiFi_v1.09.ino: In function 'void connectToNetwork()':
GyverPanelWiFi_v1.09:448:10: error: 'class WiFiClass' has no member named 'mode'
GyverPanelWiFi_v1.09:448:15: error: 'WIFI_AP' was not declared in this scope
C:\Users\Максим\Documents\Arduino\GyverPanelWiFi_v1.09\a_main.ino: In function 'void parsing()':
a_main:1950:22: error: 'class WiFiClass' has no member named 'softAPdisconnect'
exit status 1
no matching function for call to 'WiFiClass::disconnect(bool)'

**Comment by vvip-68** [comment]
Возможно это из за наличия у вас кириллицы в пути к библиотекам - те черные квадратики со знаками вопроса.
Смените пользователя Windows на не-кириллического.
