### ISSUE TITLE
GyverPanelWifi

### ISSUE THREAD

**Issue by Ady-67** [vvip-68/GyverPanelWiFi#116]
Hi,please give me more instructions regarding the alarm sounds.
I can't make them work, I followed all the installation instructions, everything works perfectly.

**Comment by vvip-68** [comment]
Could you ask more specific question? "Help me regarding the alarm sounds" is extrimely common question.

**Comment by Ady-67** [comment]
So,the alarm sounds are not played by dfplayer.

lun., 1 feb. 2021, 15:36 vvip-68 <notifications@github.com> a scris:

**Comment by vvip-68** [comment]
What did you do for alarm sounds being played by dfplayer?
Did you put alarms sound on SD card into proper folder?
Did yoг select sound file in application in Alarm Settings page?

**Comment by vvip-68** [comment]
Did you connect MP3 DFPlayer board properly to main controller?
Does port monitor logs contains message that MP3 Player is properly initialized and found sound files on SD-card?
Does speaker properly connected to DFPlayer board?
Can you hear sound on speaker when short connect IO1/IO2 pin on DFPlayer board with GND pin?

**Comment by Ady-67** [comment]
Yes, I put on the sd card the three files 01.02.03
I downloaded the application but at the application when I set the
alarm the part with the sound activation disappears and I don't know
why?


lun., 1 feb. 2021, 15:49 vvip-68 <notifications@github.com> a scris:

**Comment by Ady-67** [comment]
I connected everything according to the scheme, indeed on the Serial
monitor it does not show me the initialization of the player with 9600 baud.

If you briefly connect the IO1 / IO2 pins with gnd, run the mp3 files
on the sdcard.


lun., 1 feb. 2021, 15:54 vvip-68 <notifications@github.com> a scris:

**Comment by vvip-68** [comment]
> If you briefly connect the IO1 / IO2 pins with gnd, run the mp3 files on the sdcard.

So, DFPlayer is functional

>indeed on the Serial monitor it does not show me the initialization of the player with 9600 baud.

What do you see on Serial monitor at all? Connection speed is set to 115200
Do you see anything in monitor?

> alarm the part with the sound activation disappears and I don't know why?

this part is not visible if sketch has turned off definition USE_MP3 - set to 0

**Comment by Ady-67** [comment]
1.Do I have to put the sound files separately or all three in one (sound)?

2. The serial monitor at 115200 shows less and less information about
initializing dfplayer
3. I chose variant 5 from the sketch with 16x16 matrix, mp3 set 1 and
weather set 1


lun., 1 feb. 2021, 16:33 vvip-68 <notifications@github.com> a scris:

**Comment by vvip-68** [comment]
1. Files on SD card MUST be copied into SD-card root as is in three separate folders 01, 02 and 03
2. Give me content of port monitor log immediately after microcontroller is restarted.
3. Variants 1-5 are variant (hardware profile) for MY OWN devices. You MUST specify parameters for YOUR device, which is higly likely differs from MY device.

**Comment by Ady-67** [comment]
Image 1 and 2 is Serial monitor without DFPlayer connected and image 3 is
with DFPlayer connected.

În lun., 1 feb. 2021 la 17:01, vvip-68 <notifications@github.com> a scris:

**Comment by vvip-68** [comment]
There are no images in post.
It is better to copy all ccontent of log as plain text.

**Comment by Ady-67** [comment]
lun., 1 feb. 2021, 17:34 vvip-68 <notifications@github.com> a scris:

**Comment by Ady-67** [comment]
Would you receive the pictures?

**Comment by vvip-68** [comment]
No. No pictures, no plain text logs. Nothing. No any valuable information.
You own see that above - nothing.

**Comment by Ady-67** [comment]
I took the pictures with the phone and they are 6MB and he doesn't want to
send them by email.

I try to make them smaller.


lun., 1 feb. 2021, 18:12 vvip-68 <notifications@github.com> a scris:

**Comment by Ady-67** [comment]
WiFiPanel-v.1.09.2021.0118
18:28:34.552 -> Host: 'WiFiPanel-5' >> 16x16
18:28:34.552 ->
18:28:34.552 -> Загрузка строк выполнена.
18:28:34.552 -> Использованы адреса EEPROM 800 - 837
18:28:34.552 -> Свободно ячеек 3258
18:28:36.803 ->
18:28:36.803 -> Инициализация файловой системы...
18:28:36.803 -> FS: Использовано 16384 из 1024000 байт
18:28:36.803 ->
18:28:36.803 -> Инициализация MP3 плеера.
18:28:42.990 -> Звуков будильника найдено: 0
18:28:42.990 -> Звуков рассвета найдено: 0
18:28:42.990 -> Звуков сообщений найдено: 0
18:28:42.990 -> MP3 плеер недоступен.
18:28:43.177 ->
18:28:43.177 -> Подключение к HD86SAG -> 192.168.0.100
18:28:43.271 -> .............
18:28:47.302 -> WiFi подключен. IP адрес: 192.168.0.100
18:28:47.302 ->
18:28:47.302 -> UDP-сервер на порту 2390
18:28:47.302 -> Режим: The Matrix
18:28:47.302 -> NTP-сервер ru.pool.ntp.org -> 193.192.36.3
18:28:47.302 -> Отправка NTP пакета на сервер ru.pool.ntp.org
18:28:47.302 ->
18:28:47.302 -> Запрос текущей погоды
18:28:47.490 -> Погода получена: OpenWeatherMap
18:28:47.490 -> Город: Simeria
18:28:47.490 -> Сейчас: пасмурно, +3ºC
18:28:47.490 -> Код иконки: '04n'
18:28:47.490 -> Код погоды: 804
18:28:47.490 -> Сейчас: Темное время суток
18:28:47.490 -> Рассвет: 07:49
18:28:47.490 -> Закат: 17:33
18:28:47.490 ->
18:28:47.490 -> UDP << ip='193.192.36.3:123'; ntp sync
18:28:47.537 -> UDP пакeт размером 48
18:28:47.537 -> Разбор пакета NTP
18:28:47.537 -> Секунд с 1970: 1612204126
18:28:47.537 -> Текущее время: 01.02.2021 18:28:46
18:28:47.537 -> --------------------

În lun., 1 feb. 2021 la 18:12, vvip-68 <notifications@github.com> a scris:

**Comment by Ady-67** [comment]
If I connect dfplayer, nothing starts and in the Serial monitor only the
time and a series of signs appear.

În lun., 1 feb. 2021 la 18:12, vvip-68 <notifications@github.com> a scris:

**Comment by Ady-67** [comment]
18:37:46.841 -> WiFiPanel-v.1.09.2021.0118
18:37:46.841 -> Host: 'WiFiPanel-5' >> 16x16
18:37:46.841 ->
18:37:46.841 -> Загрузка строк выполнена.
18:37:46.841 -> Использованы адреса EEPROM 800 - 837
18:37:46.888 -> Свободно ячеек 3258
18:37:49.125 ->
18:37:49.125 -> Инициализация файловой системы...
18:37:49.125 -> FS: Использовано 16384 из 1024000 байт
18:37:49.125 ->
18:37:49.125 -> Инициализация MP3 плеера.
18:37:55.326 -> Звуков будильника найдено: 0
18:37:55.326 -> Звуков рассвета найдено: 0
18:37:55.326 -> Звуков сообщений найдено: 0
18:37:55.326 -> MP3 плеер недоступен.
18:37:55.513 ->
18:37:55.513 -> Подключение к HD86SAG -> 192.168.0.100
18:37:55.560 -> ..............
18:37:59.872 -> WiFi подключен. IP адрес: 192.168.0.100
18:37:59.872 ->
18:37:59.872 -> UDP-сервер на порту 2390
18:37:59.872 -> Режим: Светлячки
18:37:59.872 -> NTP-сервер ru.pool.ntp.org -> 80.249.145.122
18:37:59.872 -> Отправка NTP пакета на сервер ru.pool.ntp.org
18:37:59.872 ->
18:37:59.872 -> Запрос текущей погоды
18:38:00.341 -> Погода получена: OpenWeatherMap
18:38:00.341 -> Город: Simeria
18:38:00.341 -> Сейчас: пасмурно, +3ºC
18:38:00.341 -> Код иконки: '04n'
18:38:00.341 -> Код погоды: 804
18:38:00.341 -> Сейчас: Темное время суток
18:38:00.341 -> Рассвет: 07:49
18:38:00.341 -> Закат: 17:33
18:38:00.341 ->
18:38:04.888 -> Таймаут NTP запроса!
18:38:29.878 -> Режим: Радужные переливы
18:38:59.873 -> Режим: Часы
18:38:59.873 -> NTP-сервер ru.pool.ntp.org -> 80.249.145.122
18:38:59.873 -> Отправка NTP пакета на сервер ru.pool.ntp.org
18:38:59.920 -> UDP << ip='80.249.145.122:123'; ntp sync
18:38:59.967 -> UDP пакeт размером 48
18:38:59.967 -> Разбор пакета NTP
18:38:59.967 -> Секунд с 1970: 1612204738
18:38:59.967 -> Текущее время: 01.02.2021 18:38:58
18:38:59.967 -> --------------------
18:39:29.885 -> Режим: Шумящий лес
18:39:59.857 -> Режим: Циклон
18:40:29.882 -> Режим: Погода
18:40:59.896 -> Режим: Вышиванка
18:41:29.922 -> Режим: Лабиринт
18:42:08.431 -> Режим: Светлячки
18:42:38.450 -> Режим: Лампа

În lun., 1 feb. 2021 la 18:12, vvip-68 <notifications@github.com> a scris:

**Comment by vvip-68** [comment]
> 18:28:36.803 -> Инициализация MP3 плеера.
18:28:42.990 -> Звуков будильника найдено: 0
18:28:42.990 -> Звуков рассвета найдено: 0
18:28:42.990 -> Звуков сообщений найдено: 0
18:28:42.990 -> MP3 плеер недоступен.

This means that DFPlayer has no detect SD-card and did not found any sound files.
By this reason application settings has no section related with settings of sounds

As I remember - this log is for case when DFPlayer is not connected.

> If I connect dfplayer, nothing starts and in the Serial monitor only the
time and a series of signs appear.

It means that you connect DFPlayer with not propper way, some of pins of microcontroller has inappropriate levels on its start, that lead to unable to start MCU in normal mode.

Could you provide pointer to scheme that you have used for your device and real photo of connections between MCU and DFPlayer?

**Comment by Ady-67** [comment]
I made this variant.I followed the scheme exactly.


În lun., 1 feb. 2021 la 19:01, vvip-68 <notifications@github.com> a scris:

**Comment by Ady-67** [comment]
When I connect the TX pin from DFPlayer to pin D4 from ESP it locks.


În lun., 1 feb. 2021 la 19:01, vvip-68 <notifications@github.com> a scris:

**Comment by Ady-67** [comment]
![18-53-26-scheme](https://user-images.githubusercontent.com/78360223/106496514-a258de00-64c5-11eb-8104-8b742f9962cd.jpg)

**Comment by vvip-68** [comment]
So, you still didn`t provide photo of your device and connections. How I can help you under this conditions?

**Comment by Ady-67** [comment]
This is.

**Comment by Ady-67** [comment]
![IMG_20210201_194926](https://user-images.githubusercontent.com/78360223/106497421-b2bd8880-64c6-11eb-9c26-bed3b3c33225.jpg)
![Uploading IMG_20210201_194842.jp
![Uploading IMG_20210201_194811.jpg…]()
g…]()

**Comment by Ady-67** [comment]
![Uploading IMG_20210201_194842.jpg…]()

**Comment by Ady-67** [comment]
![Uploading IMG_20210201_194811.jpg…]()

**Comment by Ady-67** [comment]
![Uploading IMG_20210201_194811.jpg…]()

**Comment by Ady-67** [comment]
![Uploading IMG_20210201_194811.jpg…]()

**Comment by Ady-67** [comment]
![Uploading IMG_20210201_194842.jpg…]()

**Comment by Ady-67** [comment]
I uploaded the pictures 25 minutes ago and they still haven't uploaded.
What city are you from in Russia?

**Comment by vvip-68** [comment]
Does it matter? github servers are located somewere in USA, I think...

**Comment by Ady-67** [comment]
No, that's not why I asked. I hope you weren't upset.

**Comment by vvip-68** [comment]
It will not help to solve issue

**Comment by Ady-67** [comment]
Ok.

lun., 1 feb. 2021, 20:39 vvip-68 <notifications@github.com> a scris:

**Comment by Ady-67** [comment]
Talk to you soon and keep up the good content.

**Comment by Ady-67** [comment]
![Uploading IMG_20210202_065239.jpg…]()

**Comment by Ady-67** [comment]
![Uploading IMG_20210202_065057.jpg…]()

**Comment by Ady-67** [comment]
![Uploading IMG_20210202_065035.jpg…]()

**Comment by vvip-68** [comment]
Do you have smth like google drive account?
You may upload files onto your drive and put links here.

**Comment by Ady-67** [comment]
Okay, later because I'm at work now.


mar., 2 feb. 2021, 07:31 vvip-68 <notifications@github.com> a scris:

**Comment by Ady-67** [comment]
https://drive.google.com/file/d/1pqOLJokTF6UkS5ubiWW5Q0S9YOtJqfzT/view?usp=drivesdk

**Comment by Ady-67** [comment]
https://drive.google.com/file/d/1prWqBMa2l_LH6yaPMU8go28YGXBjxZGR/view?usp=drivesdk

**Comment by Ady-67** [comment]
https://drive.google.com/file/d/1qFuUm9Zb5B0ZMIDUzVEgCDrh5-6znlOA/view?usp=drivesdk

**Comment by vvip-68** [comment]
No access. Content is blocked. For all 3 images

**Comment by Ady-67** [comment]
how to unlock them


mar., 2 feb. 2021, 12:23 vvip-68 <notifications@github.com> a scris:

**Comment by Ady-67** [comment]
try now


mar., 2 feb. 2021, 12:23 vvip-68 <notifications@github.com> a scris:

**Comment by vvip-68** [comment]
I didn`t see any suspicious on connections...
A you sure thar resistors on Rx/TX lines are 1k?
Show me file structure on SD-card...
Could you try another card?
I haму no ideas anymore...

**Comment by vvip-68** [comment]
Do you have another DFPlayer board for try it?
I assembled about 4-5 devices with sound features. It works
However I had 2-3 DFPlayer board, which I couldn`t make it working.
By unknown reason.

**Comment by vvip-68** [comment]
Try temporary excange wires D3<->D4 on MCU...

**Comment by Ady-67** [comment]
I guess the Nodemcu board, in the winter I made AlexGyver's garland with
the sdcard module and Jinx effects and out of three Nodemcu modules, only
one initializes the sd card.

mar., 2 feb. 2021, 13:06 vvip-68 <notifications@github.com> a scris:

**Comment by Ady-67** [comment]
https://drive.google.com/file/d/1qTE9tZVzdKxTGvpb4LPdCF_tZ4pprGUU/view?usp=drivesdk

**Comment by Ady-67** [comment]
I managed to solve the problem.
1.DFPlayer defective
2.DFPlayer must be powered at 3.3 V otherwise it will not initialize.

**Comment by Ady-67** [comment]
Thank you for your cooperation.

**Comment by vvip-68** [comment]
Thank you for information. DFPlayer datasheet http://files.amperka.ru/datasheets/DFPlayer_Mini.pdf
specify operation voltage as 3.3V-5V. Probably your power supply unit output gives more than 5V.
Usually chines pover supply units give output 5.4-5.6 Volts
It is highly recommended for ESP8255 MCU use pover supply as 4.8V, otherwise is bad intercommunication between LEDs and MCU - inappropriate logical levels lead to digital artefacts on LED matrix

Where did you get 3.3V? As I understand DFPlayer has built-in 3W amplifier. It means on power supply 3.3 V requite circuit in about 1A. As I understand 3.3V pin of NodeMCU is able to provide not more that 300-500 mA of currency.
Did you add special power supply voltage converter to 3.3V specially for DFPlayer?

**Comment by vvip-68** [comment]
Also in case of VCC (Input Power) level 5.4-5.6V from power supply unit output it is possible provide power supply for MCU and DFPlayer through cremnium diode as it shown on following picture:
![image](https://user-images.githubusercontent.com/39353139/106692777-b573c700-6607-11eb-8d2e-617aaec2c8b3.png)

**Comment by Ady-67** [comment]
I took 3.3 V from the Nodemcu module and it works perfectly.

I will do more tests and I will measure the supply voltage and I will
tell you the results.


mie., 3 feb. 2021, 05:01 vvip-68 <notifications@github.com> a scris:

**Comment by Ady-67** [comment]
I noticed that it does not play sounds clearly.
Could it be because of the Nodemcu module because it has limited current?


mie., 3 feb. 2021, 05:08 vvip-68 <notifications@github.com> a scris:

**Comment by Ady-67** [comment]
I will measure and if the voltage is higher than 5V I will use a diode.

mie., 3 feb. 2021, 05:08 vvip-68 <notifications@github.com> a scris:

**Comment by vvip-68** [comment]
> I noticed that it does not play sounds clearly.
Could it be because of the Nodemcu module because it has limited current?

May be several reasons for unclear sound
1. Bad speaker with work power less then output power of amplifier (speaker overload)
2. Low / limited / not enough  current from 3.3v output pin
3. Position/location of speaker relative underlaying surface

High current from 3.3v pin may lead to overheat of onboard stabilizer and make it broken / malfunctional.

**Comment by Ady-67** [comment]
OK thanks


mie., 3 feb. 2021, 09:10 vvip-68 <notifications@github.com> a scris:

**Comment by Ady-67** [comment]
did all kinds of tests and came to the next conclusion.
1. I reduced the voltage from 5.4V to 4.8 V with a UF 5402 / 3A diode
2. I powered DFPlayer at 4.8V and it does not initialize
3. If I supply DFPlayer with 4.8V after NodeMcu starts then it is initialized
I noticed a problem, the diode heats up while the assembly is working, is it normal?

**Comment by vvip-68** [comment]
Not, heating diod is not normal. Probably you made incorrect scheme and your LED matrix GND line connected after diode, instead of direct connection to power supply unit GND. Check it.

**Comment by Ady-67** [comment]
I'll make all the connections again.
Thanks for the advice.


joi, 4 feb. 2021, 05:05 vvip-68 <notifications@github.com> a scris:

**Comment by Ady-67** [comment]
A question and a proposal at the same time.
Would it be difficult to modify the code so that each effect corresponds to a song?
I saw such a lamp also favored by a Russian boy of course with your effects and how to run an effect run and a song, he has them for sale for 3700 rubles but does not make the code public.

**Comment by vvip-68** [comment]
No, I do not want to do that. You may do it yoself. It is not so hard but completely not interesting for me.  In addition to sketch you probably will need rework smartphone application for make link between sound and effect.

In other word that is easy to set PlaySound(x) on effect change making sound hardcoded, but if you want make flexible settings for tune relations between sound and effect - it is enough a lot of coding, and I do not want spend time for that.

**Comment by Ady-67** [comment]
I understand. I have not reached such a level that I know how to make such
a change.

Thank you for your honesty.


joi, 4 feb. 2021, 17:05 vvip-68 <notifications@github.com> a scris:

**Comment by Ady-67** [comment]
Another problem, I wanted to change the classic button with a touch button but when I connect the button the brightness is automatically reduced if I give an impulse it increases to 99 after which it returns to 0.
What's wrong now?

**Comment by vvip-68** [comment]
Did you changed definition for button type in a_soft_def.h, lines 526, 527?
``` 
// GButton butt(PIN_BTN, LOW_PULL, NORM_OPEN); // For touch button
GButton butt(PIN_BTN, HIGH_PULL, NORM_OPEN);   // For usual button
```

**Comment by Ady-67** [comment]
Thank you very nice.
If you ever come to Romania, I'll let you know to honor you with a drink.


joi, 4 feb. 2021, 20:06 vvip-68 <notifications@github.com> a scris:

**Comment by vvip-68** [comment]
Deal!
