### ISSUE TITLE
Эффекты сбрасываются на "часы"

### ISSUE THREAD

**Issue by vladimirt1994** [vvip-68/GyverPanelWiFi#118]
При выборе любого эффекта кроме "часы" в приложении  "WiFi Panel", они начинают быстро меняться друг за другом и в конце устанавливается эффект часы. Использую версию GyverPanelWiFi_v1.10. Несколько раз прошивал на версию WiFi-Panel-ESP8266-v1.0.9, на этой версии такого не наблюдается. Как исправить? Может я что то накосячил, хотя сверял 2 версии прошивки, все переменные которые указывал одинаковые. Матрица 18х11

**Comment by vvip-68** [comment]
У маня такого эффекта не наблюдается. Пришлите что в это время выводится в логе.
