### ISSUE TITLE
Проблема с LittleFS ESP32

### ISSUE THREAD

**Issue by sepulka123** [vvip-68/GyverPanelWiFi#121]
Добрый день.
Повторил Ваш замечательный проект на ESP32.
Панель 23 х 22  и модуль SD. Ни часов ни плеера ни управления по питанию.
Работает нормально (за исключением нескольких вопросов, но это потом), но при запуске "ESP32 LittleFS Data Upload"
получаю сообщение: LITTLEFS Error: mklittlefs not found! 
Что может быть не так ?

**Comment by vvip-68** [comment]
Гуглить надо почему такая ошибка возникает?
Плагин устанавливали из папки tools/LittleFS_Uploader проекта, архив ESP32LittleFS.zip?

**Comment by sepulka123** [comment]
Разархивировал ESP32LittleFS.zip , получил
c:\Program Files (x86)\Arduino\tools\ESP32LittleFS\*.*
Перезагрузил Arduino IDE.
В папке c:\Users\Wladimir-i3\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.5\tools\*.*
Нет файла:    mklittlefs.exe.
  - Создал подпапку data.
        3. В созданной папке data создайте подпапку с именем, соответствующим размерам вашей матрицы. 
   Например для матрицы 16x16 создайте папку "16p16"
А где искать эту папку 
4. В созданную папку 16р16 скопируйте файлы картинок

**Comment by sepulka123** [comment]
(Прошу прощения что то "вздрыгнуло" и сообщение ушло недоделанным это продолжение)

Создал подпапку data.
 В созданной папке data создал папку 23p22 скопировал в нее картинку .gif
e:\ESP32\GyverPanelWiFi\GyverPanelWiFi-master\firmware\GyverPanelWiFi_v1.10\data\23p22\03a.gif

**Comment by sepulka123** [comment]
Может где то в скетче нужно указывать, что используется Система
LittleFS для ESP32 ?

**Comment by vvip-68** [comment]
Нет, не нужно. И при чем тут скетч, если у вас из Arduino IDE выгрузка не проходит?
Примеры картинок - в проекте в папке pics/ Но там только для 16x16 картинки.

А ESP8266 ядро у вас установлено? Может там этот файл есть?
У меня пишет - 
mklittlefs : C:\Users\user\AppData\Local\Arduino15\packages\esp8266\tools\mklittlefs\2.5.0-4-fe5bb56\mklittlefs.exe

Попробуйте поставьте такой же плагин для ESP8266

**Comment by vvip-68** [comment]
> Создал подпапку data.
В созданной папке data создал папку 23p22 скопировал в нее картинку .gif
e:\ESP32\GyverPanelWiFi\GyverPanelWiFi-master\firmware\GyverPanelWiFi_v1.10\data\23p22\03a.gif

А при чем тут вообще gif?
Вы теплое с мягким не путайте.
В данном случае - это картинки, сохраненные с матрицы программой WiFiPlayer, которая позволяет их рисовать "пальцем" через смартфон в этом приложении. Там в приложении можно сохранить нарисованную картинку в файловую систему или загрузить ранее нарисованную-сохраненную. Сам файл (содержимое) представляет собой три байта заголовка (размер матрицы) и далее последовательно сохраненные "триплеты" цвета RGB (3 байта) для каждого диода матрицы.

**Comment by sepulka123** [comment]
У меня на матрице рисовать можно а сохранять не знаю как.
Не нашёл я такого в приложении.

**Comment by vvip-68** [comment]
![image](https://user-images.githubusercontent.com/39353139/109308850-260fab80-7875-11eb-9a6e-0617732879bc.png)

**Comment by sepulka123** [comment]
У меня это так выглядит.
![S10226-170336](https://user-images.githubusercontent.com/55927434/109318023-061cbf80-7856-11eb-8865-de2079a8f879.png)

**Comment by sepulka123** [comment]
Прошу прощения, загружается !
Просто пробовал при выключенной панели. 
А поскольку в приложении на "экране" ничего не менялось, то подумал, что не загружается.

**Comment by sepulka123** [comment]
Да, но на "экран" приложения все равно ничего не выводится.

**Comment by vvip-68** [comment]
Выбор картинки из списка и нажатие кнопки "Открыть" ТОЛЬКО загружает файл из сохраненного файла на матрицу.
Чтобы получить изображение с матрицы в приложение - его нужно оттуда передать на телефон. Это круглая кнопка со стрелкой вниз - самая левая в ряду кнопок.

**Comment by sepulka123** [comment]
Добрый день.
Хотел отправить Вам небольшую денежку, но что то не получается.
Спрашивает Ваш адрес. Что туда записать ?
Мой адрес :  sepulka123@gmail.com  
Туда можно отправить Ваш адрес и, может еще, что нужно для оплаты по "ПейПел".

**Comment by vvip-68** [comment]
Спасибо за поддержку. Кнопка "Sponsor" вверху странички имеет две ссылки - на отправку доната через PayPal - там нужно только ввести сумму и нажать кнопку "Отправить" - больше ничего не требуется (проверено), никаких адресов.
Вторая ссылка - реквизиты карточки в платежной системе VISA. Не уверен можно ли переводить на карту из за рубежа (не из РФ), но по РФ - точно можно через банк-онлайн, например.

**Comment by vvip-68** [comment]
@sepulka123 
Спасибо за поддержку, Владимир.
