### ISSUE TITLE
ошибка в wifi panel

### ISSUE THREAD

**Issue by RailWar** [vvip-68/GyverPanelWiFi#125]
В wifi panel 1.10 при нажатии на любую кнопку для строк с 1 до  Z ошибка `Start(1) + length(1)-1 exceeds text length(0)`

**Comment by vvip-68** [comment]
Ошибка не наблюдается. Приложите скриншот программы с ошибкой. И последовательность что делаете, чтобы получить ошибку. Версия программы соответствует версии прошивки?

**Comment by RailWar** [comment]
![Screenshot_2021-03-24-12-20-49-74_6f4bf5aa62f7621cde178c8627d7d779](https://user-images.githubusercontent.com/31412580/112285697-a5897280-8c9b-11eb-93d2-22187d16b06f.jpg)
соединяюсь с лампой, захожу в закладку "бегущая строка", нажимаю на любую кнопку кроме "0" - выскакивает ошибка
Версия программы внизу (скриншот). а где увидеть версию прошивки?. собирал и ставил apk в одно время

**Comment by vvip-68** [comment]
Последняя версия приложения - 1.10.2021.0225
Возможно там эта ошибка пправлена. Попробуйте ее.
Если нет - будем изучать дальше.

**Comment by RailWar** [comment]
обновил. работает. спасибо
