### ISSUE TITLE
pcb

### ISSUE THREAD

**Issue by RailWar** [vvip-68/GyverPanelWiFi#127]
для себя разработал плату для esp-12f в sprint layout если кому-то кроме меня интересно могу поделиться - вставите в проект. выглядит так
![image](https://user-images.githubusercontent.com/31412580/112300097-8c87be00-8ca9-11eb-863e-67f32aaf28ef.png)
готовую уже не сфотогрофировать - запаял и засунул в коробку. разведено все - micro sd, dfplayer, дисплей, тач,  мосфет, порт для usb-uart

**Comment by vvip-68** [comment]
Плата - это здорово. Я в этом ничего не понимаю, но если пришлёте всё что нужно - я добавлю это в проект.

**Comment by RailWar** [comment]
[lamp8266.zip](https://github.com/vvip-68/GyverPanelWiFi/files/6196693/lamp8266.zip)

**Comment by vvip-68** [comment]
Вот спасибо за печатку!
Чтобы не ошибиться - это же для
#define DEVICE_VARIANT 1
?

Дам для варианта 0 и 1 кажется немного отличается распиновка - что к каким пинам подключается.
Этот вариант для тач-кнопки или можно обычную использовать и где-то что-то перемычкой переключается?

**Comment by vvip-68** [comment]
Может быть было бы совсем хорошо - если есть какой-то текстик - иснструкция по сборке для "чайников"...

**Comment by vvip-68** [comment]
Особенно с инструкцией "как прошивать" по проводам. Для этого же нужен внешний конвертоh USB-TTL? насколько я понимаю или через Arduino (Nano)?

**Comment by RailWar** [comment]
#define DEVICE_VARIANT 1 - да
можно и обычную кнопку. там контакт "+" не используется. 
чайники с таким связываться не захотят (наверное). я утюгом делал плату, где покупал на али, где выпаивал из доноров детальки. но напишу-опишу чуть позже.
а прошивать точно так же. просто надо иметь com-uart. напр. на той же cp2102. появится ком-порт

**Comment by vvip-68** [comment]
У меня ЧПУ-шка есть. Надо будет попробовать выгравировать плату, как время свободное на это появится...

**Comment by RailWar** [comment]
специально делал односторонюю чтобы утюгом . только две перемычки бросить надо

**Comment by RailWar** [comment]
вывел туда еще adc. может когда пригодится

**Comment by RailWar** [comment]
[pcb.docx](https://github.com/vvip-68/GyverPanelWiFi/files/6203823/pcb.docx)

**Comment by vvip-68** [comment]
Вот спасибо! Добавил в проект.
