### ISSUE TITLE
Папка 48х16 пуста

### ISSUE THREAD

**Issue by simonovich** [vvip-68/GyverPanelWiFi#129]
Зачем-то пустая папка:
https://github.com/vvip-68/GyverPanelWiFi/tree/master/tools/Jinx/48x16
А лучше бы полная! ))

**Comment by vvip-68** [comment]
Все эти *.out - файлы занимают слишком много места.
1. Гит отказывается их загружать
2. Архив проекта и так уже велик - будет вообще к гигабайту, если все такие файлы хранить
3. Файлы довольно специфичные - зависят от угла подключения матрицы
Файлы для размеров матрицы 50x20 есть в соответствующей папке. Из них легко делаются файлы 48x16 - практически для всех эффектов без ущерба. Из 90% этих файлов делаются даже 16x16
Там же в архиве есть исходники Jinx-эффектов (включая гифки) из которых легко можно наделать собственных эффектов под любые размеры матриц.
