### ISSUE TITLE
wifi pass lenght

### ISSUE THREAD

**Issue by aseldom** [vvip-68/GyverPanelWiFi#13]
Возможн ли увеличить максимальную длину пароля для вафай? Хотя бы до 20 символов?

**Comment by vvip-68** [comment]
Можно. Файл eeprom.ino - строка 60 - карта распределения памяти EPROM - для пароля выделены ячейки 104-119,
процедура чтения / сохранения пароля -  getPass().toCharArray(pass, 17)  и setPass(String(pass))
Согласно карте памяти - ячейки 242-299 не используются. Перенесите хранение пароля туда.
Исправьте в строках 831-839 начальную ячейку чтения/сохранения данных и их длину.
Исправьте также в строке 184 длину читаемых данных. 
В файле a_main.ino - строка 628 и файле a_def_soft.h строка 257 - длина,
При текущей длине пароля 16 символов нужен дополнительный - на оконечный '\0' - поэтому длина массива 17.
