### ISSUE TITLE
tm1637 и точки

### ISSUE THREAD

**Issue by simonovich** [vvip-68/GyverPanelWiFi#133]
Подключил индикатор tm1367. Работает. Но почему-то вместо двоеточия между часами и минутами наблюдаю 4 мигающих десятичных точки, по одной на каждом сегменте, внизу.
Так и задумано?

**Comment by simonovich** [comment]
Описание проблемы и вариант решения:
https://youtu.be/m1CtIJsRoyM?t=220

**Comment by vvip-68** [comment]
Вы купили не тот вариант дисплея - "калькуляторный". Для проекта нужен дисплей - "часовой". В нём вместо десятичных точек - разделительное двоеточие между часами и минутами.
