### ISSUE TITLE
Добавить эффект "Георгиевская ленточка"

### ISSUE THREAD

**Issue by AndreyLyamkin** [vvip-68/GyverPanelWiFi#136]
Привет!
А можете добавить эффект, который будет рисовать на панели георгиевскую ленточку?
Скоро праздник Победы. Я думаю очень популярен будет данный эффект

**Comment by vvip-68** [comment]
Да, могу добавить. Давайте код эффекта, вставлю.

**Comment by AndreyLyamkin** [comment]
> Да, могу добавить. Давайте код эффекта, вставлю.

Так если бы был этот код эффекта. Где его можно сделать? В каком формате нужен? 
Я надеялся, что может кто-то из подписчиков уже подобное делал

**Comment by vvip-68** [comment]
Сделать можно в Arduino IDE в формате кода языка Си.
