### ISSUE TITLE
Не могу переключиться на большие часы. Матрица 8х32.

### ISSUE THREAD

**Issue by didos06** [vvip-68/GyverPanelWiFi#137]
Всë работает, а часы на большие ни как не переключаются. В a_def_soft.h  byte CLOCK_SIZE = 2 поставил, ничего не меняется, все равно 3х5 рисуются. Это моë первое устройство, пока ещë маловато понимаю. Куда копать?

**Comment by vvip-68** [comment]
Чё-т я даже не тестировал для такого типа матриц.
Я исправил - заберите обновления с хранилища. Исправленный файл - clock.ino
