### ISSUE TITLE
Подключение к сети 

### ISSUE THREAD

**Issue by ledskl** [vvip-68/GyverPanelWiFi#138]
Доброго дня Вам. Подскажите пожалуйста можно ли сбросить подключение к сети на дефолтное PanelAP без приложения и без перепрошивки. В приложение попасть не могу.

**Comment by vvip-68** [comment]
Когда устройство не может  подключиться к прописанной сети - оно создаёт точку доступа.
Попробуйте сразу-сразу после перезагрузки устройства, пока оно не успело подключиться к сети, нажать на кнопку.
Пор=пытка подключения будет прервана и устройство создаст точку доступа.
Или просто - выключите роутер к которому устройство было подключено, перезагрузите устройство.
Оно будет пытаться подключиться к несуществующей сети и через таймаут 5 минут (или после нажатия кнопки во время этих попыток) - создаст точку доступа.
