### ISSUE TITLE
Error while compiling - missing a_def_devc.h

### ISSUE THREAD

**Issue by TimoUrban** [vvip-68/GyverPanelWiFi#142]
Hi!

I get the following error during compilation in Arduino IDE: 

```
compilation terminated.
exit status 1
a_def_devc.h: No such file or directory
```

I found this file in file "private.zip" but it is password protected. 
Can you please help me? 

Thank you very much.

**Comment by vvip-68** [comment]
You not need this file.
Edit line 37 of file a_def_hard.h as:
 
#define A_DEF_DEVC  0
 
  
>Среда, 7 июля 2021, 23:42 +07:00 от Timo ***@***.***>:
> 
> 
>Hi!
>I get the following error during compilation in Arduino IDE:
>compilation terminated.
>exit status 1
>a_def_devc.h: No such file or directory
>
>I found this file in file "private.zip" but it is password protected.
>Can you please help me?
>Thank you very much.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением,
Вадим Пузанов
