### ISSUE TITLE
GyverPanelWiFi

### ISSUE THREAD

**Issue by Verholaz** [vvip-68/GyverPanelWiFi#143]
Сделал 2 лампы с вашей прошивкой. Всё работает. Огромное спасибо Вам за проделанную работу. Но есть 1 вопрос по последней прошивке. В папке sounds - 04 в readme есть строчка: "Звуки отбивки каждого часа, если включен часовой сигнал в часах (женский голос Оксана)." Вопрос: "Это где?" В приложении нет. Смотрел во вкладках прошивки - тоже не нашёл. Спасибо за ответ. P.S. Приложение из архива с этой прошивкой.

**Comment by vvip-68** [comment]
Этого нигде нет. Это нереализованный задел на будущее...

Среда, 11 августа 2021, 22:21 +07:00 от Verholaz ***@***.***>:
>Сделал 2 лампы с вашей прошивкой. Всё работает. Огромное спасибо Вам за проделанную работу. Но есть 1 вопрос по последней прошивке. В папке sounds - 04 в readme есть строчка: "Звуки отбивки каждого часа, если включен часовой сигнал в часах (женский голос Оксана)." Вопрос: "Это где?" В приложении нет. Смотрел во вкладках прошивки - тоже не нашёл. Спасибо за ответ. P.S. Приложение из архива с этой прошивкой.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .

С уважением,
Вадим Пузанов

**Comment by Verholaz** [comment]
Добрый вечер. Спасибо за ответ. Сделал ещё один проект ( матрице ) с вашей прошивкой GyverPanelWiFi v1.10. Выложил на форуме  Bluetooth матрица под этим ником. Вам желаю успешных проектов и удачи.
