### ISSUE TITLE
Jinx Framer Viewer

### ISSUE THREAD

**Issue by dorinik** [vvip-68/GyverPanelWiFi#144]
Greetings vvip-68 and thanks for your hard work!
Please post the Jinx Frame Viewer application in English.
Thanks and good luck!

**Comment by vvip-68** [comment]
I updated JinxFramer tool. Get it and try. Right down corner of application window contains the ComboBox for select application interface language. Next, you must restart application for selected language is being applied.

**Comment by dorinik** [comment]
many thanks !

În mar., 17 aug. 2021 la 18:09, vvip-68 ***@***.***> a scris:

**Comment by gmarkitantov** [comment]
как взять приложение

**Comment by vvip-68** [comment]
кликнуть мышкой
