### ISSUE TITLE
Ошибка компиляции версии 1.12

### ISSUE THREAD

**Issue by Mosrom** [vvip-68/GyverPanelWiFi#148]
При компиляции с платой ESP32 Dev Module возникает ошибка  "USE_E131 was not declared in this scope".

**Comment by Mosrom** [comment]
После добавления строки эта ошибка исчезла. Спасибо.

**Comment by Mosrom** [comment]
На ESP32-S3 Ваш скетч будет работать?

**Comment by vvip-68** [comment]
@Mosrom, будет. А что мешает попробовать?
