### ISSUE TITLE
Матрица 25*12 - не помещается один столбик больших часов 

### ISSUE THREAD

**Issue by fastdron** [vvip-68/GyverPanelWiFi#15]
Доброго времени суток , прошу помощи Вашей в правке больших часов ,не влазит один столбик , можно например мигающие точки отредактировать чтоб они были по ширине в один пиксель? И если это возможно - ткните носом где это в коде ибо я от программирования совсем далёкий) . Заранее спасибо! Ваша реализация этого проекта -круче всех!!!

**Comment by vvip-68** [comment]
файл clock.ino процедура DrawClock() - строки 284-291 - убрать отрисовку колонки x+13
Далее в строках 295 и 291 сместить позицию на одну влево

**Comment by fastdron** [comment]
Спасибо ,побежал пробовать👍

**Comment by vvip-68** [comment]
Там, похоже, еще проверки на ширину матрицы нужно править 26 на 25 - например в clock.ino строка 197, custom.ino 179
