### ISSUE TITLE
Wifi

### ISSUE THREAD

**Issue by kost111233** [vvip-68/GyverPanelWiFi#150]
Извините еще раз за беспокойство. Вы сказали что в скетче есть пункт, который включает точку доступа платы и сама плата в это время подключается к домашней сети. Если не затруднит, подскажите как эта строка называется в коде.

**Comment by vvip-68** [comment]
Я такого не говорил.
Я говорил, что в приложении на смартфоне есть чекбокс, включив который точка доступа будет создаваться вместе  с подключением к домашней сети. Переменная, связанная с этим чекбоксом в скетче называется `useSoftAP`
