### ISSUE TITLE
Не загружает время и погоду

### ISSUE THREAD

**Issue by ri5074** [vvip-68/GyverPanelWiFi#152]
Добрый день
Столкнулся с проблемой: при подключении к роутеру Netis N1 матрица не хочет загружать с интернета данные о времени и погоде. При этом матрица зависает практически полностью - пока идет запрос погоды ничего на экране не меняется, потом один раз что-то сменится и снова секунд 10-30 ничего не происходит. С роутерами TP-Link все работает отлично, но хотелось бы разобраться что в моем роутере блокирует работу сети. Никаких специфических настроек на нем не делал.
Лог:
Подключение к Coffee66_2.4 -> 192.168.10.150
.............
WiFi подключен. IP адрес: 192.168.10.150

UDP-сервер на порту 2390
Режим: Радуга
Не удалось получить IP aдрес сервера NTP -> ua.pool.ntp.org -> 255.255.255.255
Используем сервер по умолчанию: 91.207.136.50
NTP-сервер ua.pool.ntp.org -> 91.207.136.50
Отправка NTP пакета на сервер ua.pool.ntp.org

Запрос текущей погоды
Таймаут NTP запроса!
Таймаут запроса погоды!

Запрос текущей погоды

**Comment by vvip-68** [comment]
Зависание матрицы и всё описанное - оттого, что микроконтроллер не может получить доступ в интернет - в логе написано, что "таймаут запроса". Как только вы настроите свой роутер - проблема уйдет. Про настройку роутера - читайте специализированные форумы по вашему роутеру, обратитесь в support фирмы-производителя, поищите статьи в интернете.

Или отключите в настройках прошивки через приложение получение времени и погоды с интернета - проблема с зависаниями уйдет.
