### ISSUE TITLE
Настройка е131

### ISSUE THREAD

**Issue by Vasap62** [vvip-68/GyverPanelWiFi#154]
Подскажите как настроить синхронизацию контроллеров. Желательно для чайников))) Никак не могу настроить. Заранее спасибо!

**Comment by vvip-68** [comment]
Я вряд ли смогу что-то подробнее рассказать, чем это в wiki расписано.
Если есть конкретные вопросы - готов выслушать.

**Comment by Vasap62** [comment]
Я имею ввиду конкретно на WiFi панели. Вы там добавили функцию синхронизации эффектов, а я не могу Че-то настроить её

**Comment by vvip-68** [comment]
Вики читали? Что сделали для настройки?

**Comment by Vasap62** [comment]
Вики пока не читал. Выставил с настройках в приложении один контроллер ведущим, другой ведомым. Один контроллер сделал точкой доступа (ведущий), другой попытался к нему подключить введя ssid и пароль ведущего контроллера, ничего не вышло((( или они должны быть подключены к одной общей сети где точкой доступа выступает роутер например? Я не очень разбираюсь в программировании наверное что-то делаю не так

**Comment by vvip-68** [comment]
Давайте, вы сначала почитаете вики, что-то попробуете, потом будете задавать конкретные вопросы?
Синхронизация работает только при подключении к локальной сети. В режиме точки доступа - эта технология не работает.

**Comment by Vasap62** [comment]
Понял, спасибо большое!
