### ISSUE TITLE
Здравствуйте, нужна помощь с подключением к роутеру

### ISSUE THREAD

**Issue by ferakond** [vvip-68/GyverPanelWiFi#156]
Контроллер подключается к роутеру, но с приложения не получается подключится

**Comment by vvip-68** [comment]
Настройте свой телефон (или роутер) так, чтобы пакеты, отправляемые с телефона доходили через роутер до устройства. Найдите и установите на телефон утилиту проверки связи типа Ping, Когда эта утилита будет получать ответы от контроллера - программа управления сможет подключиться к контроллеру.

Некоторые телефоны требуют отключения передачи "Мобильные данные", иначе они отправляют пакеты опроса контроллера не роутеру в локальной сети, а куда-то в интернет по каналу мобильной связи. Отключение этого канала (или корректная настройка в параметрах телефона) позволяет запросам приложения к контроллеру уходить в локальную сеть роутера и передаваться контроллеру, вместо отправки "в никуда".

**Comment by ferakond** [comment]
Спасибо, попробую
