### ISSUE TITLE
Как настроить скорость всех эффектов в прошивке?

### ISSUE THREAD

**Issue by timof123** [vvip-68/GyverPanelWiFi#157]
Не могу найти информацию, как настроить скорость эффектов прямо в прошивке. Скорость по умолчанию (60) очень медленная.
В файле a_def_soft.h в строке 646 нашел переменную D_EFFECT_SPEED. Но при ее изменении ничего не происходит. 

Как все-таки настроить эту скорость по умолчанию?

**Comment by vvip-68** [comment]
Это какая-то рудиментарная констаната....
Вообще же - при ПЕРВОЙ прошивке чистого контроллера или при смене константы EEPROM_OK в строке 7 файла a_def_soft.h - происходит инициализация настроек эффектов значениями по умолчанию. В частности - скорость эффекта по умолчанию задается в файле eeprom.ino в строке 304. 

Если запуск / прошивка не первая - при неизменном значении EEPROM_OK - эти константы "по умолчанию" вообще не используются - все настройки извлекаются из сохраненных в EEPROM.

Но вы правы, нужно будет эту константу D_EFFECT_SPEED в этой строке 304 использовать. Позже исправлю.
