### ISSUE TITLE
Управление кнопкой 

### ISSUE THREAD

**Issue by fastdron** [vvip-68/GyverPanelWiFi#16]
Подскажите почему не работает индикатор тм1637
Собрана матрица 25*12 в скетче выбран          
  Device id ==4 и настроены все пункты, раскоментил #define Dio D5 и # define CLK D7  подключил модуль к соответствующим пинам ,перепрошил D1 mini (правда без очистки памяти) и все равно часы не выводятся и на кнопку принажатии 4 или 5 раз не выводится ip адрес. Что я не так делаю? Или при использовании панели в качестве гирлянды нет возможности подключать индикатор часов и выводить ip?

**Comment by vvip-68** [comment]
есть, но честно говоря, особо не проверялось.
и TM1637 точно не может работать с SD картой - они используют одни и те же пины SPI

**Comment by fastdron** [comment]
Прошу прощения, мой косяк - не поставил 1 в def-hard для активации модуля. С этим понятно, а вот как вывести ip адрес по нажатии кнопки на панель?

**Comment by vvip-68** [comment]
"На панель" - на матрицу или на TM1637?
Впрочем - у меня это работает по четырехкратному / пятикратном нажатию кнопки в зависимости от выбранного при компиляции DEVIC_TYPE. По крайней мере так задумывалось. Что, отвалилось? Сейчас посмотрю...

**Comment by fastdron** [comment]
при выбраном типе девайса 4(гирлянда на балкон) не выводится ip на саму матрицу(гирлянду) ,так же пробовал подключить ТМ1637 -время не завилось(может я не донастроил в скетче где-то-пока только разбираюсь))) мигают просто точки а вместо цифр просто полоски (на тм1637) , и ip тоже не выводится на 1637 при нажати 4или 5 раз на кнопку

**Comment by vvip-68** [comment]
Так, с выводом IP - поправил, выложил.
С точками и тире - а время то с сервера получилось?
Такое поведение - признак того, что прошивка не смогла получить текущее время с сервера NTP

**Comment by fastdron** [comment]
Спасибо огромное, сейчас обновлю и проверю. Вы уж простите что я тут засоряю коменты))) ,сам я только начинаю разбираться с ардуино и электроникой, и на Git научился писать буквально вчера)))))))) Хотел уточнить у Вас - как правильно и проще всего обновить прошивку и добавить Ваши исправления? нужно заново прошивать и настраивать весь скетч , или копировать отдельно измененные файлы и вставлять в скетч? зарание прошу прощения за глупые вопросы) ,просто меня этому никто еще не научил))

**Comment by vvip-68** [comment]
Я таки настоятельно рекомендую поставить и настроить SmatrGit. Он показывает что в каких файлах изменилось и позволяет забирать изменения отдельных файлов, не требуя перенастройки ваших исправлений.
Ну или то же самое вручную - на гите смотреть что в каких файлах изменилось при этом коммите и брать только измененные файлы или только измененные строки. Но SmartGit удобнее

**Comment by fastdron** [comment]
"Ну или то же самое вручную - на гите смотреть что в каких файлах изменилось при этом коммите и брать только измененные файлы или только измененные строки. "
только что просто строки измененные перезалил в скетч вручную- муторно немного))))
НО ТЕПЕРЬ ВЫВОД IP на матрицу работает по 4кратному нажатию кнопки! Суппер! сейчас заново подкину TM 1637 и посмотрю что с ними) спасибо огромное. также SmartGit начну изучать по Вашему совпету.

**Comment by fastdron** [comment]
а нельзя как нибудь сделать чтобы отображение ip на матрице пррокручивалось всего один раз и возвращался ранее выбраный эффект или демо режим?

**Comment by vvip-68** [comment]
Можно. Разобраться и переписать код.

**Comment by fastdron** [comment]
Понял,ну я это точно не осилю,пока что))))))) Спасибо . отпишусь еще по поводу tm1637 ,как раз сейчас подключаю

**Comment by vvip-68** [comment]
Часы то на матрице отображаютс?

**Comment by fastdron** [comment]
"Раз уж у вас девайс (кнопка) под рукой и вы (один раз в год может быть) нажмете 4 раза, чтобы посмотреть IP - что вам мешает после этого нажать кнопку 3 раза, чтобы вернуться в демо-режим?" Полностью согласен! это был просто уточняющий вопрос

**Comment by fastdron** [comment]
"Часы то на матрице отображаются?"
на матрице отображаются большие часы(пришлось указать размер матрицы на 1 столбик шире (26 вместо 25 иначе были только малые часы) , еще не пробовал правки по часам по Вашему совету, сейчас разберусь с тм1637 и после полезу править часы на матрице)))

**Comment by fastdron** [comment]
по поводу подключения TM1637 - как только прошиваю d1mini с активированым в dev_hard модулем ТМ1637- устройство перестает конектится к моей локалке и в монитор порта выкидывает ip адрес подключения к моему роутеру 2,2,2,2 ...

**Comment by fastdron** [comment]
LED-Panel-WiFi v.1.05.2020.1012

Загрузка строк выполнена.
Ипользованы адреса EEPROM 800 - 962
Свободно ячеек 3133

Подключение к ASUS
.......
WiFi подключен. IP адрес: 2.2.2.2

UDP-сервер на порту 2390
NTP-сервер ua.pool.ntp.org -> 255.255.255.255
Отправка NTP пакета на сервер ua.pool.ntp.org
Таймаут NTP запроса!
NTP-сервер ua.pool.ntp.org -> 255.255.255.255
Отправка NTP пакета на сервер ua.pool.ntp.org
Таймаут NTP запроса!
NTP-сервер ua.pool.ntp.org -> 255.255.255.255
Отправка NTP пакета на сервер ua.pool.ntp.org
Таймаут NTP запроса!
NTP-сервер ua.pool.ntp.org -> 255.255.255.255
Отправка NTP пакета на сервер ua.pool.ntp.org
Таймаут NTP запроса!

**Comment by fastdron** [comment]
и на самих тм1637 соответственно полоски-время не подтянулось - матрица глючит ужасно,на кнопку почти не реагирует, эфекты тормозят.... что это может быть?

**Comment by vvip-68** [comment]
Не знаю. Только что собрал проект с включенным USE_TM1637 - никаких проблем нет.
Сам индикатор, правда, не подцеплен - неохото было с проводами возиться паять...

**Comment by fastdron** [comment]
Отключение в def_hard не решает прорблему ,только сброс eeprom помог

**Comment by fastdron** [comment]
сейчас проверю без индикатора

**Comment by fastdron** [comment]
ОООО, интересненько))) без физически подключенного индикатора но с #define USE_TM1637 1 все ок,не виснет ничего

**Comment by fastdron** [comment]
прбую другой индикатор

**Comment by vvip-68** [comment]
Мне кажется физическое подключение к пинам никак не должно влиять на прошивку...
Что, ж, видимо мне придется доставать паяльник...

**Comment by fastdron** [comment]
а не может быть проблемы из за несогласования уровней? я индикатор питаю от 5 в от бп, скорее всего в этом проблема)))) вот я тупень)))

**Comment by vvip-68** [comment]
Думаю, что нет

**Comment by fastdron** [comment]
именно в этом был трабл))) перекинул питание на 3.3 в - все работает ,не виснет,подключается!!! но часы на индикаторе какие-то битые, сейчас парочку других подкину ,посмотрю

**Comment by fastdron** [comment]
а как вывести ip на тм1637 напеомните -это 5кратное нажатие кнопки? если так- то не работает

**Comment by fastdron** [comment]
с другим индикатором часы работают ! Класс_ВЫ ЛУЧШИЙ!!!)))

**Comment by vvip-68** [comment]
> а как вывести ip на тм1637 напеомните -это 5кратное нажатие кнопки? если так- то не работает
Так же как на матрицу - вывод на индикатор и на матрицу должен идти параллельно.
На индикатор - попеременно цифры тетрад

**Comment by fastdron** [comment]
на индикатор не идет вывод ip паралельно с матрицей. на матрице все ок. В скетче есть гдето флаги откл этого? я мог уже рание чтото откл и забыть)))

**Comment by fastdron** [comment]
Обновил еще раз прошивку, проверил все параметры, залил - и О чудо!!))))) есть вывод! спасибо огромное

**Comment by vvip-68** [comment]
Спаял, проверил - все работает.
https://drive.google.com/file/d/1ImupDAcpdq9ada9xP8HB-hewNHmkvUNG/view?usp=sharing

**Comment by fastdron** [comment]
доступ закрыт на диске. Но в любом случае уже работает и у меня! это очень удобно будет смотреть ip - матрица то у меня на улицу будет повернута) а часы выведу на корпусе устройства и там смтогу смотреть ip в случае необходимости! Спасибо огромное вам за помощь!!!!!!!!! тут все... есть вопросы по выводу текста по наступлению события и по спец режимах, если у вас будет минутка -поможете разобраться?

**Comment by vvip-68** [comment]
Да открыл уже доступ. Кнопку вовремя не нажал...
Помогу

**Comment by fastdron** [comment]
в отдельную тему вопросы по событиям писать или тут?

**Comment by fastdron** [comment]
это у вас матрица 16 на 16 на видео?

**Comment by vvip-68** [comment]
из трех 16х16 Это мой тестовый стенд
Если длиннопост (ак этот) - лучше вообще  в личку сюда https://vk.com/iivanovii

**Comment by fastdron** [comment]
а телеграмм нету у вас? @Fastdron

**Comment by vvip-68** [comment]
Нет
