### ISSUE TITLE
подключение

### ISSUE THREAD

**Issue by Simafor47** [vvip-68/GyverPanelWiFi#160]
Вечер добрый.Подскажите,не нашел в схемах нужную мне,а именно для платы 8266 с дисплеем,мр3,sd-шилдом кнопкой и реле.
Нашел только для wemos и esp32. ткните носом где искать и куда подключать всё это добро))

И заодно хотелось бы узнать как программировать бегущую строку,желательно с примерами.Вики читал,строку записать смог,но вместе со скобками и тд))и как задать периодичность например(чтоб через определенное время,как эффекты демо крутятся и текст бежал)

**Comment by vvip-68** [comment]
Все имеющиеся схемы - в [вики](https://github.com/vvip-68/GyverPanelWiFi/wiki/Варианты-устройств.-Схемы.). Других схем у меня нет, но всё что нужно легко получается путем комбинации частей из имеющихся. Или, например, "вычитанием" ненужных частей из полной схемы "С полным набором компонент (отключение матрицы - MOSFET)".

Все подключения описываются в настройках скетча в файле a_def_hard.h в строках, начиная с 72 (или с 145 для схемы с полным набором компонент).

Про программирование бегущей строки - более подробно чем написано в [вики](https://github.com/vvip-68/GyverPanelWiFi/wiki/Настройка-бегущей-строки) я все равно рассказать не смогу. Примеры строк (те, что загружаются в прошивку по умолчанию) - в файле eeprom.ino в строке, начиная с 487. 

В самом приложении на телефоне на закладке настройки текста есть синяя кнопка с вопросиком - нажав на нее вы откроете правила написания текста в бегущей строки и описание всех доступных макросов. Изучайте. 

Ниже кнопки с вопросиком - область кнопок, позволяющая автоматически добавить в строку шаблоны для наиболее часто используемых макросов.

На этой же страничке настройки текстов бегущей строки в самом верху есть поле "Интервал", позволяющее указать как часто выводить бегущую строку поверх эффектов.
