### ISSUE TITLE
Лагает эффект "Узоры"

### ISSUE THREAD

**Issue by timof123** [vvip-68/GyverPanelWiFi#162]
Используется NodeMCU. Размер гирлянды 10*15 светодиодов. Эффект "Узоры" подвисает. Правда, если в приложении настроить, чтобы узор двигался только в одном направлении - тогда все отлично. Но вот при движении в разные стороны лагает очень(((. 
Что-то можно с этим сделать?

**Comment by vvip-68** [comment]
Я подправил алгоритм этого эффекта. Заберите свежую версию. Может быть так будет лучше.
