### ISSUE TITLE
Глюк с невозвратом в нормальный деморежим после запуска игр через приложение GyverPlayerWiFi

### ISSUE THREAD

**Issue by frol-aleksan** [vvip-68/GyverPanelWiFi#164]
Решение: в файле a_main.ino добавить блок
          if (tmp_eff == MC_MAZE || tmp_eff  == MC_SNAKE || tmp_eff  == MC_TETRIS || tmp_eff  == MC_ARKANOID) {
            // При вызове игр принудительно включаем деморежим и переинициализируем эффект
            loadingFlag = true;
            gameDemo = true;
            setEffect(tmp_eff);
          } else
после
// Если в приложении выбраны эффект "Ночные часы" / "Дневные часы", но они недоступны из-за размеров матрицы - выключить матрицу
          // Если в приложении выбраны часы, но они недоступны из-за размеров матрицы - брать другой случайный эффект
          if (tmp_eff == MC_CLOCK){
            if (!(allowHorizontal || allowVertical)) {
              setRandomMode2();
            } else {
              setSpecialMode(10);    // Дневные часы. Для ночных - 8
            }
          } else 

Также добавить блок 
if (newMode == MC_MAZE || newMode == MC_SNAKE || newMode == MC_TETRIS || newMode == MC_ARKANOID) {
    // При вызове игр принудительно включаем деморежим
    gameDemo = true;
  }
в функциях nextModeHandler() и void prevModeHandler() в custom.ino перед строкой
set_thisMode(newMode);

**Comment by vvip-68** [comment]
Я исправл.
