### ISSUE TITLE
не подключается к WiFi

### ISSUE THREAD

**Issue by playeeerua** [vvip-68/GyverPanelWiFi#165]
Это снова я :D
Вроде прошилось, спасибо за терпение, теперь с вай-фай. Его почему-то нет. В устройствах его нет (смотрел через 192.168.1.1) Пытался зайти через 192.168.4.1 глухо :( Как точка доступа он тоже не появился. Вот что выдает монитор порта
![image](https://user-images.githubusercontent.com/66793382/144128967-d6690a41-0218-4b75-8413-8f42a26434d1.png)

**Comment by playeeerua** [comment]
Ну хоть не стоим на месте, маленькими шажками продвигаемся))

**Comment by vvip-68** [comment]
Тема закрыт - проблем решена?
В логе пишет, что подключилась к локалке, адрес контроллера - 192.168.1.123
Вот этот адрес и нужно использовать в программе для подключения к контроллеру.
Естественно адрес должен быть в той же подсетке, которой управляет роутер.
Например если контроллер подключился с адресом 192.168.**1**.123, а роутер управляет сеткой 192.168.**0**.xx - программа на телефоне не сможет подключиться к контроллеру.

Судя по вашему нику - вы с Украины. Ваше правительство заблокировало российские сервисы типа Яндекс - а именно оттуда контроллер получает погоду. Вы не сможете получать погоду с Яндекса. Именно для таких случаев имеется второй источник погоды - OpenWeatherMap - он включается в приложении на телефоне.

**Comment by playeeerua** [comment]
по дефолту стояло 0.90, я поменял на 1.123, потому что роутер управляет сеткой 1.1 в подключенных устройствах в роутере он не появляется. Я смотрел 123 никем не занято в роутере было
В программе на телефоне я вписывал его айпи, но не подключается. 
Та мне бы сначала сделать так, что-бы заработало все, а потом с погодой заморачиваться, но нам эта функция вообще не нужна, ее можна убрать

**Comment by vvip-68** [comment]
Сначала тогда добейтесь, чтобы телефон вообще видел контроллер в сети.
Поставьте приложение [Ping](https://play.google.com/store/apps/details?id=ua.com.streamsoft.pingtools) или подобное и добейтесь, чтобы пакеты с телефона до контроллера проходили.

После того как пинг будет проходить - сделайте скриншот монитора порта что происходит в момент попытки подключения телефона к контроллеру.

**Comment by ferrrum** [comment]
Роутер RT-GM-2
Подключается через ровно через раз. И не только ваша прошивка. 
Делал отдельный скетч для WiFi. Всё равно с первого раза не хочет подключатся.

При раздаче WiFi с телефона 100% подключение.

Проблему решил программным ресетом. 
if (!wifi_connected && !stop_waiting){ESP.restart();}
После перезагрузки всегда подключается.
Но тут если не будет знакомой WiFi сети. Будет постоянная перезагрузка.

Помогите с записью в eeprom подсчёта количества перезагрузок.

**Comment by vvip-68** [comment]
@ferrum - а может роутер поменять на нормальный?
А что не я сно с записью в EEPROM? Там вест файл eeprom.ino - сплошные записи и чтения

**Comment by ferrrum** [comment]
Попробуй раздай интернет с телефона. Может проблема как у меня в роутере.

**Comment by playeeerua** [comment]
завтра найду телефон на андроиде, отпишу или получилось решить проблему

**Comment by playeeerua** [comment]
При попітке подключения телефона, вот что відает монитор порта (Не подключает)
![image](https://user-images.githubusercontent.com/66793382/144484520-eb0bbcd6-d2e4-4aa9-9808-41902df92305.png)

**Comment by vvip-68** [comment]
А если отключить запрос погоды - может он мешает подключению?
Поставьте где-нибудь в setup() после LoadSettings()
set_useWeather(0);

**Comment by playeeerua** [comment]
Не совсем понимаю куда вставить. А там нет как например с мп3 use_mp3=1 не 0 поменять и отключаю?)

**Comment by playeeerua** [comment]
![image](https://user-images.githubusercontent.com/66793382/144486596-7a34dfc8-f27f-4d27-95c5-467ec43320f8.png)
Оно?)

**Comment by Witska** [comment]
Оно

**Comment by vvip-68** [comment]
Вот. Ничего никуда не добавляйте, а здесь поставьте 0

**Comment by playeeerua** [comment]
Ееееесть, подключило и не пропадает. Проблема номер 9999. Теперь с матрицей.

**Comment by playeeerua** [comment]
На стол не смотрите, это подвал :D
Перепроверили спайку, вроде ок все, нигде не перепутано
![11B37D21-F6C1-46A5-A7DA-2C874966FE59](https://user-images.githubusercontent.com/66793382/144487543-57f39607-f8ee-46c8-982a-cf898f739cb7.jpeg)

**Comment by playeeerua** [comment]
Я хочу проверить и поставить другую матрицу что-бы понять в ней ли дело. Нашел схему 16х16, вижу что зеленую надо в дин паять, а те 3 провода , подсоеденитьне трогать и просто еще один в дин допаять?
![Uploading image.jpg…]()

**Comment by playeeerua** [comment]
![Uploading 9F837F46-4AE2-4A43-9546-C31BC8D95F7A.jpeg…]()

**Comment by playeeerua** [comment]
![F194C77A-8BDC-4ED8-BBDE-E63F80ED475F](https://user-images.githubusercontent.com/66793382/144488432-ec46ad5c-6c25-4478-a162-67b7d53a4b53.jpeg)

**Comment by vvip-68** [comment]
Зеленый слева - DIN - к выходу управляющего сигнала с контроллера. Белый - к минусу питания контроллера (и блока питания). Красный - к плюсу питания

**Comment by vvip-68** [comment]
А куда вообще все это подключено? На фото выше виден угол микроконтроллера, и пин на который идет сигнал - D2 никуда не подключен.

**Comment by playeeerua** [comment]
У меня ж их 3 теперь :D
К 3-му подключен (с резистором 220 Ом походу, уже не помню)

**Comment by vvip-68** [comment]
И питание бы вам к КАЖДОМУ куску ленты параллельно подводить. А то тоненькие проводнички ленты и тоненькие проводочки между кусками ленты - не додут нормально работать. Конец ленты будет еле светиться из за падения напряжения.

**Comment by playeeerua** [comment]
А можно как-то полностью проверить или светит вся лента?

**Comment by playeeerua** [comment]
что ж, буду паять. Скоро увидимся :D

**Comment by vvip-68** [comment]
> А можно как-то полностью проверить или светит вся лента?

Залейте тестовый скетч. который поочередно зажигает каждый светодиод ленты. Где-то в примерах FastLed были подобные простенькие скетчи.

**Comment by simonovich** [comment]
А я не могу прописать устройство в свою wifi сеть, т.к. мобильное приложение не предоставляет вкладки для настройки подключения.
См. https://disk.yandex.ru/i/_B1taETPtS-lXw

**Comment by vvip-68** [comment]
Потому что никто не любит читать инструкции, зато любят мучиться. Прям мазохисты какие-то.
Для настройки матрицы (в т.ч. настройки подключения к сети) рядом лежит приложения PanelSetup

**Comment by simonovich** [comment]
Во первых, я читал инструкцию:
https://github.com/vvip-68/GyverPanelWiFi/wiki/%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D0%BE%D0%B2-%D0%B2-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B8
Во-вторых, у меня свежая версия софта, в том числе все 3 apk установлены.
И прочеканы.
Когда захожу в panel setup, то вижу только panel setup. А зачем оно мне? Тем более, если настройки матрицы подгружены в отдельном файле с профилем устройства.

**Comment by vvip-68** [comment]
Скриншот этого приложения настройки можно?
На розовую кнопку с ключиком вверху экрана в синей полоске нажимать пробовали?

**Comment by simonovich** [comment]
Новости с полей.
Нашёл кнопку подключения в Panel Setup, я реально её просмотрел. Вписал сеть и свободный ip. Созранить - перезагрузка.
После этого приложенька Wifi Panel зашла по новому адресу. А вот Panel Setup по новому адресу не заходит. По старому, понятное дело, тоже.

В мониторе порта 
```
Подключение к MyWiFi -> 192.168.5.9
.............
```

Примерно через полчаса этот лог вешает Arduino IDE и я его убиваю.

В общем, это уже что-то другое. Я буду с этим работать, если совсем плохо станет - напишу.
Спасибо.

**Comment by vvip-68** [comment]
Там у каждого приложения - своя настройка адреса к какому IP подключаться. Там исправлено на новый адрес?

**Comment by simonovich** [comment]
Исправлено.
