### ISSUE TITLE
Зависает плата Esp32 на определенных эффектах

### ISSUE THREAD

**Issue by promo148** [vvip-68/GyverPanelWiFi#167]
Плата зависает (в монитор порта ничего не выводит, от WiFi отваливается) на эффектах Змейка и Арканоид

Эффект Палитра вызывает ребут платы. В мониторе порта:
![3](https://user-images.githubusercontent.com/60114036/144303369-da7d96ac-4c8c-4fa5-b79f-0bd669a3451e.png)

Пробовал на нескольких платах Esp32 (разное количество пинов), разное питание (от usb-компа, powerbank, от БП для питания ленты на 4,85 вольта).
Может есть какие идеи почему так происходит?
Или подскажите как вырезать данные эффекты. 

Версия ядра ESP32 - 1.0.6
Версия FastLED - 3.4.0
WiFiPanel v.1.12.2021.1127

![1](https://user-images.githubusercontent.com/60114036/144302579-8598d17d-b5e2-4c83-9f69-06d151f574cd.png)
![2](https://user-images.githubusercontent.com/60114036/144302595-e5e7a7de-37da-4690-90ce-d0a7748d53b6.png)

**Comment by vvip-68** [comment]
Нет, не сталкивался с таким. Все указанные режимы у меня стабильно работают....
Вырезать - просто удалить их из кода и все ссылки, что на них завязаны. 
Но проще в приложении поставить галочки на этих эффектах - "Не использовать".

Если галочки поставить не удается - можно в скетче где-нибудь в setup() после вызова LoadSettings() написать
putEffectUsage(MC_PALETTE, false);
putEffectUsage(MC_SNAKE, false);
putEffectUsage(MC_ARKANOID, false);

**Comment by kost111233** [comment]
Попробуйте библиотеку FastLED не 3.4.0

**Comment by vvip-68** [comment]
А каким MQTT брокером пользуетесь?
Я вот смотрю по скриншотам - если дефолтным mqtt.by у вас топик MQTT совершенно неправильно настроен. Это, кстати, тоже может вызывать проблемы и отвалы.

**Comment by promo148** [comment]
> Попробуйте библиотеку FastLED не 3.4.0

Попробую вечером все версии

**Comment by promo148** [comment]
> А каким MQTT брокером пользуетесь? Я вот смотрю по скриншотам - если дефолтным mqtt.by у вас топик MQTT совершенно неправильно настроен. Это, кстати, тоже может вызывать проблемы и отвалы.

Упс. А что не так?
Я настроил не для mqtt.by, я локально у себя на сервере с Home Assistant, поднял стандартный Mosquito mqtt. Соответственно взял интеграцию под HA 
https://github.com/tarasifua/vvip-68-matrix-home-assistant-integration

**Comment by vvip-68** [comment]
Ну для не mqtt.by - наверное нормально 
На mqtt.by 16 ноября они поменяли формат топика.
У меня пока нет времени исправить в инструкции, но, в принципе в личном кабинете там все написано.
