### ISSUE TITLE
Иконки погоды

### ISSUE THREAD

**Issue by ferakond** [vvip-68/GyverPanelWiFi#170]
Здравствуйте, а как можно настроить отображение иконок погоды ? Или это от региона погоды как то зависит? Погоду показывает через макросы и на часах

**Comment by vvip-68** [comment]
Иконки погоды лежат в файле weather.h
Формат тот же, что у анимации - RGB565, левый верхний угол картинки слева вверху массива.

В файле weather.ino - процедура получения номера картинки в массиве по коду погоды, полученному от погодного сервера. getWeatherFrame() - для Яндекса, getWeatherFrame2() - для OpenWeatherMap

**Comment by ferakond** [comment]
А есть какой-то подробный мануал? Мне кажется я что-то пропустил)

**Comment by vvip-68** [comment]
Специального мануала по замене картинок погоды нет. Это уже такие программистские дебри, что мало кому интересно. Как выбирается картинка из массива картинок погоды - описано выше. Как создаются картинки в коде в формате RGB565 - в принципе можно почитать статью wiki, посвященную утилите [JinxFramer](https://github.com/vvip-68/GyverPanelWiFi/wiki/JinxFramer---редактор-анимации,-роликов,-картинок#Экспорт-кадра-в-код-скетча) в разделе "Экспорт кадра в код скетча", нарисовать картинки, экспортировать их и заменить в weather.h картинки своими. 

Картинки погоды - не анимация, просто картинка. Более-менее приличная анимация -
а) требует достаточно много памяти контролера (там же много кадров нужно на одну картинку)
б) а кто ее рисовать будет? - я не художник.

Если вы художник и нарисуете красивые картинки - поделитесь, будет красиво у всех.

**Comment by ferakond** [comment]
Я прошу прощения, я наверное не так вопрос сформулировал) Я имел ввиду на роликах где использовали вашу прошивку в строке погоды после текста на матрице отрисована иконка погоды)
А на счёт картинок я попробую)

**Comment by vvip-68** [comment]
А это точно моя прошивка? Может кто переделывал? У меня такой возможности нету.
Ролик этот посмотреть можно?

**Comment by ferakond** [comment]
https://youtu.be/1qtvohFDlQc на восьмой минуте
Там правда просто иконка погоды и температура

Может м вправду в другой прошивке видел

**Comment by vvip-68** [comment]
Ну вот та иконка что на восьмой минуте - это оно и есть, всё о чем описано выше.

**Comment by ferakond** [comment]
А подскажите пожалуйста как этот эффект включить.
То что во вкладке  погода просто по очереди показывает иконки погоды

**Comment by vvip-68** [comment]
Очевидно что у вас не получены сведения о погоде с погодного сервера и ему просто нечего показывать. Аот он по очереди все и показывает. Почему нет сведений о погоде? Ну, это вас спрашивать нужно.
- Или эта возможность выключена в настройках прошивки - стоит USE_WEATHER 0
- Или выключено получение в настройках (в программе) - тип погодного сервера "Ничего"
- Или нет соединения с интернетом (или сервер заблокирован, например как Яндекс в Укараине)
- Или еще что-то...

Как только контроллер получит сведения о погоде - он на этом эффекте будет показывать текущую погоду, а не перебирать картинки по циклу...

**Comment by ferakond** [comment]
Ну на счёт не настроен я писал, что в бегущей строке если макросом то показывает и на часах температуру 
В программе выставлено все. Ладно буду в этой области ковырять) Спасибо за помощь и за мотивацию на развитие))

**Comment by vvip-68** [comment]
Ну по другому не бывает. Есть погода - показывает ее. Нет погоды - "крутит" иконки по циклу.
Я говорю об оригинальной прошивке. Если кто-то что-то там переписывал - тогда я не знаю.
