### ISSUE TITLE
подключение к mqtt.by из apk

### ISSUE THREAD

**Issue by limittouch** [vvip-68/GyverPanelWiFi#172]
гирлянда смотрит в мир через роутер и успешно подключается к брокеру mqtt.by без проброса портов
```
17:58:23.420 -> Подключаемся к MQTT-серверу 'mqtt.by:1883'; ClientID -> 'WiFiPanel-be12' ...
17:58:23.607 -> Подключение к MQTT-серверу выполнено.
```
приложение GyverPanelWiFi.apk с теми же настройками по MQTT-каналу не подключается

заменить в инструкции подключения к mqtt.by формат префикса на 
user/<аккаунт>/<уникальный идентификатор>

4 часа убил, пока issues/167 не прочитал :)

**Comment by vvip-68** [comment]
Ну нет у меня пока времени поправить инструкцию... 
Это только 16 ноября у них поменялось...
Поправлю. Потом.

**Comment by vvip-68** [comment]
А то - сделайте доброе дело, обновите текст инструкции, картинок наделайте. 
Пришлите мне md-файл и картинки - я в вики заменю :)

**Comment by limittouch** [comment]
скриншотов больно много, а у меня все иначе настроено, не потяну

зато есть рац-предложение:
ничего не менять, а добавить красным в начале главы **MQTT-сервер по-умолчанию** :

**ВНИМАНИЕ! В связи с изменением у брокера mqtt.by формата префикса, в приведенных ниже примерах везде вместо строки "af7cd12a" требуется использовать "user/<имя пользователя>/af7cd12a". Так же требуется задать имя пользователя и пароль.
Подробности настройки подключения см. на странице брокера "Профиль"** 

дешево и сердито
плюс, понятно, что у разных брокеров разный формат префикса может быть

**Comment by vvip-68** [comment]
Спасибо за предложение, строку добавлю.
А как в md-файлах делать текст красным?

**Comment by 247760** [comment]
@vvip-68 
<h2>

```diff
- red
+ green
! orange
# gray
```

</h2>

**Comment by vvip-68** [comment]
Спасибо. Костыли, конечно, но...

**Comment by simonovich** [comment]
Там мальчики  играются со своим серваком (mqtt.by). Рабочий вход по паролю иногда доступен только на порту 1885. А он с недавнего времени платный! :)
А на бесплатном тестовом 1883, то жесткие требования по паролю / топику, то наоборот пускает по-любому и всех подряд... Также какие-то странные подвисания в ночное время.
Пробуйте.
