### ISSUE TITLE
SD

### ISSUE THREAD

**Issue by kost111233** [vvip-68/GyverPanelWiFi#177]
Добрый день, подскажите. Решил в схему добавить sd карту. Прошить не удается, сначала были одинаковые библиотеки в разных местах, в итоге все удалил, заново установил библиотеку sd и вот такую ошибку выдает
![50FA0909-7244-4224-A52D-B7FA93786886](https://user-images.githubusercontent.com/54816270/145019144-6b21628f-2be3-4e13-a645-dc0d06632acf.jpeg)

**Comment by vvip-68** [comment]
Вообще удалите эту библиотеку. Она для ардуино (AVR)б а не для ESP.
У ESP поддержка SD карты на уровне ядра

**Comment by kost111233** [comment]
![image](https://user-images.githubusercontent.com/54816270/145019894-f12d1037-8845-4f69-8250-06035890fcaf.jpg)
Удалил, теперь ошибка что ее нет.

**Comment by kost111233** [comment]
![image](https://user-images.githubusercontent.com/54816270/145019967-50f3ad3b-4e62-4dee-ace7-4ccddc2aa696.jpg)

**Comment by vvip-68** [comment]
А версия ядра какая стоит?

**Comment by kost111233** [comment]
2.7.4

**Comment by vvip-68** [comment]
Вот тут папка с библиотекой SD - она у вас есть?
![image](https://user-images.githubusercontent.com/39353139/145021375-1b18cd1e-5550-4334-b604-3e559b7dc8b5.png)

**Comment by kost111233** [comment]
Я от туда ее тоже удалил)

**Comment by vvip-68** [comment]
Потому и не находит

**Comment by kost111233** [comment]
Спасибо. Скетч залился
