### ISSUE TITLE
Не стартует клиент mqtt

### ISSUE THREAD

**Issue by VahrushevSA** [vvip-68/GyverPanelWiFi#182]
Здравствуйте!
в настройках ESP8266 выставил USE_MQTT 1
в MQTT parameters сервер указал
при работе платы не стартует mqtt клиент

**Comment by AndreyLyamkin** [comment]
что пишет в мониторе порта?

**Comment by vvip-68** [comment]
f rfr dsа оняzfkчто он не стартует?

**Comment by VahrushevSA** [comment]
в мониторе порта по идее должно отображаться подключение к серверу, его нет

**Comment by vvip-68** [comment]
Давайте лог с монитора порта сразу после запуска контроллера.
А в настройках подключений (например в приложении) вообще галочка стоит, "Использовать MQTT"? 
Может у вас он вообще отключен?

**Comment by VahrushevSA** [comment]
WiFiPanel v.1.12.2021.1206


Инициализация файловой системы... 
FS: Использовано 24576 из 2072576 байт
Загрузка строк выполнена.
Использованы адреса EEPROM 1000 - 1037
Свободно ячеек 3058

Host: 'WiFiPanel' >> 30x17

Найдены сохраненные настройки: FS://eeprom.bin

Подключение к m-k -> 192.168.66.45
.............
WiFi подключен. IP адрес: 192.168.66.45

UDP-сервер на порту 2390
Режим: Морской прибой
NTP-сервер ru.pool.ntp.org -> 193.192.36.3
Отправка NTP пакета на сервер ru.pool.ntp.org

Запрос текущей погоды
Погода получена: Yandex
Город: Kamensk-Uralskiy
Сейчас: пасмурно, -7ºC
Код иконки: 'ovc'
Цвет неба: '#9bccff'
Сейчас: 
Рассвет: 09:14
Закат: 16:15

UDP << ip='193.192.36.3:1

**Comment by vvip-68** [comment]
В приложении PanelSetup в настройке соединения галка "Использовать MQTT" включена? Настройки соединения настроены? Какой брокер используется? Скриншот экрана приложения пожалуйста.

**Comment by VahrushevSA** [comment]
DEFAULT_MQTT_SERVER "192.168.66.252"
в логе ни слова о сервере

**Comment by vvip-68** [comment]
Значит в настройках отключено использование

**Comment by VahrushevSA** [comment]
Извините! не глянул PanelSetupWiFi
всё заработало.
Спасибо, что оперативно отвечаете!
