### ISSUE TITLE
Ошибка в тексте на сайте.

### ISSUE THREAD

**Issue by boomega** [vvip-68/GyverPanelWiFi#185]
Здраствуйте!
Куда об этом писать на гитхабе не понимаю, поэтому пишу здесь.
Читаю как настроить, и не могу понять откуда число 5, потом понял что ошибка, должно быть число 3, прошу исправить.
Спасибо.

![Ошибка в тексте](https://user-images.githubusercontent.com/75878897/145671926-2fa699c7-b5be-4700-85d7-5c0f808afaa6.png)

https://github.com/vvip-68/GyverPanelWiFi/wiki/Настройка-ПО-управления-эффектами-"Jinx!"-как-источника-синхронизации-устройств-в-группе

**Comment by vvip-68** [comment]
Спасибо, исправил
