### ISSUE TITLE
Светодиоды

### ISSUE THREAD

**Issue by playeeerua** [vvip-68/GyverPanelWiFi#188]
Скучали по мне?)
У меня вопрос по питалову. Блок питания 5В 3А. Светодиодов как у гайвера 42 на 8. Отпаяли одну ленту (верхнюю и вуаля, заработало) Возможно ли что ему питания не хватает? Хотя у гайвера ж на видео такой же блок…

![2330019A-4986-4D38-A729-B6288EB2FA22](https://user-images.githubusercontent.com/66793382/145719104-3ae81429-f89a-477e-b9f5-ca7d28bb2031.jpeg)

**Comment by vvip-68** [comment]
Думаю, что причина не в этом. Скорее в верхней ленте где-то замыкание.

**Comment by playeeerua** [comment]
Тоже об этом думал, щас будем верхнюю ленту менять

**Comment by simonovich** [comment]
На чем оно там. Нанка? Только что зависал на канале у Гайвера, где он рассказывал, что для нанки верхний предел 600 светодиодов. Т.е. все должно работать.

**Comment by playeeerua** [comment]
Работает, поменяли верхнюю и нижнюю ленту (внизу половина работала). Но вот еще проблема (как же без нее) Если с резис
![29C645D1-DE68-4166-BB02-04A5BE8A5BA2](https://user-images.githubusercontent.com/66793382/145723184-dd6dd4c6-c1b5-42f4-a030-f4d69918b863.jpeg)
тором, то сверху 2 линии белые (фото 1), подключить напрямую, артефакты убираются
![F0D2EB08-B713-45C1-BF56-EE06499FB2D5](https://user-images.githubusercontent.com/66793382/145723180-69649af2-e64f-4827-a73c-e1a523737421.jpeg)

**Comment by vvip-68** [comment]
Может сопротивление резистора великовато?
Совсем без резистора чревато выгоранием пина контроллера. Как повезет.

**Comment by 247760** [comment]
@playeeerua  Конденсаторы по питанию есть?

**Comment by playeeerua** [comment]
Конденсатора нет. Резистор 220 Ом

**Comment by 247760** [comment]
> Конденсатора нет.
Почему?

**Comment by playeeerua** [comment]
Ну написано необязательно 😂
Нам для начало надо было сделать что-б работало, конденсатор есть, допаяем это они как я понимаю?
![image](https://user-images.githubusercontent.com/66793382/145723989-20c4f417-2554-4016-af25-88dee5cff5eb.jpg)

**Comment by playeeerua** [comment]
Вот резистор
![Uploading image.jpg…]()

**Comment by playeeerua** [comment]
Вот резисторы
![image](https://user-images.githubusercontent.com/66793382/145724060-6e6a6c01-3108-46bc-ab0f-26e58cd4c56c.jpg)

**Comment by 247760** [comment]
Запаивайте, он есть на всех схемах, ещё добавляют между ног электролита керамический конденсатор, но Вы хоть этот пока добавьте.

**Comment by playeeerua** [comment]
Все, с резистором вижу, продали кОм

**Comment by playeeerua** [comment]
Он как бы есть, но пишет необязательно🤔
Но в лампу добавил, вот и остатки есть. Главное что наконец-то спустя 3 месяца мы дошли до финишной прямой, осталось совсем чуть-чуть. Спасибо за терпение, без вас бы я не справился) Но есть вопрос по поводу приложения. А как часы убрать?) Все перетыкал. А то он везде, в бегущей строке, в режимах, а так отдельно включить как режим никак?

**Comment by vvip-68** [comment]
С часами не надо все тыкать. Достаточно в настройках часов в приложении снять галку "Часы поверх эффектов"

**Comment by vvip-68** [comment]
Отдельно часы включить как режим - есть "режим (эффект) который называется "Часы"

**Comment by playeeerua** [comment]
Нашел, спасибо
