### ISSUE TITLE
Случайный выбор эффектов 

### ISSUE THREAD

**Issue by fastdron** [vvip-68/GyverPanelWiFi#20]
Привет. Подскажите - есть ли возможность воспроизводить в случайном порядке (или в заданной последовательности ) эффекты только с одной из групп . Например воспроизвести в случайном порядке все Эффекты с карты памяти?. Ибо когда выбираешь  в приложении с телефона "Sd-карта / случайный выбор " - запускается один из эффектов на карте памяти и крутится постоянно , возможно-ли как-то заставить :
1) крутить по порядку все эффекты с карты памяти (циклически ) если выбран в ручном режиме эффект "SD-карта - случайный выбор"?
2) если выбран демо режим и начинает воспроизводится эффект " SD-карта \ случайный выбор"- иметь возможность переключаться между двумя вариантами воспроизведения 
- прокручивается один случайно выбранный эффект с карты и по завершении переключается на другой (не с карты ) (как работает сейчас)
- прокрутить все эффекты с карты и только потом переключаться на другой режим

**Comment by vvip-68** [comment]
Можно, если переписать алгоритм.

**Comment by fastdron** [comment]
Как "костыль" можно использовать последовательность строк бегущих (вместо текста например точка и все)с заданным эффектом )

**Comment by vvip-68** [comment]
Не знаю. Пробуйте. Но скорее всего нет. Связанно с особенностями передачи строк UTF-8 из приложения в устройство.

**Comment by vvip-68** [comment]
Чего костыли то расставлять. Возьмите и измените прошивку так как это именно вам нужно. Это ж конструктор по большому счету. Что хочу то и ворочу.

**Comment by vvip-68** [comment]
И строк всего 36, а эффектов на SD-карте (по крайней мере у меня) - более 40 штук

**Comment by fastdron** [comment]
> Это ж конструктор по большому счету. Что хочу то и ворочу.

С моими познаниями в программировании - это практически нереальная задача ) ,по крайне мере -пока что)))

**Comment by vvip-68** [comment]
Учиться никогда не поздно, а главное - полезно. А наличие цели - стимулирует. Наличие же исходного года - сильно помогает разобраться что к чему и что изменить, чтобы получить как надо. Тем более всегда можно спросить, если что-то непонятно.

**Comment by vvip-68** [comment]
> А нельзя-ли в бегущих строках указать просто пробел?

Но кроме пробела же еще есть куча "непечатных" символов. Вот на же фигурная скобка не отображается. Тильда ~ скорее всего не отображается. Да той же буквы ё в шрифте нет

**Comment by fastdron** [comment]
> Тем более всегда можно спросить, если что-то непонятно.

Спасибо огромное!!!!!! Учусь.со свободным временем проблемка только)его вечно не хватает. По выходным и вечерами занимаюсь.

**Comment by fastdron** [comment]
> Вот та же фигурная скобка не отображается

оооо,точно, спасибо за наводку. а с кодом буду разбираться помаленьку) . Смотрю новую версию выкатили! там погода с другого источника будет браться? По идее в Украине тоже заработает,вечером проверю иотпишусь
