### ISSUE TITLE
e131 delay 

### ISSUE THREAD

**Issue by yusufsulaiman** [vvip-68/GyverPanelWiFi#203]
Пробовал е131. и он работает.Для 16x16 все выглядит плавно без задержек. но после попытки 40x20 есть задержка после строки 16. я использую сглаз jinx & router

**Comment by yusufsulaiman** [comment]
https://user-images.githubusercontent.com/6624207/146705182-cd9f646a-0613-4f08-bc40-b38180d80324.mp4

**Comment by vvip-68** [comment]
Выглядит как проблемы с сетью или плохая работа роутера. Пакеты теряются...
У меня примерно такое наблюдалось на DIR-615. Перегрузишь роутер - какое-то время работает более-менее. Через какое-то время опять. Поменял роутер на TPLink Archar C80 - проблемы перестали.
