### ISSUE TITLE
Правка для эффекта водоворот

### ISSUE THREAD

**Issue by waw555** [vvip-68/GyverPanelWiFi#204]
Здравствуйте!

Кажется опечатка в эффекте водоворот.

В строке
float spd = (map8(255-getEffectSpeedValue(MC_SWIRL), 50, 100) / 100.0) / (USE_SEGMENTS_PAINTBALL != 0 ? 1 : (float)seg_num);

необходимо USE_SEGMENTS_PAINTBALL  заменить на USE_SEGMENTS_SWIRL

**Comment by vvip-68** [comment]
Да, действительно. Спасибо.

**Comment by Des-75** [comment]
У меня водоворот выглядел очень тускло (яркость сколько ни поднимай - толку ноль), в красных цветах... Я всё думал, что за всратый эффект и кому он нужен..
Исправил - стало нормально, цветно, ярко.
**Waw55**, спасибо
