### ISSUE TITLE
Проблемы с подключением. 

### ISSUE THREAD

**Issue by bosser2407** [vvip-68/GyverPanelWiFi#206]
Нивкакую не хочет работать через роутер. 
Said пароль и IP ввожу верно, в роутере устройство появляется. Но по этому адресу в приложении подключатся отказывается((
8266 d1 mini и nodemcu. Эти же платы прекрасно работают и подключаются с Wled и esphome

**Comment by vvip-68** [comment]
Ставите на телефон программу типа Ping и добиваетесь, чтобы контроллер пинговался с телефона. 
Смотрите настройки сети в контроллере и в роутере.
Как только контроллер начнет отвечать на запросы программы с телефона - вы сможете подключиться.

**Comment by bosser2407** [comment]
> Ставите на телефон программу типа Ping и добиваетесь, чтобы контроллер пинговался с телефона. Смотрите настройки сети в контроллере и в роутере. Как только контроллер начнет отвечать на запросы программы с телефона - вы сможете подключиться.

![2021-12-28_07-25-38](https://user-images.githubusercontent.com/85440955/147527960-6f2caf8a-a37a-4df9-8fe5-db54146be992.png)
Сразу после ввода SSId, пароля и перезагрузки пингуется. Через секунду уже нет. Какие настройки можно ковырять, я честно не представляю. Если бы так себя вели все устройства, а такое только с этой прошивкой

**Comment by vvip-68** [comment]
Отключите для начала получение погоды и синхронизацию времени с интернета. Если контроллер пытается получить погоду или время - операции блокирующие - и сервер не отдает данные - контроллер больше ничего делать не умеет кроме как ждать ответа. В этот момент подключиться приложением к контроллеру не удастся. Если после отключения погоды и времени соединение будет устанавливаться - дальше смотрите почему не получает погоду. Если вы с Украины и стоит синхронизация с Яндекс - погоды - ваше правительство заблокировало сервера яндекса и получить с него погоду не получится.

**Comment by vvip-68** [comment]
Эффект "Лампа" - это просто чтобы забить место в менюшках приложения. Настоящий список эффектов принимается от контроллера после установки соединения. Очевидно, что если нормального соединения установить не удается - ничего от контроллера и не получается в приложение. В том числе и список эффектов.

И смотрите еще что в мониторе порта. Может у вас контроллер циклически перегружается по какой-то причине...

**Comment by bosser2407** [comment]
> Эффект "Лампа" - это просто чтобы забить место в менюшках приложения. Настоящий список эффектов принимается от контроллера после установки соединения. Очевидно, что если нормального соединения установить не удается - ничего от контроллера и не получается в приложение. В том числе и список эффектов.
> 
> И смотрите еще что в мониторе порта. Может у вас контроллер циклически перегружается по какой-то причине...

Чудеса. Отключение погоды кажется помогло. Я в Крыму, и с яндексом у нас вроде проблем нет.  И с отключением погоды, в MQTT пошли топики. До этого MQTT тоже не работал
![2021-12-28_10-50-54](https://user-images.githubusercontent.com/85440955/147542328-e0561430-eb9a-4fb9-a7bc-9caedacc1672.png)

**Comment by vvip-68** [comment]
Потому что скорость порта надо выставить такую же как настроено в приложении - а там стоит 115200

**Comment by vvip-68** [comment]
Что у вас возвращает в браузере, скажем. такой запрос
 https://yandex.ru/time/sync.json?geo=62

**Comment by bosser2407** [comment]
> Как то так


![2021-12-28_11-32-13](https://user-images.githubusercontent.com/85440955/147546131-34737a91-42ee-447a-ae40-034c4980b539.png)

**Comment by vvip-68** [comment]
Ну, то есть - так то погоду с яндекса он получает... Почему же в приложении включение получения погоды завешивает?... А если погоду с OpenWeatherMap брать?
