### ISSUE TITLE
Фризы при эффектах

### ISSUE THREAD

**Issue by Chez718** [vvip-68/GyverPanelWiFi#207]
Здравствуйте, сделал панель 30х60, использовал сначала esp8266, все было нормально, но не хватало фпс, заменил на esp32, стало работать заметно быстрее, но иногда проскакивают фризы, каждые 4-5 секунд на пол секунды и бывает каждые 10 секунд на секунду, в чем может быть проблема?

**Comment by Chez718** [comment]
Дополню: эффекты абсолютно любые, от простых до сложных, поэтому, думаю вряд ли проблема в нехватке оперативной памяти. И да, с есп8266 работало медленно но без фризов, а тут быстрее, но с фризами.

**Comment by vvip-68** [comment]
Не настроено соединение с интернетом.

**Comment by Chez718** [comment]
Вроде с самого начала настроил и время синхронизировал, сеть есть.

**Comment by vvip-68** [comment]
Других причин для фризов кроме как блокирующих запросов в интернет - нет. Время, погода, MQTT - что так у вас включено...
