### ISSUE TITLE
GyverPanelWiFi_v1.06

### ISSUE THREAD

**Issue by AxxiMator** [vvip-68/GyverPanelWiFi#21]
_Здравствуйте_. 
Очень понравился проект.
Очень хотелось бы увидеть в проекте версию часов со ШРИФТОМ **6х8** - могу даже оказать помощь с кодом для данного шрифта.
Данный размер шрифта **очень актуален для матриц WS2812 размером 8х32**. И цифры красивее смотрятся.
Только как его  интегрировать в код - не знаю.
И в версии часов, очень не хватает **RTC DS3231**, который раньше был. ( при отключении света и отсутствии интернета - время будет сбиваться, что не очень хорошо для ЧАСОВ.)
Заранее благодарен. **Александр**

**Comment by vvip-68** [comment]
Все доступные символы шрифта определены в файле fonts.h (разложите Hex в binary - увидите образы символов).
Делаете по аналогии файл со своим шрифтом. Далее в a_def_soft.h в строках184,185 меняете ширину/высоту символа в соответствии с вашими размерами - должно заработать. Если нет - в файле funningText.ino возможно придется отладить getFont() и drawLetter()

**Comment by vvip-68** [comment]
Данная версия не предполагается для эксплуатации в отсутствии интернета. Он сейчас есть практически везде, где есть электричество. Изначальная идея - как можно меньше компонентом, чтобы всё работала с одной маленькой платкой без лишних наворотов и дополнительного монтажа - припаял 3 провод и готово. . Исходные коды и схемы открыты - вы можете легко интегрировать энергонезависимые часы какие нужны вам для ваших потребностей.
