### ISSUE TITLE
Заполнение памяти 100%

### ISSUE THREAD

**Issue by Mosrom** [vvip-68/GyverPanelWiFi#216]
Обратил внимание, что после добавления немецкого алфавита память модуля полностью заполнена. Даже когда память заполнялась на 98% наблюдались задержки при воспроизведении эффектов. Скетч сильно разросся. Возникает ошибка компиляции. Раньше можно было удалить игры, но сейчас это сделать не так просто, так они глубоко интегрированы в прошивку. Те, кто использует модули с памятью 4 мб обязательно с этим столкнутся. Здорово, если была бы возможность отключать в скетче игровую составляющую, думаю, что не многие этим пользуются. Я даже в демо режиме их отключаю.

**Comment by vvip-68** [comment]
Это у вас какие-то проблемы, не связанные с добавлением немецких букв.
Для немецких букв добавлено начертание самой буквы - это порядка 100 байт и пару case в условиях определения какой образ буквы из массива шрифтов выбирать для отображения.

Вот результат компиляции СО ВСЕМИ ВКЛЮЧЕННЫМИ фичами - звуки, индикатор, MQTT, SD-карта, погода и так далее. "Полный фарш"

![image](https://user-images.githubusercontent.com/39353139/154892384-abed3e66-ec80-4458-8424-ed08a1181bd9.png)

Как видите - и до 60% заполнение не дотягивает...

**Comment by Mosrom** [comment]
Всё зависит от того, какую плату Вы выбрали в менеджере плат и какой объём памяти установили. У меня это ESP32 Dev Module.

**Comment by vvip-68** [comment]
Гирлянда на 1000 лампочек. 92% постоянной (памяти кода) и 17% оперативной под переменные.
Ничего не виснет, всё фунциклирует.

![image](https://user-images.githubusercontent.com/39353139/155145802-ff519d11-49c6-46ce-ad3f-677631e829cf.png)

Ну, берите ESP8266 - - там памяти больше остается. Или модуль с бОльшим количеством памяти.
Сам в недоумении почему ядро ESP32 столько памяти занимает. Наверное последствия индусских программистов....

**Comment by vvip-68** [comment]
Хотя вот интересно - модуль выбран 4МБ в настройках - а объем доступной пишет 1МБ...
А... Там выделяется 1МБ на приложение, 1.2MБ на ОТА и 1.5 на SPIFFS...

Попробуйте отключить ОТА (будете по проводу прошивку заливать). Тогда 3МБ пот приложение и 1МБ под SPIFF.
Если выбрать Huge APP 3MB No ATA / 1 MB SPIFFS...
