### ISSUE TITLE
Топик CL не содержит данных или отсутствует

### ISSUE THREAD

**Issue by Krypt0nC0R3** [vvip-68/GyverPanelWiFi#217]
Имеется лампа на актуальной прошивке (1.12), подключенная к домашнему MQTT серверу. При выполнении команды (отправленной в  cmd) `$5 FF00FF; $5 2;` значение CL не меняется. Так же, если в приложении выбрать цвет для рисования, значение этого топика не меняется.

**Comment by Krypt0nC0R3** [comment]
Сама команда при этом выполняется корректно

**Comment by vvip-68** [comment]
Там в a_main.ino строка 3179 видимо ошибка - там должно быть drawColor а не globalTextColor - видимо последствия копипаста...
