### ISSUE TITLE
GyverPanelWifi ver 1.12 sunrise time is wrong

### ISSUE THREAD

**Issue by dio1985** [vvip-68/GyverPanelWiFi#221]
GyverPanelWifi ver 1.12 sunrise time is wrong 
i tried to change the local zone (ohter country) 
but the problem is same

**Comment by vvip-68** [comment]
Sunrise time is retrieving from Weather service (Yandex or OpenWeatherMap).

**Comment by dio1985** [comment]
also i tred to install it with your original code. but sunriseTime was 28:23. .. so what is mean 28 ?? but sunset was 16:23.. 
16 mean 4Pm. but 28 what is that?

**Comment by vvip-68** [comment]
Which weather source do you use?

**Comment by vvip-68** [comment]
I`ve updated file weather.ino in repository for possible fix the issue. Please get it and try if issue is fixed.

**Comment by dio1985** [comment]
thank you!! it works !! 
have a good day!!
