### ISSUE TITLE
Default IP (не подключается к интернету, не получает погоду и время)

### ISSUE THREAD

**Issue by bulava92** [vvip-68/GyverPanelWiFi#223]
Поменяйте default ip в настройках в скетче на 0.0.0.0

С установленным в прошивке дефолтным ip ни в какую не подключается к сети, не получает время, погоду и не работает mqtt. Проверял на чистой прошивке с сайта на 3 платах - везде замена этого ip на 0.0.0.0 сразу открывала подключение к сети и прошивка начинала нормально работать. Так что дело было не в роутере и провайдере а в прошивке.

**Comment by vvip-68** [comment]
Установка с скетче 0.0.0.0 означает, что контроллер будет использовать режим DHCP - получать IP адрес от роутера.
При этом возникает вероятность, что роутер будет периодически выдавать разные адреса матрице (если на роутере не делать специальных настроек) и будет невозможно подключиться к матрице с телефона. Нужно будет либо лезть в логи и смотреть какой адрес получила матрица в данный момент (а какой, кстати?) - или смотреть текущий адрес четырехкратным нажатием кнопки. Затем исправлять этот адрес в телефоне, чтобы снова подключиться к матрице.

Задание явного адреса позволяет избежать данных потенциальных проблем. Возможно вы в скетче (или в настройках с телефона) задали неверный адрес и матрица оказалось в другой подсетке, нежели та, которую обслуживает роутер.

Второй возможный вариант, почему при задании адреса в той же подсетке, что обслуживает роутер, но нет выхода в интернет может быть следующий момент (размышляю теоретически, на практике я таких роутеров не встречал - проверьте свой).

99% роутеров имеют в своей подсетке адрес 192.168,xxx,1 - то есть, бывают роутеры, обслуживающие сети и имеющие адрес роутера 192.168.0.1, 192.168.1.1, 192.168.100.1. Именно на это и рассчитан скетч - то есть на основе заданного IP адресом шлюза в сеть (Gateway) считается адрес в указанной сети, оканчивающийся на 1.

![image](https://user-images.githubusercontent.com/39353139/159510217-090a557b-a1ad-4c1f-aaa2-0b3eefc961ca.png)

Если же ваш роутер имеет адрес, оканчивающийся не на 1 - доступа в интернет не будет. Надо исправлять у казанных на картинке строках. Какой адрес имеет ваш роутер?

**Comment by vvip-68** [comment]
Ну вот, вы, похоже, первый, кто прошел этот путь до конца.
У меня таких роутеров (оканчивающихся не на 1) нет - я с таким не сталкивался. Вышеописанное - умозаключение, базирующееся на предоставленных вами сведениях и анализе ситуации. Я думаю, что данное объяснение верно.

Проверить (при желании) легко - изменить 1 в указанных строках на 254 для вашего роутера и указать явно адрес матрицы в сети. Если все при таких настройках будет работать - значит мое предположение о причинах явления - верно.
