### ISSUE TITLE
Звуки в GyverPanelWiFi

### ISSUE THREAD

**Issue by EDUARDT68** [vvip-68/GyverPanelWiFi#225]
Добрый день.
А в  GyverPanelWiFi можно свои мелодии добавлять?

**Comment by EDUARDT68** [comment]
Я на карту закинул 4 аудиофайла. В меню их не видно. Ни в будильнике, ни в рассвете, ни в задачах для бегущей строки.

**Comment by vvip-68** [comment]
Вот тут их прописали?
![image](https://user-images.githubusercontent.com/39353139/160252499-13209515-0737-4b40-ad7e-89e921fff8cf.png)

**Comment by EDUARDT68** [comment]
Блин. А я ищу совсем в другом месте. Да и о другом думал. Спасибо.
