### ISSUE TITLE
led corner blinking 

### ISSUE THREAD

**Issue by dio1985** [vvip-68/GyverPanelWiFi#226]
> ![20220417_150708](https://user-images.githubusercontent.com/78635592/163703057-78ce0294-745d-43bd-9427-20c816cd493c.jpg)

i have 4panels(16×16)
i found 1point blinking led. so i tried to change to other panel. but its same
and also i changed led direction by code. but its same

any problem only for me?

https://user-images.githubusercontent.com/78635592/163703343-eb608509-a93b-42a1-9894-a377ed2f9009.mp4

**Comment by vvip-68** [comment]
It is common issue for those, who do not want read instructions on several first lines of main sketch file and uses wrong version of ESP8266 core. It should be 2.7.4 version, not 3.x.x

**Comment by vvip-68** [comment]
After you install right version of esp8266 core du not forget also return led bin back to D2 from D4, that uses in case of core 3.x.x version
