### ISSUE TITLE
wifi setup err

### ISSUE THREAD

**Issue by dio1985** [vvip-68/GyverPanelWiFi#227]
1. connection to my wifi with default(192.168.0.100)
2. but my wifi was 192.168.219.xxx 
3. but GyverPanel tried to conect wrong default(192.168.0.100)
4. GyverPanel show me conected 192.168.0.100
5. so can not conect any ntp or weather .
6. this is same to wrong wifi 
![20220429_204213](https://user-images.githubusercontent.com/78635592/165938424-be4e0f94-74ad-4846-b6e0-6d774100646a.jpg)
 psswd as 2times

**Comment by vvip-68** [comment]
So, what is the question? Of course, if you connect to wrong network, you will not be able to get internet resources, available on another network. It is obviously.

Turn on matrix device into AP mode using button click on device start before it connected to wrong network, connect to the device using APPanel access point on 192.168.4.1, open PanelSetup application and set correct IP addres for device.
