### ISSUE TITLE
clock size 

### ISSUE THREAD

**Issue by dio1985** [vvip-68/GyverPanelWiFi#228]
setting : clock size > small. 
              clock vertical 
but all time and date  is not displayed . 

checking now is         21:02 ( 9:02 pm)  01.05 2022

https://user-images.githubusercontent.com/78635592/166145302-976a229b-d935-4764-b3bb-b89c80d7b65f.mp4

**Comment by vvip-68** [comment]
You right. It is a bug...

**Comment by vvip-68** [comment]
Try to update version from Git. I fixed the bug.

**Comment by dio1985** [comment]
thank you. i will try it
