### ISSUE TITLE
Просто в будильнике если плеер не прошел проверку то звуки выбирать настраивать нельзя, а в настройке бегущих строк звуки выбирать можно, я по этому и спросил?

### ISSUE THREAD

**Issue by SeregaI** [vvip-68/GyverPanelWiFi#229]
Просто в будильнике если плеер не прошел проверку то звуки выбирать настраивать нельзя, а в настройке бегущих строк звуки выбирать можно, я по этому и спросил?
Спасибо за разъяснения

_Originally posted by @SeregaI in https://github.com/vvip-68/GyverPanelWiFi/discussions/198#discussioncomment-2706460_

**Comment by vvip-68** [comment]
Запрет кнопочек в приложении в зависимости от - сильно усложняет приложение, которое и так довольно сложное для изменения. Поэтому в данном конкретном месте в интерфейсе это есть, но по указанным выше ограничениями в реале - не работает. Перфекционисты могут это поправить самостоятельно. Все исходники в репозитории - в комплекте.
