### ISSUE TITLE
Ночные часы

### ISSUE THREAD

**Issue by AGRO666** [vvip-68/GyverPanelWiFi#23]
А как должны работать Ночные часы? Ставлю по времени включение Ночных часов, время наступает и панель тухнет полностью. Панель 18х10, если это важно. 
ЗЫ попробовал сейчас на стандартной панели 16х16 - вручную выбираем эффект Ночные часы и всё тухнет.

**Comment by vvip-68** [comment]
Должны отображаться часы на черном фоне минимальной яркостью одного из 7 выбранных цветов - красный, синий, зеленый, желтый, голубой, розовый, белый. Естественно, если время инициализировано и известно системе. Если время неизвестно - ничего отображаться не будет - просто черный экран.

**Comment by AGRO666** [comment]
Ага, нашел, работает оказывается, просто на матрице с тонированным стеклом не очень видно.

**Comment by vvip-68** [comment]
clock.ino строка 1132 - функция getNightClockColorByIndex()
Увеличте там яркость ночных часов на какую вам нужно.
