### ISSUE TITLE
Ошибка в апк

### ISSUE THREAD

**Issue by ClausZP** [vvip-68/GyverPanelWiFi#24]
Приключении настроек времени выпадает ошибка прикрепил скриншот. Телефон Xiaomi 9t(k20) прошивка miui 12.
![Screenshot_2020-11-13-20-00-30-516_com vvip_phone GyverPanelWiFi](https://user-images.githubusercontent.com/67625092/99105540-5f384e80-25eb-11eb-9d8b-943488be309c.jpg)

**Comment by ClausZP** [comment]
![Screenshot_2020-11-13-20-04-52-681_com vvip_phone GyverPanelWiFi](https://user-images.githubusercontent.com/67625092/99105707-a8889e00-25eb-11eb-83b8-a534caf9569d.jpg)

**Comment by vvip-68** [comment]
Ну да, бывает. У вас какие-то неинициализированные настройки в прошивке и/или ошибка передачи из прошивки в приложение. Приложение на смартфоне - слабо управляемый конструктор, забитый до своего предела и не поддающийся практически уже модификации. Поэтому - что есть, то есть. Пробуйте еще раз. В большинстве случаев - получается.

**Comment by ClausZP** [comment]
Ошибка возникает просто при переходе во вкладку, если не нажимать "end application" окошко закрывается, и дальше работает. Спасибо за проделанный труд, и быструю реакцию.

**Comment by vvip-68** [comment]
У меня такой ошибки не возникает - поэтому я даже проверить не смогу что может быть не так. 
Если вы что-то меняли в прошивке, связанное с этим - откатывайте назад. Или на прошивке, скачанной с репозитория без изменений тоже вот так выходит?
