### ISSUE TITLE
Предложение "Не квадратная матрица"

### ISSUE THREAD

**Issue by NewdreamN** [vvip-68/GyverPanelWiFi#240]
Уважаемый **vvip-68**, в первую очередь, огромная благодарность за проект и проделанную работу!
Возникла необходимость изготовить матрицу иного формата, т.е. - треугольник, круг, иная форма. 
Нашел проект, описывающий изготовление маски со светодиодами, библиотека fastled.
https://www.youtube.com/watch?v=zYZkbfmCuEY
Автором предлагается описывать положение каждого светодиода в коде, также автор дает ссылку на генератор формы матрицы:
https://macetech.github.io/FastLED-XY-Map-Generator/
Есть ли возможность как то внедрить такую возможность в данный проект?
Спасибо за ответ!

**Comment by vvip-68** [comment]
Теоретически наверное есть возможность - в видео же описан алгоритм как делать трансляцию индексов светодиодов к нужной форме. Ссылка на гитхаб проекта есть.
Практически - кто будет этим заниматься? Мне это не интересно.
Да и зачем, если есть уже готовый проект.
Коды проектов - открытые. Изучите алгоритм  и внедрите его в проект. 
Или спросите на форуме у Гайвера - не возьмется ли кто за работу и сколько он за эту работу хочет.
