### ISSUE TITLE
Проблема с MQTT

### ISSUE THREAD

**Issue by AndreyIvkov** [vvip-68/GyverPanelWiFi#243]
Собрал прошил все работает.но подключиться через MQTT очень сложно.сразу после перезагрузки получается но не на долго.отваливается и больше не подключается. По сети wi-fi лучше но не идеально.тоже может отвалиться и потом не подключается.собрал на wemos d1 mini. MQTT брокер wqtt.ru.

**Comment by vvip-68** [comment]
Ну, по симптомам налицо проблемы со связью.
Либо в вашей сети с роутером что-то не так (ищите проблему, устраняйте), либо с самим микроконтроллером. Мне встречались экземпляры, которые очень плохо держали связь по WiFi. Обычно это контроллеры прямоугольной формы, плата коричневого цвета, с надписью Wemos белой краской - вот такие
![image](https://user-images.githubusercontent.com/39353139/203927827-80f73c9d-3d8e-4dc3-b204-d0f0330b8ea8.png)

**Comment by AndreyIvkov** [comment]
У меня другая платка wemos d1 mini. Синяя. Как улучшить связь?может внешнюю
антенну припаять от старого роутера например?

вс, 27 нояб. 2022 г., 11:27 vvip-68 ***@***.***>:

**Comment by vvip-68** [comment]
Тут я ничего подсказать не могу. Спросите в профильных форумах по железу, по платам Wemos d1 mini - может там что подскажут.

**Comment by AndreyIvkov** [comment]
Я все таки припаял антенну от старого роутера и всё заработало.связь держит
через MQTT подключаюсь легко и ни чего не отваливается. Спасибо.

сб, 10 дек. 2022 г., 14:55 vvip-68 ***@***.***>:
