### ISSUE TITLE
До нового года осталось.....

### ISSUE THREAD

**Issue by tih66** [vvip-68/GyverPanelWiFi#253]
На гирлянде пишет что до нового года осталось 22 дня, а везде что 23 дня.
![изображение](https://user-images.githubusercontent.com/74896220/206630713-80f9e720-f78d-405b-9e67-15997cd8c294.png) 
строка показа "До {C#00D0FF}Нового года {C#FFFFFF}осталось {C#10FF00}{R01.01.***+}{S01.12.****#31.12.**** 23:59:59}{E21}";

**Comment by vvip-68** [comment]
А это вопрос как считать. На самом деле осталось 22 дня 12 часов 52 минуты
Часы и минуты просто не показываются.
Хотите - исправьте скетч чтоб показывались.
Или, если хотите - добавляйте в скетче +1 день к результату.

**Comment by 247760** [comment]
Приветствую @vvip-68, где то на просторах Гайвер группы, кто то писал что по [тут](https://github.com/dbprof/ny-led-matrix/blob/5c018c703792b22f99cf80462bd681ff2b285e50/custom.ino), написан режим COUNTER для отсчёта вроде как от 10 секунд до 0 до Новому году, правда ли это? Спасибо :)

**Comment by vvip-68** [comment]
Я не знаком с тем проектом, не знаю что там есть.
