### ISSUE TITLE
Изменение цветовой последовательности для одного отрезка

### ISSUE THREAD

**Issue by Melkiyby** [vvip-68/GyverPanelWiFi#255]
Привет. Собрал матрицу 48х14(6х14 на окно) и так совпало что одна лента оказалась отличной по цветовой последовательности. Есть ли возможность для этого участка указать нужную последовательность или нужно глубокое погружение в библиотеку FastLed?
![Screenshot_20221212-004946_Video Player](https://user-images.githubusercontent.com/17052717/206931057-9894f465-5517-418a-b7c2-f7f879f325b9.jpg)

**Comment by vvip-68** [comment]
Мне не известен способ как это сделать и я не вижу простого решения.
Есть вроде какая-то возможность разделять вывод на ленту через подключение к разным пинам контроллера и для каждого пина указать свои настройки. Но это действительно нужно глубокое погружение в FastLED и я с этим не сталкивался и ничего конкретного по этому поводу сказать не могу.

**Comment by vvip-68** [comment]
Ну, мои эксперименты показали, что это возможно.
Вывод на части ленты разделяется на разные пины, каждый пин инициализируется со своей цветовой последовательностью. Должно работать.

**Comment by Melkiyby** [comment]
Ну про вывод через разные пины это понятно, сейчас ковыряю fastled на возможность внесения коррекции в сам массив что бы еще один провод не тянуть. По результатам отпишусь

**Comment by vvip-68** [comment]
Проще всего, видимо, найти процедуру FastLedShow() и в указанное место

![image](https://user-images.githubusercontent.com/39353139/207001496-e027ac13-ee8d-4bd1-bbbc-9d509b766edc.png)

вставить небольшой цикл, который пробегает по участку матрицы, которая "не того цвета" и меняет для каждого пикселя цвета с RGB на GRB или как там оно у вас...

**Comment by Melkiyby** [comment]
Всё верно, в это место нужно вставить 
![123](https://user-images.githubusercontent.com/17052717/207253250-8c757a43-4d88-4ec4-bc25-56857f7335f6.jpg)
Осталось проверить на подтормаживание

**Comment by Melkiyby** [comment]
Был выявлен косяк с морганием изменённого участка(синий с красным чередовались) в режиме рисования, игр, загрузки картинок и на некоторых эффектах. Вот фикс
![456](https://user-images.githubusercontent.com/17052717/207606742-6f3bd921-fff6-4698-9a5f-93366975f80d.jpg)

**Comment by vvip-68** [comment]
Расскажите словами в чем смысл? Что-то не соображу...

**Comment by Melkiyby** [comment]
Я согласен что мой метод не самый быстрый. Завтра попробую с memcpy() если конечно мозга хватит.

**Comment by vvip-68** [comment]
В проекте есть несколько мест, где используется memcpy(), посмотрите там. Почитайте в инете про функцию с примерами.
Ничего сложного - указывается куда копировать (приемник), откуда копировать (источник) и сколько копировать (в байтах). Помним, что цвета в массиве - эта структура RGB, то есть один цвет - 3 байта. Вроде бы так.
