### ISSUE TITLE
Не весь список анимаций в приложении

### ISSUE THREAD

**Issue by altdaps** [vvip-68/GyverPanelWiFi#258]
Приветствую, спасибо за отличный проект, пользуюсь уже третий год.
Сегодня скачал последнюю версию (и прошивки и приложения), кроме необходимых для работы настроек ничего не менял, но столкнулся с проблемой - в списке анимации в приложении, в выпадающей списке можно выбрать только сердце. В чем может быть причина?

**Comment by Gomerchik** [comment]
Так же повторил этот проект на окно с размерами 18*12. Спасибо за труды. Хотелось бы добавить анимацию флага из папки pics, но че-то ни как не догоню как лучше и проще это сделать( Столько программ запутался совсем. Анимацию из gif-ки сделать и запускать с карты памяти? (тогда надо ее прикрутить к проекту), или вписать в скетч? Я скорее копировальщик, чем программист - Хорошая инструкция и окно радует соседей)) 
Подскажите - подмогните, чем сможете.

**Comment by altdaps** [comment]
> vvip-68, действительно, марио имеет высоту 16 пикселей, а у меня матрица - 14. В ранних версиях прошивки проверки размера матрицы видимо не было, поэтому работало. Спасибо.

**Comment by vvip-68** [comment]
Не было. Зачем вам безголовый Марио?
Впрочем, если хотите - отключите проверку тут:
![image](https://user-images.githubusercontent.com/39353139/207762927-166f728b-50df-4ea3-ba27-4802de6333ef.png)

**Comment by vvip-68** [comment]
>Так же повторил этот проект на окно с размерами 18*12. Спасибо за труды. Хотелось бы добавить анимацию флага из папки pics, но че-то ни как не догоню как лучше и проще это сделать( Столько программ запутался совсем. Анимацию из gif-ки сделать и запускать с карты памяти? (тогда надо ее прикрутить к проекту), или вписать в скетч? Я скорее копировальщик, чем программист - Хорошая инструкция и окно радует соседей))
Подскажите - подмогните, чем сможете.

Хорошая (я так считаю) инструкция по анимациям дана в комментариях в начале файла animation.ino
Количество кадров анимации ограничено 20, для флага, я думаю, хватит. В памяти контроллера это тоже поместится.

Для более сложных эффектов из Jinx, которые занимают много памяти (посмотрите размер файла ролика, сохраненного в Jinx) - требуется подключение SD-карты

**Comment by Gomerchik** [comment]
Спасибо. Буду изучать пока жду картридер.

  
>Четверг, 15 декабря 2022, 6:15 +03:00 от vvip-68 ***@***.***>:
> 
> 
>Так же повторил этот проект на окно с размерами 18*12. Спасибо за труды. Хотелось бы добавить анимацию флага из папки pics, но че-то ни как не догоню как лучше и проще это сделать( Столько программ запутался совсем. Анимацию из gif-ки сделать и запускать с карты памяти? (тогда надо ее прикрутить к проекту), или вписать в скетч? Я скорее копировальщик, чем программист - Хорошая инструкция и окно радует соседей))
>Подскажите - подмогните, чем сможете.
Хорошая (я так считаю) инструкция по анимациям дана в комментариях в начале файла animation.ino
Количество кадров анимации ограничено 20, для флага, я думаю, хватит. В памяти контроллера это тоже поместится.
Для более сложных эффектов из Jinx, которые занимают много памяти (посмотрите размер файла ролика, сохраненного в Jinx) - требуется подключение SD-карты
—
Reply to this email directly,  view it on GitHub , or  unsubscribe .
You are receiving this because you commented. Message ID:  <vvip-68/GyverPanelWiFi/issues/258/1352503804 @ github . com>  
 
С уважением,
Станислав Миронов
***@***.***
