### ISSUE TITLE
До Нового года осталось - дальше отображаются фигурные скобки и то, что в них (макросы вшиты из примеров)

### ISSUE THREAD

**Issue by ACKET2009** [vvip-68/GyverPanelWiFi#261]
Здравствуйте. 
 До недавнего времени макросы, вроде показывали, сколько осталось дней - 11, 10... А теперь первый длинный макрос пишет с изменением цветов строку, но отображает и фигурные скобки и текст за ними. Я ничего не менял - это как-то само изменилось. Может нужно что-то изменить в макросах? Или почему такое происходит?

**Comment by 247760** [comment]
@ACKET2009 вот бы ещё скрин\копия строки из телефона. Там сначала идут дни, потом новое условие дни и часы, видимо у Вас лишняя случайная скобка и начала светиться в виду выполнения нового условия.

**Comment by vvip-68** [comment]
Возможно макрос был не совсем корректно написан изначально. И в той версии такие "отступления от правил" сходили с рук. По "многочисленным просьбам трудящихся" этот макрос немного передела - вместо конкретного года теперь можно указывать `****` или `***+` плюч время задавать с секундами. Возможно отступление от стандарта написания макроса уже не позволяет скетчу его правильно интерпретировать...

**Comment by ACKET2009** [comment]
![2022-12-24 19 36 49](https://user-images.githubusercontent.com/16642654/209444448-c7d65c5b-9876-443f-8376-2348dbe78694.jpg)
![2022-12-24 19 37 12](https://user-images.githubusercontent.com/16642654/209444451-7301aa60-920b-48c7-8a93-096c63bb2383.jpg)
Вот такие макросы подтянулись при прошивке из скетча. Я ничего не менял...

**Comment by ACKET2009** [comment]
Я не сам писал - это примеры макросов, которые встроились из скетча при прошивке.

**Comment by vvip-68** [comment]
У меня точно такие же макросы - все прекрасно отображается.
Второй макрос - "особенный" он при нажатии на кнопку "Показать" сам остаток времени не покажет.
Он полностью работает только внутри скетча, когда приходит время ему отображаться - там вычисляются все нужные параметры, которых при отображении по кнопке "Показать" просто нет в наличии.

**Comment by ACKET2009** [comment]
странно... я на две платы загрузил. Одна на окне 12х12 диодов на mini 8266, другая на 16х16 диодов матрица на nodemcu и на обеих одинаковая история...

**Comment by vvip-68** [comment]
Ну дело же не в самих платах, а в том, что где-то что-то неправильно настроено или работает. И если для обоих плат (пусть и разных) настроено / работает одинаково неправильно - результат будет одинаково неправильный.

Почему именно у вас происходит вот так - я не знаю. Даже предположений никаких нет. Может кто-то другой сталкивался с этим и решил проблему. Я в этом помочь не могу.

Посмотрите в мониторе порта. Обычно если что-то идет не так, в мониторе выводятся какие-нибудь сообщения в лог.

**Comment by vvip-68** [comment]
Попробуйте в этой строке там где в макросе #C - прямо на телефоне стереть "C" и написать еще раз заглавную латинскую "C". Может быть в скетче по ошибке или недоразумению в готовых текстовых строках вместо латинской С закралась точно такая же по написанию, но буква кириллицы "C"?

**Comment by ACKET2009** [comment]
Ну это, получается, только с этим макросом, который на первом скриншоте... остальные все хорошо работают... Я пока внешне не могу определить правильность их написания - нужно сверяться со справкой. Но если они написаны правильно, то в каком месте копать? Может в последнем скетче присутствуют поправки не совместимые с шаблонами, заложенными изначально?

**Comment by ACKET2009** [comment]
Хорошо, попробую.

**Comment by vvip-68** [comment]
У меня этот макрос выглядит на телефоне точно так же как на скриншоте и он работает.

**Comment by ACKET2009** [comment]
пробел поменял после До - убрал и после первого макроса поставил. Так заработало...

**Comment by vvip-68** [comment]
![image](https://user-images.githubusercontent.com/39353139/209445853-7cc5946f-4701-4f4f-a77e-6bb66e0273eb.png)

**Comment by 7918514** [comment]
Друг столкнулся с подобной проблемой и именно вчера. Причём у него на двух устройствах одинаково загружено (прошивка+макрос). На одном устройстве норм работает, а на втором шпарит со всеми скобками и символами. Сравнили - отличий не нашли. Скопировал с рабочего, вставил в нерабочий, сохранил, всё заработало штатно. Причём до вчерашнего дня всё работало без нареканий. Может быть простое нажатие "Сохранить" решило бы проблему, но увы сначала скопипастили, а потом "Сохранили".

**Comment by vvip-68** [comment]
> А какого числа должно показывать помимо остатка дней ещё и часы?

Конда останется 0 дней

**Comment by ACKET2009** [comment]
Странно эта строка себя ведёт - опять полезли символы... убрал первый цветовой макрос, в итоге... так стабильно показывает...
