### ISSUE TITLE
При включении тухнущие красные часы, пока не перевключишь несколько раз эффекты не запускаются

### ISSUE THREAD

**Issue by ACKET2009** [vvip-68/GyverPanelWiFi#262]
Здравствуйте! При включении питания начинает работать последний запущенный эфект, потом он притухает и запускаются красные часы у которых то минуты показывает, то двоеточие, то температуру то есть как чеширский кот - то одно появится, то другое... В общем пару раз перевключишь и, вроде нормализуется всё... Это из за чего такое?

**Comment by vvip-68** [comment]
Неверно выбранная версия ядра микроконтроллера или неверно выбранная плата в настройках компиляции

**Comment by ACKET2009** [comment]
Всё, как по инструкции выбрано. Одна из плат Wemos D1 mini, другая NodeMCU, обе установлены, как  "NodeMCU 1.0(ESP-12E Module)" при компиляции, установки в скетче, соответственно выбрал под ESP8266...

**Comment by vvip-68** [comment]
Всё по инструкции, говорите?
Ну вот она причина то:

![image](https://user-images.githubusercontent.com/39353139/209455995-1c00410f-aade-4dd9-9f56-63427c8dbd81.png)

Читайте внимательно инструкцию!

**Comment by vvip-68** [comment]
![image](https://user-images.githubusercontent.com/39353139/209456058-44908af2-0164-4e81-a997-4a8ac8e90446.png)

**Comment by 7918514** [comment]
@ACKET2009 **Upload Speed** ставьте по максимуму - это значительно сократит время заливки прошивки в контроллер.
