### ISSUE TITLE
MQTT.BY

### ISSUE THREAD

**Issue by dimkacobra** [vvip-68/GyverPanelWiFi#264]
Брокер mqtt.by сломался. Поддержка говорит починит, но как скоро не ясно. Подскажите есть ли подобный аналог этому брокеру. А то смотрю по запросу Публичный mqtt брокер, а там либо не понятно, либо платно. Помогите пожалуйста.

**Comment by dimkacobra** [comment]
Решено. Модуль подключается, а сайт не работает.

**Comment by greeg38** [comment]
Подскажите новичку, не шарю в этом, через локальную сеть работает, а к mqtt.by не подключается. Зарегистрировался, создал топик, префиксы разные пробовал, не коннектится
