### ISSUE TITLE
Бегущая строка

### ISSUE THREAD

**Issue by Serg358** [vvip-68/GyverPanelWiFi#269]
Доброго времени суток. Нужна помощь знающих. В строке "ДО НОВОГО ГОДА ОСТАЛОСЬ{R31.12.2022 23:59:59}{B#000000}" не выводятся минуты, почему? Выводятся только остаток дней и часы "осталось 5 часов". Подскажите пожалуйста.

**Comment by vvip-68** [comment]
Стандартно минуты начинают выводиться за день до наступления события. Часы - за неделю. За час - еще и секунды.
Если вам нужно другое поведение - нужно пойти в runningText.ino и вот в этом месте написать то, как нужно вам.

![image](https://user-images.githubusercontent.com/39353139/209814185-dfaadcea-66fc-4ae6-9337-3655d440a227.png)
