### ISSUE TITLE
Прокрутка часов.

### ISSUE THREAD

**Issue by AxxiMator** [vvip-68/GyverPanelWiFi#27]
Здравствуйте.
Подскажите, пожалуйста, как отключить прокрутку часов.
Использую матрицу 20*15 - очень не удобно время наблюдать.

**Comment by AxxiMator** [comment]
Разобрался

**Comment by Pulsedriver** [comment]
@AxxiMator , здравствуйте! Не подскажите как реализовали? Разбираюсь, но пока не получается понять. Уверен, должно быть в приложении, но оно у меня как-то не всегда правильно реагирует на мои действия. Вернее матрица не всегда откликается на настройки в приложении.
