### ISSUE TITLE
Не меняется ip адрес

### ISSUE THREAD

**Issue by dmsergeevich63** [vvip-68/GyverPanelWiFi#276]
Не могу изменить IP адрес устройства, 192.168.0.100. Параметры на 24 и 26 строке не работают, постоянный IP в роутере для esp32 не задан, задаваемый IP свободен. Версия 1.13.
[a_def_soft.h.txt](https://github.com/vvip-68/GyverPanelWiFi/files/10954937/a_def_soft.h.txt)

**Comment by dmsergeevich63** [comment]
> Не могу изменить IP адрес устройства, 192.168.0.100. Параметры на 24 и 26 строке не работают, постоянный IP в роутере для esp32 не задан, задаваемый IP свободен. Версия 1.13. [a_def_soft.h.txt](https://github.com/vvip-68/GyverPanelWiFi/files/10954937/a_def_soft.h.txt)

**Comment by vvip-68** [comment]
Адрес настраивается либо из приложения, либо при заливке скетча на чистую (очищенную) плату микроконтроллера.
Для очистки платы выберите в параметрах компиляции скетча Инструменты - Erase Flash - Erase All Flash Content.
