### ISSUE TITLE
Ошибка компиляции 

### ISSUE THREAD

**Issue by Inthestep** [vvip-68/GyverPanelWiFi#282]
In file included from C:\Users\myUser\OneDrive\Рабочий стол\GyverPanelWiFi-master\firmware\GyverPanelWiFi_v1.13\a_def_hard.h:404,
                 from C:\Users\myUser\OneDrive\Рабочий стол\GyverPanelWiFi-master\firmware\GyverPanelWiFi_v1.13\GyverPanelWiFi_v1.13.ino:88:
C:\Users\myUser\OneDrive\���������\Arduino\libraries\ArduinoJson-6.x/ArduinoJson.h:5:10: fatal error: src/ArduinoJson.h: No such file or directory
    5 | #include "src/ArduinoJson.h"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

**Comment by Inthestep** [comment]
как скачать библиотеки 
hardwareserial и ArduinoJson
ПАМАГИТЕ!!!

**Comment by vvip-68** [comment]
Библиотеки нужно брать из папки проекта, так как скачанные из интернета могут иметь версии в которых изменено настолько, что проект не будет собираться.

hardwareserial - это не отдельная библиотека, это часть ядра микроконтроллера и идет вместе с ним.
ArduinoJson - находится в папке проекта 'libraries'

**Comment by Inthestep** [comment]
Спасибо!
