### ISSUE TITLE
Подключение к wifi panel?

### ISSUE THREAD

**Issue by romchik1982** [vvip-68/GyverPanelWiFi#284]
Здравствуйте! Уважаемый автор, помогите решить проблему с прошивкой! Сделал все по вашей инструкции! Лента пока ещё не подключена, в пути! Прошивку отредактировал, загрузил в esp ,  подключился сначала к точке доступа, затем назначил ip, оно перезагрузилось и все не подключается, хотя я создал новое подключение и указал назначенный ip адрес, в мониторе порта это все прописывается! Но подключаться не хочет! Может поможете разобраться?

**Comment by vvip-68** [comment]
1. Убедитесь что ваш роутер и устройство находятся в одной подсети и адрес шлюза Gateway правильно указан

https://github.com/vvip-68/LedPanelWiFi/wiki/FAQ#в-подскажите-что-не-так-c-подключением-через-точку-доступа-всё-исправно-работает-а-при-попытке-подключиться-к-локальной-сети-не-могу-законнектиться-через-приложение-в-чем-может-быть-проблема

2. В настройках роутера снимите галочку "Изоляция клиентов сети".
https://github.com/vvip-68/LedPanelWiFi/wiki/FAQ#в-устройство-подключается-к-сети-получает-адрес---это-видно-в-логах-телефон-к-устройству-подключается-в-приложении-ввожу-ip-адрес-полученный-устройством---тот-что-выводится-в-логе-но-соединение-не-происходит-что-я-делаю-не-так
