### ISSUE TITLE
Проблема при добавлении грузинского языка.

### ISSUE THREAD

**Issue by CrazyLazyMan** [vvip-68/GyverPanelWiFi#289]
Здравствуйте! Столкнулся с проблемой при добавлении грузинского языка, само собой все 33 символа отрисовал и добавил в массив fontHEX в файле fonts.h, но не знаю как отредактировать getFont в runningText.ino т.к. грузинские символы в utf-8 кодируются тремя байтами. Второй вопрос, не надо ли как то переделывать андроид приложение, т.к. после отправки грузинских символов на матрицу грузинский символ превращается в вопросительный вопрос в ромбе(см. скриншот). ESP32, матрица 16х16.
![Screenshot_2023-12-16-18-54-40-103_appinventor ai_vvip_phone GyverPanelWiFi](https://github.com/vvip-68/GyverPanelWiFi/assets/98008052/b8d68204-0685-433a-8cae-f6075a31f652)
Буду признателен за помощь.

**Comment by vvip-68** [comment]
Ну это вам много чего переписывать нужно. И сам алгоритм в getFont() для трех-байтового кодирования м много еще для чего. И не уверен, что приложение вообще поддерживает трехбайтовые символы. Так то там UTF-8, но, как говорится, есть нюансы. Всё это ох, как непросто будет... Не хотите попробовать версию 1.14 из соседнего проекта. Там по крайней мере все настройки в браузере - он то точно грузинский должен поддерживать. Тогда останется только перенести отрисованные символы в тот проект и переписать функцию получения шрифта и вывод на матрицу в скетче...

**Comment by CrazyLazyMan** [comment]
Спасибо за столь быстрый ответ. Мои худшие опасения подтвердились, с другой стороны, наверное все же перейду на 1.14.

**Comment by vvip-68** [comment]
Поздновато вы к Новому году готовиться начали... :)

**Comment by CrazyLazyMan** [comment]
У меня матрица на рюкзаке)
