### ISSUE TITLE
Ошибка 'workMode' was not declared in this scope

### ISSUE THREAD

**Issue by munstr** [vvip-68/GyverPanelWiFi#290]
Приветствую. Ничего не трогал и вдруг компилятор начал что то на рабов ругаться. Ядро 3.1.2. Wemos d1 mini

Вот фулл ошибка:
`
In file included from C:\Users\lsiba\OneDrive\Desktop\ARDUINO\LedPanelWiFi-main\firmware\LedPanelWiFi_v1.14\a_def_hard.h:502,
                 from C:\Users\lsiba\OneDrive\Desktop\ARDUINO\LedPanelWiFi-main\firmware\LedPanelWiFi_v1.14\LedPanelWiFi_v1.14.ino:185:
C:\Users\lsiba\OneDrive\Desktop\ARDUINO\LedPanelWiFi-main\firmware\LedPanelWiFi_v1.14\a_def_lang.h:41:6: warning: multi-character character constant [-Wmultichar]
   41 | #if (LANG == 'RUS')
      |      ^~~~
C:\Users\lsiba\OneDrive\Desktop\ARDUINO\LedPanelWiFi-main\firmware\LedPanelWiFi_v1.14\a_def_lang.h:41:14: warning: multi-character character constant [-Wmultichar]
   41 | #if (LANG == 'RUS')
      |              ^~~~~
C:\Users\lsiba\OneDrive\Desktop\ARDUINO\LedPanelWiFi-main\firmware\LedPanelWiFi_v1.14\a_def_lang.h:329:6: warning: multi-character character constant [-Wmultichar]
  329 | #if (LANG == 'ENG')
      |      ^~~~
C:\Users\lsiba\OneDrive\Desktop\ARDUINO\LedPanelWiFi-main\firmware\LedPanelWiFi_v1.14\a_def_lang.h:329:14: warning: multi-character character constant [-Wmultichar]
  329 | #if (LANG == 'ENG')
      |              ^~~~~
C:\Users\lsiba\OneDrive\Desktop\ARDUINO\LedPanelWiFi-main\firmware\LedPanelWiFi_v1.14\a_def_lang.h:618:6: warning: multi-character character constant [-Wmultichar]
  618 | #if (LANG == 'ESP')
      |      ^~~~
C:\Users\lsiba\OneDrive\Desktop\ARDUINO\LedPanelWiFi-main\firmware\LedPanelWiFi_v1.14\a_def_lang.h:618:14: warning: multi-character character constant [-Wmultichar]
  618 | #if (LANG == 'ESP')
      |              ^~~~~
In file included from C:\Users\lsiba\OneDrive\���������\Arduino\libraries\FastLED\src/FastLED.h:75,
                 from C:\Users\lsiba\OneDrive\Desktop\ARDUINO\LedPanelWiFi-main\firmware\LedPanelWiFi_v1.14\a_def_hard.h:528,
                 from C:\Users\lsiba\OneDrive\Desktop\ARDUINO\LedPanelWiFi-main\firmware\LedPanelWiFi_v1.14\LedPanelWiFi_v1.14.ino:185:
C:\Users\lsiba\OneDrive\���������\Arduino\libraries\FastLED\src/fastspi.h:157:23: note: '#pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output'
  157 | #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\lsiba\OneDrive\Desktop\ARDUINO\LedPanelWiFi-main\firmware\LedPanelWiFi_v1.14\a_main.ino: In function 'void process()':
a_main:435:24: error: 'workMode' was not declared in this scope
  435 |     if (isTurnedOff && workMode != SLAVE) {
      |                        ^~~~~~~~
a_main:435:36: error: 'SLAVE' was not declared in this scope; did you mean 'sSLAVE'?
  435 |     if (isTurnedOff && workMode != SLAVE) {
      |                                    ^~~~~
      |                                    sSLAVE
exit status 1
'workMode' was not declared in this scope
`

**Comment by vvip-68** [comment]
Минут 15 назад исправил это. Возьмите последнюю версию файла a_main.ino
Или внесите следующие изменения - должно помочь 

![image](https://github.com/vvip-68/GyverPanelWiFi/assets/39353139/82a07510-2b64-430c-aaf8-47339e92f167)

Ну или (все равно не используете E131 - прост удалите вот этот кусочек - '&& workMode != SLAVE'
