### ISSUE TITLE
Ошибки и непонятки

### ISSUE THREAD

**Issue by Cyxapuk11** [vvip-68/GyverPanelWiFi#297]
Не понимаю чего он от меня ждет (МК). Загрузил скетч для лед-панели, загрузка успешная, но wi-fi не появляется. Использую esp8266, пробовал по описанию разные версии ядра(?), поначалу и картинки не было вовсе. Сейчас воспроизводит случайные анимации в пин d2. 
Библиотека TM1637 из архива не распозналась, скачал наобум другую. Сейчас включается с рандомным эффектом на пине d2. Но wi-fi не появился, а в порту все еще происходит каша. 
/ Если написал не туда - извиняюсь, писал вроде в discuss, а записалось в issues

**Comment by vvip-68** [comment]
Ну в вашем случае проще всего все удалить и поставить заново, сделать всё по инструкции.
IDE брать 1.8.19

https://github.com/vvip-68/GyverPanelWiFi/wiki/Пошаговая-инструкция-подготовки-среды-для-проекта
https://github.com/vvip-68/GyverPanelWiFi/wiki/Всё-собрал,-ничего-не-работает.
https://github.com/vvip-68/GyverPanelWiFi/wiki/Настройка-скетча-для-вашего-устройства

**Comment by Cyxapuk11** [comment]
> Ну в вашем случае проще всего все удалить и поставить заново, сделать всё по инструкции. IDE брать 1.8.19
Переустановил IDE (как и был, на 1.8.19). Почистил "All flash contents", библиотеки не подключал вовсе, просто закинул в папку Arduino/lib. 
Картинка есть, точка доступа появилась, но называется PanelAP и запаролена. Как понимаю, по умолчанию зовется WiFiPanel и не запаролена? Или как подключаться к ней?

**Comment by Cyxapuk11** [comment]
> Ну в вашем случае проще всего все удалить и поставить заново, сделать всё по инструкции. IDE брать 1.8.19
Переустановил IDE той же 1.8.19, почистил память контроллеру и не добавлял библиотеки в скетч. 
Сейчас wi-fi появился, но приложение к нему не подключается. Телефон подключился с паролем 12341234, но приложение не хочет. Пробовал перезагрузить МК, переустановить приложение.

**Comment by vvip-68** [comment]
![image](https://github.com/vvip-68/GyverPanelWiFi/assets/39353139/3dc7330c-5942-4ed1-a797-92fbc5208912)

![image](https://github.com/vvip-68/GyverPanelWiFi/assets/39353139/72350062-e56b-446e-baff-6c194044daee)

**Comment by vvip-68** [comment]
Отключите на телефоне "Мобильные данные"

**Comment by Cyxapuk11** [comment]
Я не понимаю порядок подключений. Почитал FAQ и запутался только больше. МК подключается к роутеру И создает свою точку сразу? Или создает точку для связи с приложением, получает из приложения настройки и данные о роутере, и далее, при надобности переподключается к роутеру? 
Мне нужно было вводить данные о роутере во вкладке a_def_soft? Локальная сеть это мой роутер или МК? 

Мобильные данные не помогли, адрес моего роутера, как я понял, 192.168.100.1. Его сюда вставить надо?
![image](https://github.com/vvip-68/GyverPanelWiFi/assets/155484990/e3252c6a-2d86-4ef0-91e7-7d56d5380930)

В порт МК шлет подобного рода шифры (матрица сейчас воспроизводит эффекты, точка доступа есть):
![image](https://github.com/vvip-68/GyverPanelWiFi/assets/155484990/b6adf009-9147-4e5d-b2da-758655d4f27d)

**Comment by vvip-68** [comment]
Подключается ли матрица к роутере или нет - зависит от того указали ли вы в скетче (правильные) настройки сети или нет.
Если не указали - матрица не сможет подключиться к роутеру и создаст свою точку доступа.
Если матрица создала свою точку доступа и вы подключились к ней - можете из приложения настроить подключение матрицы к роутеру, задав имя сети и пароль к ней, а также IP адрес, который должно получить устройство после перезагрузки. Это самый простой путь, чтобы ]c его не прописывать в скетче.

**Comment by Cyxapuk11** [comment]
В скетче такого не видел и не менял, в настройках вижу только Upload speed из подходящего: 
![image](https://github.com/vvip-68/GyverPanelWiFi/assets/155484990/7ae676bc-388f-4f36-a52c-c3522f9a0324)

**Comment by vvip-68** [comment]
![image](https://github.com/vvip-68/GyverPanelWiFi/assets/39353139/78a0c715-7b8f-4329-b09b-9c91f901ccf3)

**Comment by Cyxapuk11** [comment]
Не помогло (настроил это и перезагрузил мк):
![image](https://github.com/vvip-68/GyverPanelWiFi/assets/155484990/6777613b-6804-4395-880b-6d78b3ef4646)

**Comment by vvip-68** [comment]
Значит у вас микроконтроллер не работает. Хотя, говорте, что вывод на матрицу есть...
Я с таким не сталкивался, не подскажу.

**Comment by Cyxapuk11** [comment]
Попробовал наугад остальные и нашел. Клал он на наши частоты, куда хочет - туда и шлет: 
![image](https://github.com/vvip-68/GyverPanelWiFi/assets/155484990/032f00c5-9ecc-461c-8815-9662fe9e6605)

**Comment by vvip-68** [comment]
Это скорость вывода при старте микроконтроллера, на которой он выводит начальные свои условия старта. Больше на этой скорости ничего не будет. Весь вывод из скетча идет на 115200
Если вывода не 115200 нет - всего два варианта - или микроконтроллер не стартует в режиме исполнения скетча, или в скетче в настройках параметров отключен отладочный вывод в монитор порта

**Comment by Cyxapuk11** [comment]
Перепрошил с дебагом (выключал когда ничего толком не работало т.к. думал что это именно на пины бесполезная по сути отладка). 
Вывод в порт заработал, а вместе с ним и успешно все подключилось в приложении с первой попытки. 
Извиняюсь за свои косяки и глупость, а вам огромное СПАСИБО за проявленное к идиоту терпение)
