### ISSUE TITLE
не получается прокинуть в интернет

### ISSUE THREAD

**Issue by MaxWh1t3** [vvip-68/GyverPanelWiFi#299]
не получается прокинуть управление матрицей в инет через keenetic cloud, порт прописан в коде, на роутере все настроено как положено. При переходе по ссылке открывается только страница с надписью Подключение и возможностью поменять тему (черная/белая). При этом с такими же настройками роутера работает Home Assistant и WLED, могу управлять через интернет. Хотел MQTT подключить, но в последней версии прошивки его почему-то вырезали... Из браузера матрица управляется

**Comment by vvip-68** [comment]
Я устал уже объяснять, что это работать не будет и почему не будет, и почему выкинут MQTT
Примите как данность...

**Comment by MaxWh1t3** [comment]
окау(
