### ISSUE TITLE
Не работает текстовая строка

### ISSUE THREAD

**Issue by werwolf68** [vvip-68/GyverPanelWiFi#30]
Добрый день!
Через приложение добавляю фразы для бегущей строки. 
Если на вкладке текст нажимаю просмотр, все работает. Через отжим демо - нет. Подскажите, в чем может быть проблема?

**Comment by vvip-68** [comment]
Например на вкладке настройки текстовых строк не поставлена галка  "Текст поверх эффектов". 
Или интервал показа текстовых строк установлен большим и не успевает истечь, когда вам надоедает ждать появления строки (например интервал указан - "каждые в 600 секунд", а вы ожидаете только 300 секунд, потом вам надоедает ждать.
Или для (каждого) эффекта в его настройках на закладке "Эффект" не стоит галка, разрешающая отображать бегущую строку

**Comment by werwolf68** [comment]
Да, действительно вы правы. 
Я отключил наложение на эффекты и в настройках отключил все галочки. (По моему мнению с эффектам текст смотрится ужасно, но решил эту особенность черным фоном). Всё сейчас отлично работает.
Огромное Вам спасибо за такой классный и большой проект.

**Comment by werwolf68** [comment]
Добрый вечер. Ваш совет помог. Огромное Вам спасибо!Могу ли я Вас материально отблагодарить? Каким способом?Для меня предпочтительнее карта visa/mastercard21:21, 22 ноября 2020 г., "vvip-68" <notifications@github.com>:
Например на вкладке настройки текстовых строк не поставлена галка  "Текст поверх эффектов".
Или интервал показа текстовых строк установлен большим и не успевает истечь, когда вам надоедает ждать появления строки (например интервал указан - "каждые в 600 секунд", а вы ожидаете только 300 секунд, потом вам надоедает ждать.
Или для (каждого) эффекта в его настройках на закладке "Эффект" не стоит галка, разрешающая отображать бегущую строку

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by vvip-68** [comment]
Чтобы текст поверх эффектов не сливался с фоном эффекта - у каждого эффекта есть настройка "контрастность" - это яркость эффекта относительно яркости текста / часов. Можно подобрать такую яркость, что текст будет достаточно хорошо читаться на фоне эффекта. Черный фон, конечно, тоже выход...
Ну, если есть желание - кинь чего-нибудь на карту сбербанк/виза 4276 31000 2491 1960

**Comment by werwolf68** [comment]
Спасибо за объяснение, контрастность не думал что так работает здесь.А в номере карты нет ли у вас ошибки?Возможно в второй группе цифр лишний 0?Или номер правильный?21:58, 22 ноября 2020 г., "vvip-68" <notifications@github.com>:
Чтобы текст поверх эффектов не сливался с фоном эффекта - у каждого эффекта есть настройка "контрастность" - это яркость эффекта относительно яркости текста / часов. Можно подобрать такую яркость, что текст будет достаточно хорошо читаться на фоне эффекта. Черный фон, конечно, тоже выход...
Ну, если есть желание - кинь чего-нибудь на карту сбербанк/виза 4276 31000 2491 1960

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by vvip-68** [comment]
Я, вроде исправил в сообщении выше - 4276 3100 2491 1960

**Comment by vvip-68** [comment]
Спасибо!

**Comment by 247760** [comment]
Вопрос по тексту и макросам. Для проверки, я скопировал и вставил в окно приложения готовый макрос 
До Нового года осталось {P01.01.****#E#60#60}
-С Новым годом!!!!
Но **COM** порт мне пишет в ответ:
17:55:01.171 -> --------------------
17:55:01.171 -> Строки с событием {P}
17:55:01.171 -> --------------------
17:55:01.205 -> Строка: 'До Нового года осталось {P01.01.****#E#60#60}  -С Новым годом!!!!'
17:55:01.205 -> 
17:55:01.205 -> Ошибка в макросе '{P01.01.****#E#60#60}'
17:55:01.205 -> -------------^
17:55:01.205 -> --------------------

На данную минут, вообще не понимаю структуру написания макросов (но это моя проблема), хотелось бы на одном примере всё разобрать.

**Comment by vvip-68** [comment]
Поизучайте пока другие макросы. Я пока посмотрю что с этим пошло не так...

**Comment by werwolf68** [comment]
Добрый вечер. Я думаю это письмо адресовано не мне17:57, 2 декабря 2020 г., 247760 <notifications@github.com>:
Вопрос по тексту и макросам. Для проверки, я скопировал и вставил в окно приложения готовый макрос
До Нового года осталось {P01.01.****#E#60#60}
-С Новым годом!!!!
Но COM порт мне пишет в ответ:
17:55:01.171 -> --------------------
17:55:01.171 -> Строки с событием {P}
17:55:01.171 -> --------------------
17:55:01.205 -> Строка: 'До Нового года осталось {P01.01.#E#60#60}  -С Новым годом!!!!'
17:55:01.205 ->
17:55:01.205 -> Ошибка в макросе '{P01.01.#E#60#60}'
17:55:01.205 -> -------------^
17:55:01.205 -> --------------------
На данную минут, вообще не понимаю структуру написания макросов (но это моя проблема), хотелось бы на одном примере всё разобрать.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by 247760** [comment]
@werwolf68  я написал автору тут, чтобы не открывать новые вкладки с вопросами.

**Comment by vvip-68** [comment]
@werwolf68, да это в вашей теме (issue #30) хулиганит (задает вопросы) @247760 - ему и был ответ.
Ну, а гитхап естественно рассылает всем, кто в теме уведомления

**Comment by vvip-68** [comment]
@247760 - я исправил. Странно, что и я и другие пользователи этот макрос проверяли и ведь он работал... Как и когда ошибка закралась? Чудеса...
