### ISSUE TITLE
Нет возможности прописать доступ к Wi-Fi сети

### ISSUE THREAD

**Issue by khusamov** [vvip-68/GyverPanelWiFi#302]
Версия приложения - 1.12.2021.1026

Как попасть на эту страницу в приложении?
![image](https://github.com/vvip-68/GyverPanelWiFi/assets/4146998/cba7b256-f5c2-421f-a286-cd68d04edf72)

Дело в том, что у меня нет этих двух кнопок:
![image](https://github.com/vvip-68/GyverPanelWiFi/assets/4146998/ec2be32a-1d7b-4d14-99b5-2b1774e9ce5e)

Остальные кнопки есть, даже больше чем на первом скриншоте. Но нужной кнопки нету. Как быть?

**Comment by vvip-68** [comment]
Установить соответственно другое приложение для настройки, где эти кнопки есть.

**Comment by khusamov** [comment]
@vvip-68 А другого же нету.
Я установил эту:

> Найдите в папке проекта Android/AppInventor файл приложения PanelSetupWiFi.apk и установите его на ваш смартфон. Запустите приложение.

**Comment by khusamov** [comment]
@vvip-68 Спасибо! Понял где косяк))

**Comment by vvip-68** [comment]
Ну вот в этом приложении эти кнопки и есть.
А что у вас в этом приложении?

  
>Понедельник, 18 марта 2024, 22:44 +07:00 от Khusamov Sukhrob ***@***.***>:
> 
> 
>@vvip-68 А другого же нету.
>Я установил эту:
>>Найдите в папке проекта Android/AppInventor файл приложения PanelSetupWiFi.apk и установите его на ваш смартфон. Запустите приложение.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you were mentioned. Message ID:  <vvip-68/GyverPanelWiFi/issues/302/2004270179 @ github . com> 
 
 
С уважением,
Вадим Пузанов

**Comment by vvip-68** [comment]
Ну, ок
