### ISSUE TITLE
Погода от Яндекс

### ISSUE THREAD

**Issue by Aleks000777999** [vvip-68/GyverPanelWiFi#307]
Здравствуйте. Не работает погода от яндекс. Установил последнюю версию WiFi-Panel-v1.13 released this Mar 4, 2023. Ткните носом где, что нужно исправить, прописать, или еще какие действия. Читал, что исправлено, но в этой версии не работает. Заранее спасибо.

**Comment by vvip-68** [comment]
Исправлено. Подтверждаю. У всех, с кем я общался -  вроде работает....
Интересно про " released this Mar 4, 2023"... 
Последняя версия с исправлениями по яндексу выложена 31.10.2024...

**Comment by Aleks000777999** [comment]
Извините, я не очень силен в этом. Дайте пожалуйста ссылку на последнюю версию с исправлениями.

**Comment by vvip-68** [comment]
https://github.com/vvip-68/GyverPanelWiFi/wiki/FAQ
Первый же вопрос-ответ

**Comment by Aleks000777999** [comment]
Спасибо. Пробую.

**Comment by Aleks000777999** [comment]
ОГРОМНОЕ СПАСИБО. Работает.

**Comment by Aleks000777999** [comment]
Доброго времени. Побеспокою еще раз, с другим вопросом. Хотелось посмотреть как будет выглядеть анимация марио на моей матрице, размер 20х15. Но в списке не отображается марио и погода в приложении, знаю что нужна матрица 16х16. Но все же хотелось посмотреть. Был такой вопрос здесь, Вы отвечали человеку. Не могли бы Вы объяснить что именно нужно поправить в скетче во вкладке анимация, что бы появился весь список.  Вот Ваш скрин на тот вопрос
![Screenshot_333](https://github.com/user-attachments/assets/95b863c6-eeeb-4b99-87a4-8abe9b98002e)

**Comment by vvip-68** [comment]
Вот вообще не помню как там и что...
Обведенная рамкой конструкция говорит, что добавлять анимацию в список отображаемых нужно только когда ее размер (ширина, высота анимации) меньше или равна ширине и высоте матрицы соответственно...

Хотите посмотреть - отключите эту проверку вообще - ну то есть закомментируйте строки 120 и 125 что на этом скриншоте - тогда проверок вообще выполняться не будет - попадут все в список.

**Comment by Aleks000777999** [comment]
Спасибо, я и имел ввиду убрать проверку. Вот еще бы знать как это сделать -(закомментируйте строки 120 и 125) ??? Извините я не программист...

**Comment by vvip-68** [comment]
Можете вообще удалить эти две строки.
Но если попробовать, а потом вернут обратно - поставьте в начале каждой строки по две косых черты - //

**Comment by Aleks000777999** [comment]
Спасибо пробую.

**Comment by Aleks000777999** [comment]
Спасибо, получилось. УДАЧИ ВАМ !!!
