### ISSUE TITLE
error in firmware

### ISSUE THREAD

**Issue by matteos1** [vvip-68/GyverPanelWiFi#35]
#include "a_def_pass.h"     // приватные данные и пароли доступа к серверу MQTT

GyverPanelWiFi_v1.07:37:117: fatal error: a_def_pass.h: No such file or directory
 #include "a_def_pass.h"     // приватные данные и пароли доступа к серверу MQTT
                                                                                                                     ^
compilation terminated.
exit status 1
a_def_pass.h: No such file or directory

**Comment by vvip-68** [comment]
Пробуем не тупо нажимать на кнопку "Загрузить" в Ардуино IDE, а читать хотя бы 5 строчек комментариев до указанного места ошибки, тем более, что это всё в самом начале файла, "крупными буквами".
