### ISSUE TITLE
Форма панели

### ISSUE THREAD

**Issue by Michael-79** [vvip-68/GyverPanelWiFi#38]
Добрый день! Выражаю огромную благодарность автору!
Собираю гирлянду на окно. Возник один вопрос. Расстояние между светодиодами - 40 мм. Окно состоит из двух рам. Ширина импоста - 200 мм. Соответственно некоторые эффекты будут отображаться некорректно. Возможно ли как-то это предусмотреть?
![led](https://user-images.githubusercontent.com/75234191/100567281-f12da000-32e9-11eb-90e2-c0a7a7198783.jpg)

**Comment by vvip-68** [comment]
У меня нет идей.

**Comment by 247760** [comment]
Очень уж плотно у Вас всё. В этом моменте с разрывом выход один, делать это расстояние (можно на пару см меньше) между светодиодами, иначе Ваша гирлянда будет выглядеть более менее цельно, с учётом разрыв, на расстоянии минимум 100 метров, а то более.
