### ISSUE TITLE
Предложение №2 

### ISSUE THREAD

**Issue by 80Stepko08** [vvip-68/GyverPanelWiFi#4]
Есть такая штука, как субпиксель, на форуме https://community.alexgyver.ru/threads/wifi-lampa-budilnik-proshivka-firelamp_jeeui-gpl.2739/ Он делает эффект плавнее и красивее

**Comment by vvip-68** [comment]
Что-то по приведенной ссылке ничего конкретного не нашел, а перечитывать все 128 страниц темы - как-то не особо...

**Comment by 80Stepko08** [comment]
https://github.com/DmytroKorniienko/FireLamp_JeeUI/tree/dev

**Comment by vvip-68** [comment]
Посмотрел. Утянул процедуры отрисовки субпиксельной графики. На будущее.
Пока же у меня я не вижу куда это применить. Часть эффектов исходной лампы где это используется у меня отсутствует.
Часть эффектов что у меня есть и я видел на роликах в форуме как они выглядят с субпикселями (те же стрелки) - мне не нравится такой вариант. К тому же именно пиксельность придает некоторый шарм, от которого мне не хотелось бы избавляться. Но за идею - спасибо.
