### ISSUE TITLE
Бегущая строка в определенные дни.

### ISSUE THREAD

**Issue by CrazyGhostRider** [vvip-68/GyverPanelWiFi#42]
Здравствуйте.
Что-то я никак не могу понять. Как сделать так, чтобы бегущая строка "С Рождеством" включалась только 7 января?

**Comment by vvip-68** [comment]
В текущей версии нет такого функционала.
Нужно написать новый макрос (разновидность/микс макросов {P} и {R}) и запрограммировать, чтобы строка показывалась тольк в определенную дату.

**Comment by vvip-68** [comment]
@CrazyGhostRider, я добавил макрос бегущей строки {S} - показывать строку в определенные даты.

**Comment by CrazyGhostRider** [comment]
Огромное спасибо!!!
