### ISSUE TITLE
Погода (выбор в приложении)

### ISSUE THREAD

**Issue by fastdron** [vvip-68/GyverPanelWiFi#45]
В приложении не появились пункты выбора поставщика погоды. Скачал последние обновления. В чем может быть дело? 
![Screenshot_2020-12-04-14-14-15-265_com vvip_phone GyverPanelWiFi](https://user-images.githubusercontent.com/51260579/101162626-41369a80-363b-11eb-8d38-5f2a3bddc6a6.jpg)

**Comment by vvip-68** [comment]
Полагаю, что вы установили приложение не из той папки, старую версию.
Об этом говорит хотя бы Switch - ручной - демо. В новой версии такого свича нет - там чекбокс.

**Comment by fastdron** [comment]
Перекачать ещё раз. Сбился ip адресс панели, поправил и все появилось. Спасибо
