### ISSUE TITLE
Ох уж этот WIFI

### ISSUE THREAD

**Issue by AkmonLS** [vvip-68/GyverPanelWiFi#46]
Прошивка 
GyverPanelWiFi
плата Wemos (прошивал как положено, да и как не положено тоже пробовал)

Проблема: плата работает(в режиме точка доступа), но стоит подключиться к роутеру(а подключение проходит норм, пингуется с командной строки винды даже), приложение смартфона упорно не хочет подключаться.

**Comment by vvip-68** [comment]
Что делаете для подключения со смартфона? Подробности по шагам.
Какой адрес получает плата в сети? Нет ли в сети другого устройства с таким же адресом?

**Comment by vvip-68** [comment]
Из личного опыта. Пришел в сеть, Ноутбук с которого прошивал плату. Задал плате адрес 192.168.0.100. В логе вижу что загружается, подключается к роутеру, а из приложения к плате подключится - никак. Потом выяснилось, что ноут регистрируясь в сети тоже получил адрес 192.168.0.100

**Comment by AkmonLS** [comment]
Залил прошивку, подключился к точке доступа Panel, зашел в приложение подсоединился к панели, прописал в настройках имя WiFi и пароль.
Монитор порта включен и он отображает что соединение с моим домашним вайфай установлено. адрес 192.168.1.135 (в настройках роутера по MAC адресу зафиксил его, чтобы он один и тот же адрес всегда подключал)
на этом адресе болльше никого нет.
Захожу опять в приложение(уже будучи подключенный к домашнему вифи) ввожу адрес 192.168.1.135 не подключается.
Однако через комп: ping -a 192.168.1.135 пакеты летают!!

**Comment by AkmonLS** [comment]
13:25:09.203 -> LED-Panel-WiFi v.1.07.2020.1130
13:25:09.203 -> 
13:25:09.203 -> Загрузка строк выполнена.
13:25:09.249 -> Ипользованы адреса EEPROM 800 - 837
13:25:09.249 -> Свободно ячеек 3258
13:25:09.249 -> 
13:25:09.249 -> Инициализация SD-карты...
13:25:09.436 -> SD-карта недоступна
13:25:09.529 -> 
13:25:09.529 -> Подключение к Akmon
13:25:09.622 -> .............
13:25:13.676 -> WiFi подключен. IP адрес: 192.168.1.135
13:25:13.676 -> 
13:25:13.676 -> UDP-сервер на порту 2390
13:25:13.676 -> 
13:25:13.676 -> Подключаемся к MQTT-серверу 'srv1.clusterfly.ru:9123'; ClientID -> 'WiFiPanel-3' ....NTP-сервер ru.pool.ntp.org -> 91.207.136.50
13:25:13.767 -> Отправка NTP пакета на сервер ru.pool.ntp.org
13:25:13.814 -> UDP << ip='91.207.136.50:123'; ntp sync
13:25:13.814 -> UDP пакeт размером 48
13:25:13.814 -> Разбор пакета NTP
13:25:13.814 -> Секунд с 1970: 1607189113
13:25:13.814 -> Текущее время: 05.12.2020 17:25:13
13:25:13.814 -> --------------------
13:25:16.231 -> ...................

**Comment by vvip-68** [comment]
А у вас реально MQTT используется и настроен?
Я вижу что он не может подключиться к MQTT.
При этом каждая попытка подключения блокирует прочую передачу по канала на время пока не отвалится по таймауту.
Вероятнее всего поэтому пакеты с вашего телефона даже не доходят до платки - все ресурсы канала занимаются попытками подключиться к MQTT серверу

**Comment by AkmonLS** [comment]
LED-Panel-WiFi v.1.07.2020.1130

Загрузка строк выполнена.
Ипользованы адреса EEPROM 800 - 837
Свободно ячеек 3258

Подключение к Akmon
.............
WiFi подключен. IP адрес: 192.168.1.135

UDP-сервер на порту 2390
Режим: 'Тетрис'
NTP-сервер ru.pool.ntp.org -> 128.0.142.251
Отправка NTP пакета на сервер ru.pool.ntp.org
UDP << ip='128.0.142.251:123'; ntp sync
UDP пакeт размером 48
Разбор пакета NTP
Секунд с 1970: 1607189596
Текущее время: 05.12.2020 17:33:16
--------------------
Режим: 'The Matrix'
Режим: 'Радужные переливы'
Режим: 'Тетрис'
Режим: 'Арканоид'
Режим: 'Смена цвета'

**Comment by vvip-68** [comment]
И?

**Comment by AkmonLS** [comment]
оключил и все так же не подсоединяется, но по прежнему пингуется с компа

**Comment by vvip-68** [comment]
Тогда у меня больше нет идей

**Comment by AkmonLS** [comment]
![2020-12-05_13-41-18](https://user-images.githubusercontent.com/75522504/101240324-b23f8600-36ff-11eb-8cc9-2ae949c01625.png)

**Comment by AkmonLS** [comment]
с прошивкой Gyver**Matrix**WiFi такая же петрушка....

**Comment by vvip-68** [comment]
Значит дело в телефоне. Есть возможность другой телефон попробовать?
Есть возможность с телефона попинговать?

**Comment by AkmonLS** [comment]
Сейчас буду пробовать другой телефон и прошивки apk так как не пингуется(((

**Comment by vvip-68** [comment]
А если не телефоне в этот момент отключить Мобильные данные?

**Comment by AkmonLS** [comment]
они отключены, но роутер и компьютер пингуются с телефона

**Comment by vvip-68** [comment]
И микроконтроллер тоже пингуется с телефона?

**Comment by AkmonLS** [comment]
Нет микроконтроллер не пингуется с телефона почему то!

**Comment by vvip-68** [comment]
Может у вас на телефоне какой-нибудь прокси или VPN стоит?

**Comment by AkmonLS** [comment]
нет, ничего нет, остальные "абоненты" вай фая и локальной сети с телефона пингуются то! а именно микроконтролеер нет.
Зато микроконтролеер прекрасно виден из роутера и ПК.

**Comment by vvip-68** [comment]
Я не знаю причину, но следствие очевидно - пока микроконтроллер не будет виден с телефона - программа не сможет к нему подключиться. Попробуйте сбросить микроконтроллер, чтобы он снова подключался в режиме точки доступа, потом зайдя в программу заново прописать параметры подключения задав другой адрес (не 135) в поле явным образом. И снова пробовать

**Comment by vvip-68** [comment]
А у вас роутер в сети имеет какой адрес? 192.168.1.1 ? Или 192.168.1.100?

**Comment by AkmonLS** [comment]
192.168.1.1

**Comment by vvip-68** [comment]
И все же проверьте - если выключить микроконтроллер - он перестанет пинговаться с компа? Может все же второе устройство с таким адресом? Может телевизор какой...

**Comment by AkmonLS** [comment]
Что очень кстати примечательно у меня дома есть вайфай разетка магазинная она работает, все норм(ESP_FC0CB4  так видит ее роутер), но с телефона она так же не пингуется а с компа пингуется

**Comment by AkmonLS** [comment]
> И все же проверьте - если выключить микроконтроллер - он перестанет пинговаться с компа? Может все же второе устройство с таким адресом? Может телевизор какой...

да если отключить микроконтролеер он перестает пинговаться с компа

**Comment by vvip-68** [comment]
С другим телефоном - ничего не поменялось?

**Comment by vvip-68** [comment]
Телефон - не Xiaomi? Именно они по отзывам пользователей часто чудят почему-то...

**Comment by AkmonLS** [comment]
Нет телефона 2 и оба самсунг, щас попробую со старого Хонора

**Comment by vvip-68** [comment]
А розетка чем управляется? Программой на телефоне? И управляется?

**Comment by AkmonLS** [comment]
> А розетка чем управляется? Программой на телефоне? И управляется?

Да прогой с телефона, и все работает, но к ней доступ есть и глобального интернета, я думаю что там обмен информации организован не на прямую через локальную сеть а через сервера. поэтому не показатель...

**Comment by AkmonLS** [comment]
> Нет телефона 2 и оба самсунг, щас попробую со старого Хонора

ну увы с хонора тоже не пингуется ни розетка ни микроконтроллер, больше телефонов нет(((

**Comment by vvip-68** [comment]
а на телефоне кроме ping возможность есть аналога виндовой команды tracert - посмотреть куда они пакеты отправляют?

**Comment by vvip-68** [comment]
На роутере нет никакой настройки куда отправлять пакеты? Может он получив с телефона отправляет не в свою сеть, а куда-нибудь в интернет? Может на роутере чего настроить нужно?

**Comment by vvip-68** [comment]
Другого роутера нет попробовать?

**Comment by AkmonLS** [comment]
> а на телефоне кроме ping возможность есть аналога виндовой команды tracert - посмотреть куда они пакеты отправляют?

не нашел(



> На роутере нет никакой настройки куда отправлять пакеты? Может он получив с телефона отправляет не в свою сеть, а куда-нибудь в интернет? Может на роутере чего настроить нужно?

маршруты никакие на роутере не натроены, можно попробовать пробросить порты, например обращаясь к роутеру по порту UTP 2390  перенаправлять к микроконтроллеру.... надо изучать как это делать



> Другого роутера нет попробова

нужно поискать где то был старенький D-link

**Comment by AkmonLS** [comment]
**Все проблема решена!!**
Итог в настройках роутера нужно отключить "изоляцию точки доступа" - она включена по умолчанию!!!
эта опция запрещает напрямую общаться только вайфай клиентам!Хотя она странно работает скрывало только ESP модули от других устройств, а телевизоры и прочаяя техника(телеки, смартфоны и т.д.) вифи попрежнему пинговала друг друга.

Надеюсь это кому-нибудь еще поможет

**Comment by vvip-68** [comment]
Спасибо за информацию.

**Comment by vvip-68** [comment]
А что за модель роутера то?

**Comment by AkmonLS** [comment]
Asus RT-AC58U
