### ISSUE TITLE
Приложение на IOS

### ISSUE THREAD

**Issue by huskydogsmile** [vvip-68/GyverPanelWiFi#48]
Добрый день, спасибо за проект! Подскажите пожалуйста, планируется-ли выпуск приложения на IOS? И можно-ли через веб интерфейс управлять?

**Comment by vvip-68** [comment]
Нет, не планируется.
Через Web-интерфейс тоже управлять нельзя - никто не написал такого функционала. Да и не нужно особо никому. Одному из сотни.

**Comment by huskydogsmile** [comment]
Печально, придется клянчить у кого ни будь android. Успехов Вам в развитии проекта.
