### ISSUE TITLE
Помогите, подскажите

### ISSUE THREAD

**Issue by badbear1987** [vvip-68/GyverPanelWiFi#49]
Здравствуйте. У меня на плате nodemcu v3. При установке времени автоматического переключения времени с 1-11секунд все норм. 12 и выше гирлянда висит на одном из выбранных режимах( не переключает) температура в помещении около +10°С. Как можно исправить? Память переполнена ? (Хотя при компиляции всего 50%) или холодно плате и кварц гонит? Матрица 24х10

**Comment by vvip-68** [comment]
Не знаю. Вряд ли память и температура. У меня на балконе гирлянда 50x20 при температуре -15 прям сейчас исправно работает. Могу только предложить обновить версию прошивки до последней. У меня такого не наблюдается.

**Comment by jdc85** [comment]
Возможно ли получить ссылку на проект?

**Comment by vvip-68** [comment]
А как вы сюда пишете, если у вас нет ссылки на проект?
 
https://github.com/vvip-68/GyverPanelWiFi
  
>Вторник, 8 декабря 2020, 5:13 +07:00 от jdc85 <notifications@github.com>:
> 
> 
>Возможно ли получить ссылку на проект?
>—
>You are receiving this because you modified the open/close state.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением,
Вадим Пузанов

**Comment by badbear1987** [comment]
Вместо тетриса может игру гонки?))) На что была на тетриса. Только не по
вертикали а по горизонтали.
Я слаб в этом плане программирования (((

вт, 8 дек. 2020 г., 6:12 vvip-68 <notifications@github.com>:

**Comment by vvip-68** [comment]
> Я слаб в этом плане программирования (((

Можно. Но если слаб в программировании - то заказы (за деньги) принимаются на сайте Гайвера в разделе "Ищу разработчика" - https://community.alexgyver.ru/forums/ischu-razrabotchika-ispolnitelja.21/

Там сформулируете техническое задание, договоритесь об оплате, вам сделают.
