### ISSUE TITLE
 Проблема ArduinoOTA.setHostname(host_name.c_str())

### ISSUE THREAD

**Issue by jdc85** [vvip-68/GyverPanelWiFi#51]
Добрый вечер. Скажите с чем может быть проблема призагрузке скетча версии 1.07  'class ArduinoOTAMdnsClass<WiFiServer, WiFiClient, WiFiUDP>' has no member named 'setHostname'
и выделяет эту строку ArduinoOTA.setHostname(host_name.c_str())

**Comment by vvip-68** [comment]
1. Старая версия библиотек
2. Старая версия ядра
3. Старая версия Arduino IDE

**Comment by vvip-68** [comment]
4. Выбрана не та плата в настройках сборки

**Comment by jdc85** [comment]
Wemos d1 mini. Только не esp12 модуль, а esp8266. Какую в таком случае выбирать. Библиотеки все с раздачи сегодня скачал с Вашего архива. Очень благодарен Вам за помощь!

**Comment by vvip-68** [comment]
Я выбираю NodeMCU v1.0 - с этим глюков не замечено, хотя реально платка Wemos d1 mini
Кроме библиотек еще причина может быть в версии IDE и в версии ядраESP8266

**Comment by jdc85** [comment]
Скорей всего в. IDE давно не обновлял. Попробую, отпишусь. Может у кого-то возникнет вопрос. Почитает и расставит точки.

**Comment by jdc85** [comment]
Всё получилось. Проблема была в версии IDE как Вы и говорили. Есть вопрос, немного не в этом посте-как согласовать 12 вольтовую ленту? Тоже адресная.  А RGB меняется. Здается в моем случае не совпадает, надо изменить вместо красного зелёный. Спасибо

**Comment by vvip-68** [comment]
Так при инициализации же ленты указывается ее тип и порядок цветов

 FastLED.addLeds<WS2812, LED_PIN, **COLOR_ORDER**>(leds, NUM_LEDS).setCorrection( TypicalLEDStrip );

где

```#define COLOR_ORDER GRB          // порядок цветов на ленте. Если цвет отображается некорректно - меняйте. Начать можно с RGB```

**Comment by citypeople** [comment]
Подобная беда с NodeMCU v3, пытаюсь разобраться, но тщетно. Буду раз если есть какие-то соображения по этому поводу.

**Comment by vvip-68** [comment]
Вероятно подобная беда решается подобными же методами, что описаны выше...

**Comment by citypeople** [comment]
Да дело в том что уже удалял ide, чистил все libs которые могли быть на ПК, дело сдвинулось и теперь встал на
'class ArduinoOTAClass' has no member named 'getCommand'

**Comment by vvip-68** [comment]
1. Какая версия библиотеки ArduinoOTA используется?
2. Какая плата выбрана в настройках компиляции в Arduino IDE?

**Comment by vvip-68** [comment]
Точнее - вопрос неправильный - т.к. в данном случае ArduinoOTA - часть ядра esp8266 - какая версия ядра ESP8266 используется?

**Comment by citypeople** [comment]
1.  1.0.5
2. NodeMCU  1.0 (ESP-12E Module)

**Comment by citypeople** [comment]
Ядро пробовал 2.2.0 и 2.3.0

**Comment by vvip-68** [comment]
Ну так видимо поэтому и не работает. Текущая версия ядра - 2.7.4

**Comment by citypeople** [comment]
Спасибо пробую, вот даже мысли не было посмотреть последнюю версию, брал ссылку из интернетов на json

**Comment by vvip-68** [comment]
Так менеджер устройств по этой ссылке json и берет актуальную версию м Arsuino IDE - менеджер плат

**Comment by citypeople** [comment]
Уже компилится. И вроде все удачно, спасибо за отзывчивость и быстрые ответы.
