### ISSUE TITLE
Бегущая строка низ головой 

### ISSUE THREAD

**Issue by 19Andrey** [vvip-68/GyverPanelWiFi#55]
Добрый день, у меня текст бегущей строки идёт низ головой, подскажите как поправить

**Comment by vvip-68** [comment]
Указать правильно угол подключения матрицы и направление из угла

**Comment by 19Andrey** [comment]
В прошивке у меня часы показывают нормально, в матрицу выводит  нормально, а вот когда текст в программе пишу идёт низ головой, подскажите где менять угол матрицы в программе на телефоне что бы текст шёл нормально

**Comment by vvip-68** [comment]
У меня нет ответа. Я не знаю как добиться, чтобы часы шли нормально, а текст вниз головой. По-моему в прошивке вообще это не предусмотрено. Возьмите с хранилища прошивку, измените только размер матрицы и угол подключения. Залейте ее в микроконтроллер и убедитесь что часы и текст отображаются одинаково. Потом вносите свои изменения дальше и смотрите какое из них приводит к эффекту как у вас. Программа на телефоне вообще не имеет никаких настроек ориентации текста.
