### ISSUE TITLE
Неправильное отображение цветов

### ISSUE THREAD

**Issue by mihasik22** [vvip-68/GyverPanelWiFi#64]
Собрал матрицу на nodemcu и ws2811, загрузил последнюю прошивку, все работает но не пойму где ошибка: Красный цвет отображается зеленым, а зеленый соответственно красным. Т.е "огонь" - салатовый, а "матрица" - красная.
Подскажите пожалуйста что и где нужно поправить?

**Comment by vvip-68** [comment]
в a_def_soft.h
`#define COLOR_ORDER **GRB**          // порядок цветов на ленте. Если цвет отображается некорректно - меняйте. Начать можно с RGB`

в setup()
  // Настройки ленты
  `FastLED.addLeds<WS2812, LED_PIN, **COLOR_ORDER**>(leds, NUM_LEDS).setCorrection( TypicalLEDStrip );`
