### ISSUE TITLE
Ошибка компиляции: 'fadeMode' was not declared in this scope

### ISSUE THREAD

**Issue by vitali000** [vvip-68/GyverPanelWiFi#68]
Привет! Спасибо за проект!!!!
Если задать #define  SMOOTH_CHANGE  в 1 то компиляция вываливается с ошибкой
'fadeMode' was not declared in this scope
помогает если вот этот IF

#if (SMOOTH_CHANGE == 1)
  byte fadeMode = 4;                        // Фаза режима плавной смены эффекта
  boolean modeDir;                          // Направление перехода к следующему / предыдущему режиму
#endif

перенести ниже
этого #define  SMOOTH_CHANGE 1                    // плавная смена режимов через чёрный

**Comment by vvip-68** [comment]
О, да. Спасибо что заметили.
Это какой-то рудимент, оставшийся с самых первых версий от Гайвера до всех переделок.
Никогда не использовался. Оно хоть работает вообще, эта плавная смена? С ней всегда были какие-то проблемы, насколько я помню... Убрать его, что ли...
