### ISSUE TITLE
Бегущая строка

### ISSUE THREAD

**Issue by vikn72** [vvip-68/GyverPanelWiFi#69]
Неработает в приложении на андроид бегущая строка, макросы невозможно настроить от слова совсем не работают, Пытался пошивал несколько раз со стиранием предыдущей прошивки и ничего не помогло. контролер Wemos D1 mini . Всё остальное работает хорошо, с флешки всё читается. как починить бегущую строку с макросами? Сохранить написаный макрос невозможно
![Screenshot_20201221_011046_com vvip_phone GyverPanelWiFi](https://user-images.githubusercontent.com/57089500/102743244-1c933000-4368-11eb-8b7e-5f68f499da3a.jpg)

**Comment by vvip-68** [comment]
У вас какая-то очень древняя версия приложения на андроид, которая совсем не соответствует текущей версии прошивки. Естественно, при таком несоответствии ничего работать не будет.
