### ISSUE TITLE
Работа с матрицей 13х12

### ISSUE THREAD

**Issue by sinegovsky-ivan** [vvip-68/GyverPanelWiFi#71]
Здравствуйте!
Для матрицы 13х12 имеет смысл использовать этот проект? Или нужно старую версию - https://github.com/vvip-68/GyverMatrixWiFi ?

**Comment by vvip-68** [comment]
Эта версия делает все то же, что и GyverMatrixWiFi плюч еще много чего помимо.
Какую версию использовать - ваше решение.
По железу они полностью совместимы. Залейте одну прошивку - посмотите. Залейте другую - сравните. Пользуйте ту, что больше понравится
