### ISSUE TITLE
WiFi Password

### ISSUE THREAD

**Issue by wm5** [vvip-68/GyverPanelWiFi#80]
Добрый день!
У меня возникла проблема с подключением к моей WiFi AP. Загвоздка оказалась в том, что длина переменной pass всего 16 байт. Мой пароль оказался немного длиннее и его менять мне не хотелось. Поэтому я изменил длину переменной и место в EEPROM до 24 байт. Это решило мою проблему. И теперь мне бы хотелось, чтобы сделанные мной изменения, каким то образом отразились в следующих релизах кода. Как это можно сделать? Иначе мне придется каждый раз при обновлении версий прошивки менять длину переменной pass под себя. чего бы мне не хотелось. Спасибо!

**Comment by vvip-68** [comment]
Вероятно это можно решить, сделав fork проекта в свой репозиторий и потом применять только те обновления, которые не противоречат сделанным вами изменениям. 

А в чем смысл длинных паролей? Паролей в 8 символов хватит на подбор перебором на несколько лет. В 14 символов - на столетия. Брутфорс на роутере мне кажется весьма сомнительным предприятием - да и кому нужно вламываться в вашу домашнюю сеть - что там можно найти? Но в качестве средства от паранойи - можно менять пароль раз в две недели.

Можете перенести пароль в конец свободной области EEPROM (правда, она уже заканчивается - там осталось что-то около 16 ячеек). Ну или перенести вообще в самый конец за область хранения бегущих строк. Вряд ли когда она будет заполнена этими стоками полностью...
