### ISSUE TITLE
Бегущая строка!

### ISSUE THREAD

**Issue by mcvall** [vvip-68/GyverPanelWiFi#83]
Ну как-то не прилично спрашивать, но всё-таки? Как её воспроизвести, если в приложении ничего не нажимается, текст не могу написать, нажимаются только макросы внизу, или нужно всё в скетче прописывать? Wiki читал, короче туплю жёстко)))

**Comment by vvip-68** [comment]
Первым пунктом - если в приложении ничего не нажимается - стоить обновить приложение до версии, которая совместима с версией прошивки.

**Comment by mcvall** [comment]
Я всегда переустанавливаю приложения из вновь скачанной папки.

**Comment by vvip-68** [comment]
То что описано как симптомы - несовместимость версии прошивки и приложения.
Дпугих идей у меня нет

**Comment by mcvall** [comment]
Переустановил, заработало, разбираюсь. Спасибо!
