### ISSUE TITLE
Неправильно работает формат даты для прошедшего события

### ISSUE THREAD

**Issue by limittouch** [vvip-68/GyverPanelWiFi#87]
> Пример:
> Строка D: _До Нового года осталось {P01.01.****#E#60#60}_
> Строка E: _-С Новым годом!!!!_

при добавлении года в текст отображаемой строки, после сообщения идет плюсовой отсчет
`-С Новым {D:yyyy} годом!!!!`
покажет 
_С Новым 2020 годом!!!!125 секунд_

**Comment by vvip-68** [comment]
Исправил
