### ISSUE TITLE
SD карта

### ISSUE THREAD

**Issue by Junior220584** [vvip-68/GyverPanelWiFi#91]
Уважаемый, vvip-68, буду благодарен за ответ)
Взял плату ESP8266 Amica, подключил все пины SD в разных вариациях, не работает. Пишет карта недоступна. В чем еще может быть причина? Почитал в инете, типа обязательно необходимо включить функцию FatFs, не знаю что это. 
Можете подсказать что еще предпринять? Может заплет с самой картой? Она отформатирована в FAT, на Ардуино МЕГА работает и инициализируется....

**Comment by vvip-68** [comment]
Я не знаю что за плата ESP8266 Amica.
Если что-то вроде такого
![image](https://user-images.githubusercontent.com/39353139/103274775-11d63c00-49f5-11eb-8ef5-6503b0f5e255.png)
SD карта должна быть подключена к тем зеленым пинам CLK MISO MOSI
В Wemos d1 mini это пины D5,D6,D7
![image](https://user-images.githubusercontent.com/39353139/103274888-595cc800-49f5-11eb-97ca-02552d79c2c0.png)

Это аппаратные пины SPI, именно они используются библиотекой для работы с картой.
Если у вас не так - работать не должно. Сделайте так.

**Comment by vvip-68** [comment]
Залейте тестовую прошивку из примеров - работа с SD-картой, проверьте работает она или нет

**Comment by Junior220584** [comment]
Плата как на первой картинке, просто производитель другой. С тестовыми прошивками тоже не работало, Сейчас вроде разобрался, буду дома проверять. В итоге когда указываешь пин CS - D8 - карта не инициализируется. С просто "8" все читается. Надо только с лентой проверить, будет ли он out файл читать. Причем раньше я пробовал с пинами 2, 4 - тоже не работало, может мой косяк, у меня слабая матчасть по ардуинке))
Но все равно огромное спасибо, осталось разобраться с текстовыми строками и макросами)))) видимо вопросы буду писать позже))
VVIP-68 СПАСИБО!!!

**Comment by vvip-68** [comment]
Соответствие всех этих номеров чистых и обозначений - 8->D8
сильно зависит от того какая плата выбрана в настройках.
Так 2 на Wemos -> D2, а на NodeMCU -> D4

Зависит от ропределения явно или неявно заданных
```
#define FASTLED_ESP8266_RAW_PIN_ORDER
#define FASTLED_ESP8266_NODEMCU_PIN_ORDER
#define FASTLED_ESP8266_D1_PIN_ORDER
```
https://github.com/FastLED/FastLED/wiki/ESP8266-notes

**Comment by Junior220584** [comment]
Понял, спасибо за науку! Я этого не знал.

**Comment by Junior220584** [comment]
vvip-68, можешь еще подсказать подсказать. Судя по всему все-таки ESP не открывает SD карту. Загрузил пример Listfile, он в мониторе порта не показывает какие файлы загружены, а просто выводит данные по кругу ниже. Плюс с вашим скетчем и наличием SD светодиоды не загораются от слова совсем(( Есть мысли? на всякий случай, напоминаю, что у меня ESP 8266 как на первой картинке выше. Подключаю SD так:
MISO - D6
MOSI - D7
CSK - D5
CS - D8

Как всегда заранее спасибо за ответ)

**Comment by Junior220584** [comment]
wdt reset
load 0x4010f000, len 3584, room 16 
tail 0
chksum 0xb0
csum 0xb0
v2843a5ac
~ld
Initializing SD card...
 ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 3584, room 16 
tail 0
chksum 0xb0
csum 0xb0
v2843a5ac
~ld
Initializing SD card...
 ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 3584, room 16 
tail 0
chksum 0xb0
csum 0xb0
v2843a5ac
~ld
Initializing SD card...

**Comment by vvip-68** [comment]
Нет, особо ничего сказать не могу. По приведенному логу - у тебя вообще контроллер по кругу перезагружается по wdt - Watchdog timer - когда скетч перестает отвечать N-ое кол-во времени (зависит от настройки, макс - 8сек) - он аппаратно сбрасывается и переходит в перезагрузку. Причину - не знаю. Попробуй другой шилд, попробуй другой микроконтроллер. Попробуй другой пример. Попробуй WDT на максимум поставить - ESP.wdtEnable(WDTO_8S); Попробуй подключиться к пинам зеленым те, что слева с аналогичным назначением.

На моей прошивке видимо по той же причине ни один диод не загорается - что контроллер не выходит на работчий режим.

**Comment by Junior220584** [comment]
Да, я так и понял, что он в перезагрузку уходит. Правда не понимаю почему( Шилд точно рабочий, с мегой работает. Контроллер тоже менял. К другим пинам подключался - ничего. Буду играться, но уже запарился))))))🤦‍♂️Спасибо!!!

**Comment by vvip-68** [comment]
А что за пример ты взял? Я у себя вообще примера listfile найти не могу
![image](https://user-images.githubusercontent.com/39353139/103366165-762bf500-4af4-11eb-9119-3ef559bf014a.png)

**Comment by Junior220584** [comment]
![image](https://user-images.githubusercontent.com/76660526/103366215-107b4100-4ad3-11eb-95e7-db4addfb1df6.png)

отсюда

**Comment by vvip-68** [comment]
А ты в скетче примера пины по умолчанию и инициализацию SD-карты исправлял на используемые?

**Comment by Junior220584** [comment]
правлю только эту строку #define SD_CS_PIN 8
остальное оставляю без изменений

**Comment by vvip-68** [comment]
У меня вообще такой строки в примере, открытом по твоему скриншоту нет...

**Comment by Junior220584** [comment]
прости, я уже другие примеры из твоей папки пробую)))
из listfile эта строка
 if (!SD.begin(8)) {

**Comment by vvip-68** [comment]
Вот твой пример из listfiles
if (!SD.begin(D8)) {

Вот плата
https://drive.google.com/file/d/1Q4xFQU-FcQiUhz37khUbZThNu4wVJLu0/view?usp=sharing

Вот результат
![image](https://user-images.githubusercontent.com/39353139/103367361-75489280-4af7-11eb-9e1e-debc8a7b45d7.png)

Что я делаю не так?

**Comment by Junior220584** [comment]
![image](https://user-images.githubusercontent.com/76660526/103367647-b11f3000-4ad6-11eb-900e-f302c26d5bab.png)
![image](https://user-images.githubusercontent.com/76660526/103367677-c72cf080-4ad6-11eb-937b-ffab333e2ebd.png)

Да ты то все правильно делаешь. Вопрос в том, что я делаю не так)))))

**Comment by vvip-68** [comment]
Ну попробуй на SD-карте MOSI и MISO провода местами поменять

**Comment by Junior220584** [comment]
сразу все попробовал после твоего первого сообщения, не помогает(((

**Comment by vvip-68** [comment]
Инициализация именно так в примере прописана?
if (!SD.begin(**D8**)) {

**Comment by Junior220584** [comment]
нет, ставил просто 8. С D8 она вообще не инициализируется

**Comment by Junior220584** [comment]
![image](https://user-images.githubusercontent.com/76660526/103368223-1889af80-4ad8-11eb-8776-50f22f8c851f.png)

**Comment by vvip-68** [comment]
Не уверен что "просто 8" проецируется на пин D8, к которому провод подключен
А что значит "вообще не инициализируется?

**Comment by Junior220584** [comment]
выше скрин отправил
Initializing SD card...initialization failed!

**Comment by vvip-68** [comment]
Ну, по крайней мере в вечный ребут не уходит

**Comment by Junior220584** [comment]
это да))) но от этого не легче)))))

**Comment by vvip-68** [comment]
И с обоими вариантами MOSI MISO так?

**Comment by Junior220584** [comment]
ага

**Comment by vvip-68** [comment]
А у тебя в описании твоей карты нет - может ей не 3 вольта надо, а она 5-тивольтовая и при подключении к 3 вольтам ей просто питалова не зватает? Там какой-нибудь микросхемы-стабилизатора нет? На плате самой вольтаж не прописан? 
Ты же при подключении к натуральной ардуине ей не 3 вольта давал, а 5?

**Comment by Junior220584** [comment]
Об этом тоже уже думал. От 5В такая же хня

**Comment by vvip-68** [comment]
Осталось только взять адаптер SD-карты и подпаяться напрямую к контактам адаптера без всяких этих шилдов. Как подпаиваться к контактам адаптера - есть на ютуб ролики

**Comment by vvip-68** [comment]
Вот, например - https://www.youtube.com/watch?v=pQo8lZ4CtLA&t=4s

**Comment by Junior220584** [comment]
понял, буду пробовать напрямую. Спасибо!

**Comment by Junior220584** [comment]
![image](https://user-images.githubusercontent.com/76660526/103371070-98674800-4adf-11eb-8bd3-b7dd8a078019.png)

сейчас дал нормальные 5В на шилд и сделал общую землю с ESP. Один раз прочиталась, больше не хочет. Уже успех)))

**Comment by vvip-68** [comment]
А раньше типа общей земли не было что ли? На фото же была? Как же она без общего минусового провода работать будет? Для напряжения нужно два проводника - сигнал и опора относительно которого мерить.

Вот этот мусор - вообще не понимаю что у тебя за вывод на экране? Откуда он? Такое впечатление, что где-то скорости не совпадают... Или контакта в проводе нет...

**Comment by Junior220584** [comment]
С мусором не знаю что делать. Мне кажется так всегда было. 
Раньше я просто подключал 5В на шилд, а земля была общая. Сейчас подключил прям от БП шилд и от шилда общую землю на ЕСП.

**Comment by vvip-68** [comment]
Я думал ты без питания, от USB все запитываешь. А еслли от отдельного БП - так конденсатор может нужно поставить? Если пульсации с БП идут - могут тоже проблемы создавать

**Comment by Junior220584** [comment]
Кондер на шилд или на ЕСП?

**Comment by vvip-68** [comment]
Если есть - поставь на оба. Если нет - на ESP...

**Comment by vvip-68** [comment]
Просто если отк омпового USB - там то питание нормальное без пульсаций...

**Comment by Junior220584** [comment]
есть. Ушел паять)) вернусь с обратной связью после праздников. Надеюсь смогу победить))
Спасибо!

**Comment by Junior220584** [comment]
Так до этого и пробовал просто от USB - не работало. Может действительно помехи от БП....очень на это надеюсь)

**Comment by Junior220584** [comment]
какие лучше?
есть 6,3V 470мкф
есть 6,3V  1000мкф

**Comment by vvip-68** [comment]
Любые. А если есть tit маленькие керамические параллельно на 20-33 ya - вообще шикарно

**Comment by Junior220584** [comment]
увы, такого добра, к сожалению нет. Пока попробую просто с кондерами

**Comment by vvip-68** [comment]
А когда от просто USB - питание VCC тоже с пина +5V брал?

**Comment by Junior220584** [comment]
да

**Comment by simonovich** [comment]
> Осталось только взять адаптер SD-карты и подпаяться напрямую к контактам адаптера без всяких этих шилдов. Как подпаиваться к контактам адаптера - есть на ютуб ролики

 Я подпаялся, теперь вопрос: а как дальше расширять? Чтобы работал плеер, доп. дисплей и т.д. SD карта занимается под себя много пинов. Вроде в DFPlayer есть слот для карт. Он может использоваться также и для анимаций?

**Comment by vvip-68** [comment]
> Вроде в DFPlayer есть слот для карт. Он может использоваться также и для анимаций?

Нет. DFPlayer - сам в себе вещь. Он даже список файлов с карты не отдает. Все что умеет - вернуть кол-во файлов в папке, остальные команды - только на вход - играй файл номер N в папке M.

Выход - ставить ESP32. В ней выходов больше.  В папке schemes есть схемы для ESP32 от энтузиастов, которые все это к ней подключали. Говорили, что у них все работает.

**Comment by Junior220584** [comment]
Уважаемый vvip-68, я разобрался со своим шилдом. Выпаял с него стабилизатор на 3,3В и все заработало. Флешку читает, но почему-то не запускает с нее эффекты. Все эффекты записаны в один файл new.out. Находятся в папке 24x11. Монитор порта этот файл видит, а гирлянда не воспроизводит. Как проверить? Можно как-то одну флешку запускать, без всех эффектов?

**Comment by vvip-68** [comment]
В папке Tools есть утилита JinxFramer. Вот она читает файл эффекта непосредственно с флэшки? Есть там кадры эффекта? Какой размер этого файла? 

Что в логах (в мониторе порта) при открытии этого файла, т.е при выборе в приложении на странице эффектов в комбобоксе этого файла?

**Comment by Junior220584** [comment]
Спасибо, как всегда за быстрый ответ! 
Framer читает файл с флешки, размер 772КБ. Приложения нет, я без андроида(((
![image](https://user-images.githubusercontent.com/76660526/103561718-f4a8de00-4eca-11eb-9ec5-73af2b065514.png)

**Comment by vvip-68** [comment]
Все кадры эффекта с флэшки видит Framer? Нет в конце черных? В логе не увидел чтения файла эффекта при попытке его воспроизвести. Как управлять без приложения - я не знаю.

**Comment by Junior220584** [comment]
Да, Framer всё видит. Второго вопроса не понял... Раньше монитор писал, типа воспроизведение ОК. Я думал, что в коде можно все настраивать)) это не так?

**Comment by vvip-68** [comment]
Вот так в логе выглядит" проигрывание" файла эффекта с SD-карты:

![image](https://user-images.githubusercontent.com/39353139/103563355-39df0700-4eef-11eb-81b7-82c49b6e352c.png)

Основная концепция прошивки - в коде настраивается ширина/высота матрицы, угол подключения. Больше пользователю ничего знать не нужно. При первом включении создается точка доступа к которой подсоединяется приложение со смартфона и далее все настройки и управление выполняются из приложения.

Естественно в коде можно задавать значения параметров и все такое. Но это должен быть продвинутый пользователь, с навыками программирования и знающий набор переменных в программе, структуру программы,  какая настройка (переменная) за что отвечает, в какой момент что должно происходить, чтобы отработало то или иное действие на матрице.

**Comment by Junior220584** [comment]
Да, я это понимаю, но в силу отсутствия андроида, пытаюсь разобраться в коде. Т.е. лучше обзавестись андроидом и не ипать себе мозг, верно?)

**Comment by vvip-68** [comment]
Ну, если это развивает мозг, не даёт ему атрофироваться - почему бы и нет?
Ваш выбор по какому пути идти.

**Comment by Junior220584** [comment]
да, спасибо, действительно развивает)))
Еще чуть-чуть помучаю... Записал на флешке бегущую строку "С НОВЫМ ГОДОМ!!!". Framer ее воспроизводит нормально, а гирлянда только "С НОВЫМ ГО". Не понимаю почему. Есть мысли? 
При этом на флешке 3 файла .out. А гирлянда воспроизводит только эту неполную бегущую строку и все.. Почему так?

**Comment by Junior220584** [comment]
Видимо разобрался. У меня каждый эффект в прошивке длится 10 секунд. Судя по всему флешка также воспроизводится это время. Это как-то исправляется?

**Comment by vvip-68** [comment]
Увеличить время эффекта до 20 секунд. Или сколько там нужно.

**Comment by Junior220584** [comment]
vvip-68, я правильно понимаю, что время проигрывания флешки и время проигрывания каждого эффекта в прошивке выставляется единым? Т.е. либо я ставлю 10 секунд и все эффекты будут проигрываться по 10 секунд, вне зависимости от того, что на флешке их может быть на 3 минуты (проиграются только первый 10 секунд), либо я ставлю максимальное значение проигрывания 3 минуты и тогда каждый эффект в прошивке будет проигрываться по 3 минуты, но зато флешка полностью? Это отдельно не настраивается?

**Comment by vvip-68** [comment]
Нет, отдельной настройки времени для каждого эффекта нет. Там один тамймер и одна настройка времени на все эффекты.

**Comment by Junior220584** [comment]
понятно, спасибо!
А как на флешке тогда проиграть записи на 2 минуты? Ставить на каждый эффект 120 секунд?

**Comment by vvip-68** [comment]
Либо переписать скетч, чтобы задавать время для каждого эффекта отдельно, либо хотя бы для эффекта с SD-карты специальное время, отличное от других эффектов

**Comment by Junior220584** [comment]
Да, я и подумал, что на SD задается отдельное время, ну или она просто полностью проигрывается, но в коде не нашел. Тогда по большому счету в ней и смысла нет, так как c SD проиграется один файл из 10 (условно) или первые 10 секунд большого файла (состоящего из набора в 10 эффектов, например). Максимально на что способна SD - это дополнить твою чудо-прошивку одним файлом из Jinx на 10 секунд, так что ли?)))

**Comment by vvip-68** [comment]
Проигрывание с SD-арты - такой же точно равноправный эффект как и все другие эффекты. Задача процедуры (подпрограммы) эффекта - каким-то образом сформировать массив цветных точек и "выплюнуть" сформированное на матрицу. Одни эффекты формируют кадр программно, другие - SD-карта - считывают кадр с файла на флэшке и "выплевывают" его на матрицу. Никакой разницы нет. Всё работает одинаково. Если эффекту задано формировать изображение на матрице 10 секунд - он и делает это. 

Большинство пользователей ставит время отображения эффекта 40-80 секунд. Ставить 10 сек на эффект - на мой взгляд - извращение. Но - up to you.

Эффект SD карта считывает набор файлов (оглавление) с флэшки и затем, каждый раз, когда запускется - он выбирает случайным образом какой файл "проигрывать". Если ты поставил 10 сек на эффект - да, будет проиграног 10 секунд этого файла. Но это исключительно твой выбор.

Если хочется, чтобы работало по другому - 5 сек на обычный эффект и три минуты на эффект с флэшки - надо переписать процедуры, которые определяют надо ли переключаться на другой эффект или продолжать воспроизводить этот. 
Можно воспроизводить его указанное специальное время, запуская файл заново, если он кончился. Или доигрывать файл до конца, потом переходить к следующему эффекту - всё как ты напишешь.

**Comment by Junior220584** [comment]
vvip-68, спасибо за развернутый ответ!
Конечно на вкус и цвет все карандаши разные, но я думаю, что проигрывать один эффект 80 секунд скучно. В моем понимании, было бы круто каждый эффект проиграть 10-15 секунд и идти к следующему (хотя этот параметр определен в прошивке и настраивается). Твоя прошивка с чтением SD-карты как раз позволяет неограниченно расширить набор эффектов и при наличии "вшитых" эффектов добавлять и разнообразить их с помощью Jinx. А для этого чтение с карты нужно программить под отдельное время. Итого на выходе получается классный продукт, который помимо основных твоих фишек, может модифицироваться под пользователя отдельно. Я естественно не такой гуру программирования, как ты, поэтому может обсудим сколько будет стоить написание кода, с учетом моих комментариев?)) Я действительно думаю, что такое развитие проекта актуально для многих. Здесь есть личка?

**Comment by vvip-68** [comment]
Здесь лички нету. Я обитаю в ВК - https://vk.com/iivanovii. Под заказ я пишу 600 руб/час.
Для расчета объема работ нужно знать точное ТЗ что нужно сделать.
В свою прошивку я внедряю только то, что нравится мне. Если мне что-то не подходит, но пользователю очень этого хочется - я могу специально для него выпустить отдельный "релиз" прошивки с его требованиями, под его запросы.

Время от времени - моя прошивка (по моим надобностям) продолжает развиваться, что-то меняется.
Поддержку всех выпущенных вариантов я не провожу. Внедрение и отладка нового кода занимает слишком много времени и сил, если реплицировать это во все варианты прошивок  Это либо за отдельные деньги, либо пользователи сами добавляют изменения в свой вариант прошивки, если могут. Ну или продолжают пользоваться тем, что есть, если не могут.

**Comment by vvip-68** [comment]
> А для этого чтение с карты нужно программить под отдельное время.

Сразу вопрос - как/где/ задается это отдельное время?

**Comment by vvip-68** [comment]
Сколько я видел эффектов в Jinx - они все повторяющиеся. То есть "уникального контента" эффекта - на 20 секунд максимум. Зачем мне писать огромные файлы с повторяющимся сюжетом, если я могу "зацикливать" повторяющийся 20-секундный фрагмент на 40-60-80 или сколько мне нужно секунд. Какая надобность разнообразные сюжеты "светового шоу" запихивать в один файл на 10 минут, если можно "проиграть" десять 60-секундных файлов?

**Comment by Junior220584** [comment]
Давай в личку, в ВК напишу сейчас
