### ISSUE TITLE
длинна паспорта WIFI

### ISSUE THREAD

**Issue by buba-911** [vvip-68/GyverPanelWiFi#94]
Спасибо автору за проект,
В программе количество символов ввода для паспорта ограниченно 16-ю. Как увеличить до 20?
Подскажите пожалуйста, что изменить в программе.

И ещё, в приложении на смартфоне нет выбора игр и выборе эффектов есть возможность выбрать только 1, тот который в данное время работает в демо режиме.

**Comment by vvip-68** [comment]
Третий человек, который использует пароли длиннее 16 символов... Интересно - какой в этом практический смысл?
Ей-богу проще пароль поменять - сократить.
Пароль сохраняется в EEPROM в файле eeprom.ino в ячейки 104-119, 
процедура сохранения - putPass() в строках 907 - 911, считывание пароля из памяти - getPass в строках 903-905.
Выбираешь в свободной не занятой ничем области памяти место, которого хватает для твоего пароля, меняешь в этих процедурах начальную ячейку чтения/записи и длину пароля. Меняешь так же размер массива для хранения - в a_def_soft.h строка 292 размер массива на свой увеличенный. Далее пробегаешься по всему тексту поиском, ищешь где этот массив используется и меняешь там размер на новый. 
Новую область хранения можно выбирать в конце неиспользуемой области (если т ам еще есть место) или вообще в конце области хранени строк - в адресах 4000 минус длина твоего пароля. Не проверял, но должно работать.

Далее если проект будет развиваться и что-то меняться / добавляться - помнить где и что ты поменял, чтобы потом восстановить свои изменения и следить чтобы добавление новых изменений автором не djilk в конфликт с твоими исправлениями
