### ISSUE TITLE
Возможность отключить часы

### ISSUE THREAD

**Issue by vAkUuMkA** [vvip-68/GyverPanelWiFi#95]
Здравствуйте, а есть возможность вообще отключить часы и оставить только эффекты?

**Comment by vvip-68** [comment]
В приложении на странице настройки часов снять галку "Часы поверх эффектов".

**Comment by vAkUuMkA** [comment]
А если нет приложения и хочется отключить из прошивки?

**Comment by vvip-68** [comment]
В основном файле в setup() в строке 99 написать

clockOverlayEnabled = false;
putClockOverlayEnabled(clockOverlayEnabled);
