### ISSUE TITLE
направление текста

### ISSUE THREAD

**Issue by Vit-But** [vvip-68/GyverPanelWiFi#96]
Подскажите что не так, текст, время выходят с лева на право. Где это поменять не нашел.

**Comment by vvip-68** [comment]
![image](https://user-images.githubusercontent.com/39353139/103376554-89988980-4b0f-11eb-9d78-a6a52ca2467a.png)

**Comment by Vit-But** [comment]
спасибо, все пересмотрел, а отзеркалить угол не подумал.....
