### ISSUE TITLE
Эффект тетрис и лабиринт

### ISSUE THREAD

**Issue by mcvall** [vvip-68/GyverPanelWiFi#97]
Время смены эффектов установил 15сек. Когда очередь доходит до тетриса и лабиринта, они живут своей жизнью, т.е. могут длиться в два раза дольше. Можно как-то поправить или как вообще их убрать из прошивки?

**Comment by vvip-68** [comment]
Поправить: в custom.ino в строках 652-558 убрать проверку ожидания завершения игры по флагу gameOverFlag, чтобы не ждало пока игра закончится

Убрать - там где объявляется список эффектов - a_def_soft.h - MC_TETRIS и MC_MAZE перенести в конец списка перенумеровав эффекты,  MAX_EFFECT поправить, так, чтобы их номера были за пределами MAX_EFFECT, в списке названий эффектов в строках 22-30 также привести порядок в соответствии с перенумерованным
