### ISSUE TITLE
Weather Yandex

### ISSUE THREAD

**Issue by simonovich** [vvip-68/GyverPanelWiFi#99]
Получил сообщение с ошибкой по какой-то недокументированной команде которой ручками точно не посылал:
`{"message":"unknown command","text":"неизвестная команда '$13 3 1;'"}`

**Comment by vvip-68** [comment]
Такой команды действительно нет в актуальной версии прошивки.
Она была в одной из предыдущих версий, но потом была убрана после переделки механизма обработки текстовых строк.
То, что у вас эта команда отправляется в контроллер - скорее всего свидетельствует, что вы используете устаревшую (и не совместимую с текущей версией прошивки) версию приложения на телефоне.
